// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gles31

/*
#cgo LDFLAGS: -lGLESv3
#include <GLES3/gl31.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Byte type as declared in gl31.h:64
type Byte int8

// Clampf type as declared in gl31.h:65
type Clampf float32

// Fixed type as declared in gl31.h:66
type Fixed int32

// Short type as declared in gl31.h:67
type Short int16

// Ushort type as declared in gl31.h:68
type Ushort uint16

// Void type as declared in gl31.h:69
type Void [0]byte

// Sync as declared in gl31.h:70
type Sync C.GLsync

// Int64 type as declared in gl31.h:71
type Int64 int32

// Uint64 type as declared in gl31.h:72
type Uint64 uint32

// Enum type as declared in gl31.h:73
type Enum uint32

// Uint type as declared in gl31.h:74
type Uint uint32

// Char type as declared in gl31.h:75
type Char byte

// Float type as declared in gl31.h:76
type Float float32

// Sizeiptr type as declared in gl31.h:77
type Sizeiptr int32

// Intptr type as declared in gl31.h:78
type Intptr int32

// Bitfield type as declared in gl31.h:79
type Bitfield uint32

// Int type as declared in gl31.h:80
type Int int32

// Boolean type as declared in gl31.h:81
type Boolean byte

// Sizei type as declared in gl31.h:82
type Sizei int32

// Ubyte type as declared in gl31.h:83
type Ubyte byte

// Half type as declared in gl31.h:675
type Half uint16
