// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gles3

/*
#cgo LDFLAGS: -lGLESv3
#include <GLES3/gl3.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Byte type as declared in gl3.h:62
type Byte int8

// Clampf type as declared in gl3.h:63
type Clampf float32

// Fixed type as declared in gl3.h:64
type Fixed int32

// Short type as declared in gl3.h:65
type Short int16

// Ushort type as declared in gl3.h:66
type Ushort uint16

// Void type as declared in gl3.h:67
type Void [0]byte

// Sync as declared in gl3.h:68
type Sync C.GLsync

// Int64 type as declared in gl3.h:69
type Int64 int32

// Uint64 type as declared in gl3.h:70
type Uint64 uint32

// Enum type as declared in gl3.h:71
type Enum uint32

// Uint type as declared in gl3.h:72
type Uint uint32

// Char type as declared in gl3.h:73
type Char byte

// Float type as declared in gl3.h:74
type Float float32

// Sizeiptr type as declared in gl3.h:75
type Sizeiptr int32

// Intptr type as declared in gl3.h:76
type Intptr int32

// Bitfield type as declared in gl3.h:77
type Bitfield uint32

// Int type as declared in gl3.h:78
type Int int32

// Boolean type as declared in gl3.h:79
type Boolean byte

// Sizei type as declared in gl3.h:80
type Sizei int32

// Ubyte type as declared in gl3.h:81
type Ubyte byte

// Half type as declared in gl3.h:673
type Half uint16
