// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package android

/*
#cgo LDFLAGS: -landroid -llog
#include <android/api-level.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/configuration.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log.h>
#include <android/looper.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <android/obb.h>
#include <android/rect.h>
#include <android/sensor.h>
#include <android/storage_manager.h>
#include <android/window.h>
#include <jni.h>
#include "jni_call.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// AssetManagerH as defined in asset_manager.h:27

	// AssetManagerJniH as defined in asset_manager_jni.h:27

	// ConfigurationH as defined in configuration.h:27

	// DataSpaceH as defined in data_space.h:29

	// HardwareBufferH as defined in hardware_buffer.h:46

	// MotionEventActionPointerIndexShift as defined in input.h:280
	MotionEventActionPointerIndexShift = 8
	// LooperH as defined in looper.h:27

	// NativeActivityH as defined in native_activity.h:27

	// NativeWindowH as defined in native_window.h:34

	// NativeWindowJniH as defined in native_window_jni.h:27

	// ObbH as defined in obb.h:27

	// RectH as defined in rect.h:27

	// SensorH as defined in sensor.h:30

	// SensorFifoCountInvalid as defined in sensor.h:69
	SensorFifoCountInvalid = (-1)
	// SensorInvalid as defined in sensor.h:71
	SensorInvalid = (-1)
	// SensorStandardGravity as defined in sensor.h:428
	SensorStandardGravity = (9.80665)
	// SensorMagneticFieldEarthMax as defined in sensor.h:430
	SensorMagneticFieldEarthMax = (60.0)
	// SensorMagneticFieldEarthMin as defined in sensor.h:432
	SensorMagneticFieldEarthMin = (30.0)
	// StorageManagerH as defined in storage_manager.h:27

	// WindowH as defined in window.h:27

	// JNIimport as defined in jni.h:1104

	// JNIcall as defined in jni.h:1106

	// JNIFalse as defined in jni.h:1123
	JNIFalse = 0
	// JNITrue as defined in jni.h:1124
	JNITrue = 1
	// JNIVersion11 as defined in jni.h:1126
	JNIVersion11 = 0x00010001
	// JNIVersion12 as defined in jni.h:1127
	JNIVersion12 = 0x00010002
	// JNIVersion14 as defined in jni.h:1128
	JNIVersion14 = 0x00010004
	// JNIVersion16 as defined in jni.h:1129
	JNIVersion16 = 0x00010006
	// JNIOk as defined in jni.h:1131
	JNIOk = (0)
	// JNIErr as defined in jni.h:1132
	JNIErr = (-1)
	// JNIEdetached as defined in jni.h:1133
	JNIEdetached = (-2)
	// JNIEversion as defined in jni.h:1134
	JNIEversion = (-3)
	// JNIEnomem as defined in jni.h:1135
	JNIEnomem = (-4)
	// JNIEexist as defined in jni.h:1136
	JNIEexist = (-5)
	// JNIEinval as defined in jni.h:1137
	JNIEinval = (-6)
	// JNICommit as defined in jni.h:1139
	JNICommit = 1
	// JNIAbort as defined in jni.h:1140
	JNIAbort = 2

// JNICallH as defined in jni_call.h:2

)

// LogPriority as declared in log.h:92
type LogPriority int32

// LogPriority enumeration from log.h:92
const (
	LogUnknown LogPriority = iota
	LogDefault LogPriority = 1
	LogVerbose LogPriority = 2
	LogDebug   LogPriority = 3
	LogInfo    LogPriority = 4
	LogWarn    LogPriority = 5
	LogError   LogPriority = 6
	LogFatal   LogPriority = 7
	LogSilent  LogPriority = 8
)

// JobjectRefType as declared in jni.h:126
type JobjectRefType int32

// JobjectRefType enumeration from jni.h:126
const (
	JNIinvalidreftype    JobjectRefType = iota
	JNIlocalreftype      JobjectRefType = 1
	JNIglobalreftype     JobjectRefType = 2
	JNIweakglobalreftype JobjectRefType = 3
)

const (
	// AssetModeUnknown as declared in asset_manager.h:78
	AssetModeUnknown = iota
	// AssetModeRandom as declared in asset_manager.h:80
	AssetModeRandom = 1
	// AssetModeStreaming as declared in asset_manager.h:82
	AssetModeStreaming = 2
	// AssetModeBuffer as declared in asset_manager.h:84
	AssetModeBuffer = 3
)

const (
	// ConfigurationOrientationAny as declared in configuration.h:58
	ConfigurationOrientationAny = 0x0000
	// ConfigurationOrientationPort as declared in configuration.h:64
	ConfigurationOrientationPort = 0x0001
	// ConfigurationOrientationLand as declared in configuration.h:70
	ConfigurationOrientationLand = 0x0002
	// ConfigurationOrientationSquare as declared in configuration.h:72
	ConfigurationOrientationSquare = 0x0003
	// ConfigurationTouchscreenAny as declared in configuration.h:75
	ConfigurationTouchscreenAny = 0x0000
	// ConfigurationTouchscreenNotouch as declared in configuration.h:81
	ConfigurationTouchscreenNotouch = 0x0001
	// ConfigurationTouchscreenStylus as declared in configuration.h:83
	ConfigurationTouchscreenStylus = 0x0002
	// ConfigurationTouchscreenFinger as declared in configuration.h:89
	ConfigurationTouchscreenFinger = 0x0003
	// ConfigurationDensityDefault as declared in configuration.h:92
	ConfigurationDensityDefault = 0
	// ConfigurationDensityLow as declared in configuration.h:98
	ConfigurationDensityLow = 120
	// ConfigurationDensityMedium as declared in configuration.h:104
	ConfigurationDensityMedium = 160
	// ConfigurationDensityTv as declared in configuration.h:110
	ConfigurationDensityTv = 213
	// ConfigurationDensityHigh as declared in configuration.h:116
	ConfigurationDensityHigh = 240
	// ConfigurationDensityXhigh as declared in configuration.h:122
	ConfigurationDensityXhigh = 320
	// ConfigurationDensityXxhigh as declared in configuration.h:128
	ConfigurationDensityXxhigh = 480
	// ConfigurationDensityXxxhigh as declared in configuration.h:134
	ConfigurationDensityXxxhigh = 640
	// ConfigurationDensityAny as declared in configuration.h:136
	ConfigurationDensityAny = 0xfffe
	// ConfigurationDensityNone as declared in configuration.h:138
	ConfigurationDensityNone = 0xffff
	// ConfigurationKeyboardAny as declared in configuration.h:141
	ConfigurationKeyboardAny = 0x0000
	// ConfigurationKeyboardNokeys as declared in configuration.h:147
	ConfigurationKeyboardNokeys = 0x0001
	// ConfigurationKeyboardQwerty as declared in configuration.h:153
	ConfigurationKeyboardQwerty = 0x0002
	// ConfigurationKeyboard12key as declared in configuration.h:159
	ConfigurationKeyboard12key = 0x0003
	// ConfigurationNavigationAny as declared in configuration.h:162
	ConfigurationNavigationAny = 0x0000
	// ConfigurationNavigationNonav as declared in configuration.h:168
	ConfigurationNavigationNonav = 0x0001
	// ConfigurationNavigationDpad as declared in configuration.h:174
	ConfigurationNavigationDpad = 0x0002
	// ConfigurationNavigationTrackball as declared in configuration.h:180
	ConfigurationNavigationTrackball = 0x0003
	// ConfigurationNavigationWheel as declared in configuration.h:186
	ConfigurationNavigationWheel = 0x0004
	// ConfigurationKeyshiddenAny as declared in configuration.h:189
	ConfigurationKeyshiddenAny = 0x0000
	// ConfigurationKeyshiddenNo as declared in configuration.h:195
	ConfigurationKeyshiddenNo = 0x0001
	// ConfigurationKeyshiddenYes as declared in configuration.h:201
	ConfigurationKeyshiddenYes = 0x0002
	// ConfigurationKeyshiddenSoft as declared in configuration.h:207
	ConfigurationKeyshiddenSoft = 0x0003
	// ConfigurationNavhiddenAny as declared in configuration.h:210
	ConfigurationNavhiddenAny = 0x0000
	// ConfigurationNavhiddenNo as declared in configuration.h:216
	ConfigurationNavhiddenNo = 0x0001
	// ConfigurationNavhiddenYes as declared in configuration.h:222
	ConfigurationNavhiddenYes = 0x0002
	// ConfigurationScreensizeAny as declared in configuration.h:225
	ConfigurationScreensizeAny = 0x00
	// ConfigurationScreensizeSmall as declared in configuration.h:232
	ConfigurationScreensizeSmall = 0x01
	// ConfigurationScreensizeNormal as declared in configuration.h:239
	ConfigurationScreensizeNormal = 0x02
	// ConfigurationScreensizeLarge as declared in configuration.h:246
	ConfigurationScreensizeLarge = 0x03
	// ConfigurationScreensizeXlarge as declared in configuration.h:253
	ConfigurationScreensizeXlarge = 0x04
	// ConfigurationScreenlongAny as declared in configuration.h:256
	ConfigurationScreenlongAny = 0x00
	// ConfigurationScreenlongNo as declared in configuration.h:262
	ConfigurationScreenlongNo = 0x1
	// ConfigurationScreenlongYes as declared in configuration.h:268
	ConfigurationScreenlongYes = 0x2
	// ConfigurationScreenroundAny as declared in configuration.h:270
	ConfigurationScreenroundAny = 0x00
	// ConfigurationScreenroundNo as declared in configuration.h:271
	ConfigurationScreenroundNo = 0x1
	// ConfigurationScreenroundYes as declared in configuration.h:272
	ConfigurationScreenroundYes = 0x2
	// ConfigurationWideColorGamutAny as declared in configuration.h:275
	ConfigurationWideColorGamutAny = 0x00
	// ConfigurationWideColorGamutNo as declared in configuration.h:281
	ConfigurationWideColorGamutNo = 0x1
	// ConfigurationWideColorGamutYes as declared in configuration.h:287
	ConfigurationWideColorGamutYes = 0x2
	// ConfigurationHdrAny as declared in configuration.h:290
	ConfigurationHdrAny = 0x00
	// ConfigurationHdrNo as declared in configuration.h:296
	ConfigurationHdrNo = 0x1
	// ConfigurationHdrYes as declared in configuration.h:302
	ConfigurationHdrYes = 0x2
	// ConfigurationUiModeTypeAny as declared in configuration.h:305
	ConfigurationUiModeTypeAny = 0x00
	// ConfigurationUiModeTypeNormal as declared in configuration.h:311
	ConfigurationUiModeTypeNormal = 0x01
	// ConfigurationUiModeTypeDesk as declared in configuration.h:316
	ConfigurationUiModeTypeDesk = 0x02
	// ConfigurationUiModeTypeCar as declared in configuration.h:321
	ConfigurationUiModeTypeCar = 0x03
	// ConfigurationUiModeTypeTelevision as declared in configuration.h:326
	ConfigurationUiModeTypeTelevision = 0x04
	// ConfigurationUiModeTypeAppliance as declared in configuration.h:331
	ConfigurationUiModeTypeAppliance = 0x05
	// ConfigurationUiModeTypeWatch as declared in configuration.h:336
	ConfigurationUiModeTypeWatch = 0x06
	// ConfigurationUiModeTypeVrHeadset as declared in configuration.h:341
	ConfigurationUiModeTypeVrHeadset = 0x07
	// ConfigurationUiModeNightAny as declared in configuration.h:344
	ConfigurationUiModeNightAny = 0x00
	// ConfigurationUiModeNightNo as declared in configuration.h:349
	ConfigurationUiModeNightNo = 0x1
	// ConfigurationUiModeNightYes as declared in configuration.h:354
	ConfigurationUiModeNightYes = 0x2
	// ConfigurationScreenWidthDpAny as declared in configuration.h:357
	ConfigurationScreenWidthDpAny = 0x0000
	// ConfigurationScreenHeightDpAny as declared in configuration.h:360
	ConfigurationScreenHeightDpAny = 0x0000
	// ConfigurationSmallestScreenWidthDpAny as declared in configuration.h:363
	ConfigurationSmallestScreenWidthDpAny = 0x0000
	// ConfigurationLayoutdirAny as declared in configuration.h:366
	ConfigurationLayoutdirAny = 0x00
	// ConfigurationLayoutdirLtr as declared in configuration.h:371
	ConfigurationLayoutdirLtr = 0x01
	// ConfigurationLayoutdirRtl as declared in configuration.h:376
	ConfigurationLayoutdirRtl = 0x02
	// ConfigurationMcc as declared in configuration.h:383
	ConfigurationMcc = 0x0001
	// ConfigurationMnc as declared in configuration.h:389
	ConfigurationMnc = 0x0002
	// ConfigurationLocale as declared in configuration.h:395
	ConfigurationLocale = 0x0004
	// ConfigurationTouchscreen as declared in configuration.h:401
	ConfigurationTouchscreen = 0x0008
	// ConfigurationKeyboard as declared in configuration.h:407
	ConfigurationKeyboard = 0x0010
	// ConfigurationKeyboardHidden as declared in configuration.h:413
	ConfigurationKeyboardHidden = 0x0020
	// ConfigurationNavigation as declared in configuration.h:419
	ConfigurationNavigation = 0x0040
	// ConfigurationOrientation as declared in configuration.h:425
	ConfigurationOrientation = 0x0080
	// ConfigurationDensity as declared in configuration.h:431
	ConfigurationDensity = 0x0100
	// ConfigurationScreenSize as declared in configuration.h:437
	ConfigurationScreenSize = 0x0200
	// ConfigurationVersion as declared in configuration.h:443
	ConfigurationVersion = 0x0400
	// ConfigurationScreenLayout as declared in configuration.h:447
	ConfigurationScreenLayout = 0x0800
	// ConfigurationUiMode as declared in configuration.h:453
	ConfigurationUiMode = 0x1000
	// ConfigurationSmallestScreenSize as declared in configuration.h:459
	ConfigurationSmallestScreenSize = 0x2000
	// ConfigurationLayoutdir as declared in configuration.h:465
	ConfigurationLayoutdir = 0x4000
	// ConfigurationScreenRound as declared in configuration.h:466
	ConfigurationScreenRound = 0x8000
	// ConfigurationColorMode as declared in configuration.h:472
	ConfigurationColorMode = 0x10000
	// ConfigurationMncZero as declared in configuration.h:477
	ConfigurationMncZero = 0xffff
)

const (
	// DataspaceUnknown as declared in data_space.h:50
	DataspaceUnknown = iota
	// DataspaceScrgbLinear as declared in data_space.h:398
	DataspaceScrgbLinear = 406913024
	// DataspaceSrgb as declared in data_space.h:413
	DataspaceSrgb = 142671872
	// DataspaceScrgb as declared in data_space.h:427
	DataspaceScrgb = 411107328
	// DataspaceDisplayP3 as declared in data_space.h:435
	DataspaceDisplayP3 = 143261696
	// DataspaceBt2020Pq as declared in data_space.h:444
	DataspaceBt2020Pq = 163971072
	// DataspaceBt2020ItuPq as declared in data_space.h:453
	DataspaceBt2020ItuPq = 298188800
	// DataspaceAdobeRgb as declared in data_space.h:462
	DataspaceAdobeRgb = 151715840
	// DataspaceJfif as declared in data_space.h:471
	DataspaceJfif = 146931712
	// DataspaceBt601625 as declared in data_space.h:480
	DataspaceBt601625 = 281149440
	// DataspaceBt601525 as declared in data_space.h:489
	DataspaceBt601525 = 281280512
	// DataspaceBt2020 as declared in data_space.h:498
	DataspaceBt2020 = 147193856
	// DataspaceBt709 as declared in data_space.h:507
	DataspaceBt709 = 281083904
	// DataspaceDciP3 as declared in data_space.h:518
	DataspaceDciP3 = 155844608
	// DataspaceSrgbLinear as declared in data_space.h:530
	DataspaceSrgbLinear = 138477568
	// DataspaceBt2020Hlg as declared in data_space.h:537
	DataspaceBt2020Hlg = 168165376
	// DataspaceBt2020ItuHlg as declared in data_space.h:544
	DataspaceBt2020ItuHlg = 302383104
)

const (
	// HardwarebufferFormatR8g8b8a8Unorm as declared in hardware_buffer.h:65
	HardwarebufferFormatR8g8b8a8Unorm = 1
	// HardwarebufferFormatR8g8b8x8Unorm as declared in hardware_buffer.h:74
	HardwarebufferFormatR8g8b8x8Unorm = 2
	// HardwarebufferFormatR8g8b8Unorm as declared in hardware_buffer.h:81
	HardwarebufferFormatR8g8b8Unorm = 3
	// HardwarebufferFormatR5g6b5Unorm as declared in hardware_buffer.h:88
	HardwarebufferFormatR5g6b5Unorm = 4
	// HardwarebufferFormatR16g16b16a16Float as declared in hardware_buffer.h:95
	HardwarebufferFormatR16g16b16a16Float = 0x16
	// HardwarebufferFormatR10g10b10a2Unorm as declared in hardware_buffer.h:102
	HardwarebufferFormatR10g10b10a2Unorm = 0x2b
	// HardwarebufferFormatBlob as declared in hardware_buffer.h:110
	HardwarebufferFormatBlob = 0x21
	// HardwarebufferFormatD16Unorm as declared in hardware_buffer.h:117
	HardwarebufferFormatD16Unorm = 0x30
	// HardwarebufferFormatD24Unorm as declared in hardware_buffer.h:124
	HardwarebufferFormatD24Unorm = 0x31
	// HardwarebufferFormatD24UnormS8Uint as declared in hardware_buffer.h:131
	HardwarebufferFormatD24UnormS8Uint = 0x32
	// HardwarebufferFormatD32Float as declared in hardware_buffer.h:138
	HardwarebufferFormatD32Float = 0x33
	// HardwarebufferFormatD32FloatS8Uint as declared in hardware_buffer.h:145
	HardwarebufferFormatD32FloatS8Uint = 0x34
	// HardwarebufferFormatS8Uint as declared in hardware_buffer.h:152
	HardwarebufferFormatS8Uint = 0x35
	// HardwarebufferFormatY8cb8cr8420 as declared in hardware_buffer.h:160
	HardwarebufferFormatY8cb8cr8420 = 0x23
	// HardwarebufferFormatYcbcrP010 as declared in hardware_buffer.h:168
	HardwarebufferFormatYcbcrP010 = 0x36
	// HardwarebufferFormatR8Unorm as declared in hardware_buffer.h:175
	HardwarebufferFormatR8Unorm = 0x38
	// HardwarebufferFormatR16Uint as declared in hardware_buffer.h:182
	HardwarebufferFormatR16Uint = 0x39
	// HardwarebufferFormatR16g16Uint as declared in hardware_buffer.h:189
	HardwarebufferFormatR16g16Uint = 0x3a
	// HardwarebufferFormatR10g10b10a10Unorm as declared in hardware_buffer.h:196
	HardwarebufferFormatR10g10b10a10Unorm = 0x3b
)

const (
	// HardwarebufferUsageCpuReadNever as declared in hardware_buffer.h:209
	HardwarebufferUsageCpuReadNever = uint64(0)
	// HardwarebufferUsageCpuReadRarely as declared in hardware_buffer.h:216
	HardwarebufferUsageCpuReadRarely = uint64(2)
	// HardwarebufferUsageCpuReadOften as declared in hardware_buffer.h:223
	HardwarebufferUsageCpuReadOften = uint64(3)
	// HardwarebufferUsageCpuReadMask as declared in hardware_buffer.h:226
	HardwarebufferUsageCpuReadMask = uint64(0xF)
	// HardwarebufferUsageCpuWriteNever as declared in hardware_buffer.h:233
	HardwarebufferUsageCpuWriteNever = uint64(0) << 4
	// HardwarebufferUsageCpuWriteRarely as declared in hardware_buffer.h:240
	HardwarebufferUsageCpuWriteRarely = uint64(2) << 4
	// HardwarebufferUsageCpuWriteOften as declared in hardware_buffer.h:247
	HardwarebufferUsageCpuWriteOften = uint64(3) << 4
	// HardwarebufferUsageCpuWriteMask as declared in hardware_buffer.h:249
	HardwarebufferUsageCpuWriteMask = uint64(0xF) << 4
	// HardwarebufferUsageGpuSampledImage as declared in hardware_buffer.h:251
	HardwarebufferUsageGpuSampledImage = uint64(1) << 8
	// HardwarebufferUsageGpuFramebuffer as declared in hardware_buffer.h:253
	HardwarebufferUsageGpuFramebuffer = uint64(1) << 9
	// HardwarebufferUsageGpuColorOutput as declared in hardware_buffer.h:264
	HardwarebufferUsageGpuColorOutput = HardwarebufferUsageGpuFramebuffer
	// HardwarebufferUsageComposerOverlay as declared in hardware_buffer.h:275
	HardwarebufferUsageComposerOverlay = uint64(1) << 11
	// HardwarebufferUsageProtectedContent as declared in hardware_buffer.h:286
	HardwarebufferUsageProtectedContent = uint64(1) << 14
	// HardwarebufferUsageVideoEncode as declared in hardware_buffer.h:288
	HardwarebufferUsageVideoEncode = uint64(1) << 16
	// HardwarebufferUsageSensorDirectData as declared in hardware_buffer.h:293
	HardwarebufferUsageSensorDirectData = uint64(1) << 23
	// HardwarebufferUsageGpuDataBuffer as declared in hardware_buffer.h:298
	HardwarebufferUsageGpuDataBuffer = uint64(1) << 24
	// HardwarebufferUsageGpuCubeMap as declared in hardware_buffer.h:306
	HardwarebufferUsageGpuCubeMap = uint64(1) << 25
	// HardwarebufferUsageGpuMipmapComplete as declared in hardware_buffer.h:312
	HardwarebufferUsageGpuMipmapComplete = uint64(1) << 26
	// HardwarebufferUsageFrontBuffer as declared in hardware_buffer.h:322
	HardwarebufferUsageFrontBuffer = uint64(1) << 32
	// HardwarebufferUsageVendor0 as declared in hardware_buffer.h:324
	HardwarebufferUsageVendor0 = uint64(1) << 28
	// HardwarebufferUsageVendor1 as declared in hardware_buffer.h:325
	HardwarebufferUsageVendor1 = uint64(1) << 29
	// HardwarebufferUsageVendor2 as declared in hardware_buffer.h:326
	HardwarebufferUsageVendor2 = uint64(1) << 30
	// HardwarebufferUsageVendor3 as declared in hardware_buffer.h:327
	HardwarebufferUsageVendor3 = uint64(1) << 31
	// HardwarebufferUsageVendor4 as declared in hardware_buffer.h:328
	HardwarebufferUsageVendor4 = uint64(1) << 48
	// HardwarebufferUsageVendor5 as declared in hardware_buffer.h:329
	HardwarebufferUsageVendor5 = uint64(1) << 49
	// HardwarebufferUsageVendor6 as declared in hardware_buffer.h:330
	HardwarebufferUsageVendor6 = uint64(1) << 50
	// HardwarebufferUsageVendor7 as declared in hardware_buffer.h:331
	HardwarebufferUsageVendor7 = uint64(1) << 51
	// HardwarebufferUsageVendor8 as declared in hardware_buffer.h:332
	HardwarebufferUsageVendor8 = uint64(1) << 52
	// HardwarebufferUsageVendor9 as declared in hardware_buffer.h:333
	HardwarebufferUsageVendor9 = uint64(1) << 53
	// HardwarebufferUsageVendor10 as declared in hardware_buffer.h:334
	HardwarebufferUsageVendor10 = uint64(1) << 54
	// HardwarebufferUsageVendor11 as declared in hardware_buffer.h:335
	HardwarebufferUsageVendor11 = uint64(1) << 55
	// HardwarebufferUsageVendor12 as declared in hardware_buffer.h:336
	HardwarebufferUsageVendor12 = uint64(1) << 56
	// HardwarebufferUsageVendor13 as declared in hardware_buffer.h:337
	HardwarebufferUsageVendor13 = uint64(1) << 57
	// HardwarebufferUsageVendor14 as declared in hardware_buffer.h:338
	HardwarebufferUsageVendor14 = uint64(1) << 58
	// HardwarebufferUsageVendor15 as declared in hardware_buffer.h:339
	HardwarebufferUsageVendor15 = uint64(1) << 59
	// HardwarebufferUsageVendor16 as declared in hardware_buffer.h:340
	HardwarebufferUsageVendor16 = uint64(1) << 60
	// HardwarebufferUsageVendor17 as declared in hardware_buffer.h:341
	HardwarebufferUsageVendor17 = uint64(1) << 61
	// HardwarebufferUsageVendor18 as declared in hardware_buffer.h:342
	HardwarebufferUsageVendor18 = uint64(1) << 62
	// HardwarebufferUsageVendor19 as declared in hardware_buffer.h:343
	HardwarebufferUsageVendor19 = uint64(1) << 63
)

const (
	// KeyStateUnknown as declared in input.h:74
	KeyStateUnknown = -1
	// KeyStateUp as declared in input.h:77
	KeyStateUp = 0
	// KeyStateDown as declared in input.h:80
	KeyStateDown = 1
	// KeyStateVirtual as declared in input.h:83
	KeyStateVirtual = 2
)

const (
	// MetaNone as declared in input.h:91
	MetaNone = iota
	// MetaAltOn as declared in input.h:94
	MetaAltOn = 0x02
	// MetaAltLeftOn as declared in input.h:97
	MetaAltLeftOn = 0x10
	// MetaAltRightOn as declared in input.h:100
	MetaAltRightOn = 0x20
	// MetaShiftOn as declared in input.h:103
	MetaShiftOn = 0x01
	// MetaShiftLeftOn as declared in input.h:106
	MetaShiftLeftOn = 0x40
	// MetaShiftRightOn as declared in input.h:109
	MetaShiftRightOn = 0x80
	// MetaSymOn as declared in input.h:112
	MetaSymOn = 0x04
	// MetaFunctionOn as declared in input.h:115
	MetaFunctionOn = 0x08
	// MetaCtrlOn as declared in input.h:118
	MetaCtrlOn = 0x1000
	// MetaCtrlLeftOn as declared in input.h:121
	MetaCtrlLeftOn = 0x2000
	// MetaCtrlRightOn as declared in input.h:124
	MetaCtrlRightOn = 0x4000
	// MetaMetaOn as declared in input.h:127
	MetaMetaOn = 0x10000
	// MetaMetaLeftOn as declared in input.h:130
	MetaMetaLeftOn = 0x20000
	// MetaMetaRightOn as declared in input.h:133
	MetaMetaRightOn = 0x40000
	// MetaCapsLockOn as declared in input.h:136
	MetaCapsLockOn = 0x100000
	// MetaNumLockOn as declared in input.h:139
	MetaNumLockOn = 0x200000
	// MetaScrollLockOn as declared in input.h:142
	MetaScrollLockOn = 0x400000
)

const (
	// InputEventTypeKey as declared in input.h:159
	InputEventTypeKey = 1
	// InputEventTypeMotion as declared in input.h:162
	InputEventTypeMotion = 2
	// InputEventTypeFocus as declared in input.h:165
	InputEventTypeFocus = 3
	// InputEventTypeCapture as declared in input.h:168
	InputEventTypeCapture = 4
	// InputEventTypeDrag as declared in input.h:171
	InputEventTypeDrag = 5
	// InputEventTypeTouchMode as declared in input.h:174
	InputEventTypeTouchMode = 6
)

const (
	// KeyEventActionDown as declared in input.h:182
	KeyEventActionDown = iota
	// KeyEventActionUp as declared in input.h:185
	KeyEventActionUp = 1
	// KeyEventActionMultiple as declared in input.h:193
	KeyEventActionMultiple = 2
)

const (
	// KeyEventFlagWokeHere as declared in input.h:201
	KeyEventFlagWokeHere = 0x1
	// KeyEventFlagSoftKeyboard as declared in input.h:204
	KeyEventFlagSoftKeyboard = 0x2
	// KeyEventFlagKeepTouchMode as declared in input.h:207
	KeyEventFlagKeepTouchMode = 0x4
	// KeyEventFlagFromSystem as declared in input.h:215
	KeyEventFlagFromSystem = 0x8
	// KeyEventFlagEditorAction as declared in input.h:224
	KeyEventFlagEditorAction = 0x10
	// KeyEventFlagCanceled as declared in input.h:236
	KeyEventFlagCanceled = 0x20
	// KeyEventFlagVirtualHardKey as declared in input.h:243
	KeyEventFlagVirtualHardKey = 0x40
	// KeyEventFlagLongPress as declared in input.h:249
	KeyEventFlagLongPress = 0x80
	// KeyEventFlagCanceledLongPress as declared in input.h:255
	KeyEventFlagCanceledLongPress = 0x100
	// KeyEventFlagTracking as declared in input.h:263
	KeyEventFlagTracking = 0x200
	// KeyEventFlagFallback as declared in input.h:273
	KeyEventFlagFallback = 0x400
)

const (
	// MotionEventActionMask as declared in input.h:285
	MotionEventActionMask = 0xff
	// MotionEventActionPointerIndexMask as declared in input.h:293
	MotionEventActionPointerIndexMask = 0xff00
	// MotionEventActionDown as declared in input.h:296
	MotionEventActionDown = 0
	// MotionEventActionUp as declared in input.h:302
	MotionEventActionUp = 1
	// MotionEventActionMove as declared in input.h:309
	MotionEventActionMove = 2
	// MotionEventActionCancel as declared in input.h:316
	MotionEventActionCancel = 3
	// MotionEventActionOutside as declared in input.h:322
	MotionEventActionOutside = 4
	// MotionEventActionPointerDown as declared in input.h:328
	MotionEventActionPointerDown = 5
	// MotionEventActionPointerUp as declared in input.h:334
	MotionEventActionPointerUp = 6
	// MotionEventActionHoverMove as declared in input.h:341
	MotionEventActionHoverMove = 7
	// MotionEventActionScroll as declared in input.h:351
	MotionEventActionScroll = 8
	// MotionEventActionHoverEnter as declared in input.h:354
	MotionEventActionHoverEnter = 9
	// MotionEventActionHoverExit as declared in input.h:357
	MotionEventActionHoverExit = 10
	// MotionEventActionButtonPress as declared in input.h:360
	MotionEventActionButtonPress = 11
	// MotionEventActionButtonRelease as declared in input.h:363
	MotionEventActionButtonRelease = 12
)

const (
	// MotionEventFlagWindowIsObscured as declared in input.h:380
	MotionEventFlagWindowIsObscured = 0x1
)

const (
	// MotionEventEdgeFlagNone as declared in input.h:388
	MotionEventEdgeFlagNone = iota
	// MotionEventEdgeFlagTop as declared in input.h:391
	MotionEventEdgeFlagTop = 0x01
	// MotionEventEdgeFlagBottom as declared in input.h:394
	MotionEventEdgeFlagBottom = 0x02
	// MotionEventEdgeFlagLeft as declared in input.h:397
	MotionEventEdgeFlagLeft = 0x04
	// MotionEventEdgeFlagRight as declared in input.h:400
	MotionEventEdgeFlagRight = 0x08
)

const (
	// MotionEventAxisX as declared in input.h:422
	MotionEventAxisX = iota
	// MotionEventAxisY as declared in input.h:437
	MotionEventAxisY = 1
	// MotionEventAxisPressure as declared in input.h:450
	MotionEventAxisPressure = 2
	// MotionEventAxisSize as declared in input.h:461
	MotionEventAxisSize = 3
	// MotionEventAxisTouchMajor as declared in input.h:472
	MotionEventAxisTouchMajor = 4
	// MotionEventAxisTouchMinor as declared in input.h:485
	MotionEventAxisTouchMinor = 5
	// MotionEventAxisToolMajor as declared in input.h:500
	MotionEventAxisToolMajor = 6
	// MotionEventAxisToolMinor as declared in input.h:515
	MotionEventAxisToolMinor = 7
	// MotionEventAxisOrientation as declared in input.h:533
	MotionEventAxisOrientation = 8
	// MotionEventAxisVscroll as declared in input.h:542
	MotionEventAxisVscroll = 9
	// MotionEventAxisHscroll as declared in input.h:551
	MotionEventAxisHscroll = 10
	// MotionEventAxisZ as declared in input.h:560
	MotionEventAxisZ = 11
	// MotionEventAxisRx as declared in input.h:567
	MotionEventAxisRx = 12
	// MotionEventAxisRy as declared in input.h:574
	MotionEventAxisRy = 13
	// MotionEventAxisRz as declared in input.h:583
	MotionEventAxisRz = 14
	// MotionEventAxisHatX as declared in input.h:590
	MotionEventAxisHatX = 15
	// MotionEventAxisHatY as declared in input.h:597
	MotionEventAxisHatY = 16
	// MotionEventAxisLtrigger as declared in input.h:604
	MotionEventAxisLtrigger = 17
	// MotionEventAxisRtrigger as declared in input.h:611
	MotionEventAxisRtrigger = 18
	// MotionEventAxisThrottle as declared in input.h:618
	MotionEventAxisThrottle = 19
	// MotionEventAxisRudder as declared in input.h:625
	MotionEventAxisRudder = 20
	// MotionEventAxisWheel as declared in input.h:632
	MotionEventAxisWheel = 21
	// MotionEventAxisGas as declared in input.h:640
	MotionEventAxisGas = 22
	// MotionEventAxisBrake as declared in input.h:647
	MotionEventAxisBrake = 23
	// MotionEventAxisDistance as declared in input.h:655
	MotionEventAxisDistance = 24
	// MotionEventAxisTilt as declared in input.h:664
	MotionEventAxisTilt = 25
	// MotionEventAxisScroll as declared in input.h:671
	MotionEventAxisScroll = 26
	// MotionEventAxisRelativeX as declared in input.h:680
	MotionEventAxisRelativeX = 27
	// MotionEventAxisRelativeY as declared in input.h:686
	MotionEventAxisRelativeY = 28
	// MotionEventAxisGeneric1 as declared in input.h:691
	MotionEventAxisGeneric1 = 32
	// MotionEventAxisGeneric2 as declared in input.h:696
	MotionEventAxisGeneric2 = 33
	// MotionEventAxisGeneric3 as declared in input.h:701
	MotionEventAxisGeneric3 = 34
	// MotionEventAxisGeneric4 as declared in input.h:706
	MotionEventAxisGeneric4 = 35
	// MotionEventAxisGeneric5 as declared in input.h:711
	MotionEventAxisGeneric5 = 36
	// MotionEventAxisGeneric6 as declared in input.h:716
	MotionEventAxisGeneric6 = 37
	// MotionEventAxisGeneric7 as declared in input.h:721
	MotionEventAxisGeneric7 = 38
	// MotionEventAxisGeneric8 as declared in input.h:726
	MotionEventAxisGeneric8 = 39
	// MotionEventAxisGeneric9 as declared in input.h:731
	MotionEventAxisGeneric9 = 40
	// MotionEventAxisGeneric10 as declared in input.h:736
	MotionEventAxisGeneric10 = 41
	// MotionEventAxisGeneric11 as declared in input.h:741
	MotionEventAxisGeneric11 = 42
	// MotionEventAxisGeneric12 as declared in input.h:746
	MotionEventAxisGeneric12 = 43
	// MotionEventAxisGeneric13 as declared in input.h:751
	MotionEventAxisGeneric13 = 44
	// MotionEventAxisGeneric14 as declared in input.h:756
	MotionEventAxisGeneric14 = 45
	// MotionEventAxisGeneric15 as declared in input.h:761
	MotionEventAxisGeneric15 = 46
	// MotionEventAxisGeneric16 as declared in input.h:766
	MotionEventAxisGeneric16 = 47
)

const (
	// MotionEventButtonPrimary as declared in input.h:778
	MotionEventButtonPrimary = 1 << 0
	// MotionEventButtonSecondary as declared in input.h:780
	MotionEventButtonSecondary = 1 << 1
	// MotionEventButtonTertiary as declared in input.h:782
	MotionEventButtonTertiary = 1 << 2
	// MotionEventButtonBack as declared in input.h:784
	MotionEventButtonBack = 1 << 3
	// MotionEventButtonForward as declared in input.h:786
	MotionEventButtonForward = 1 << 4
	// MotionEventButtonStylusPrimary as declared in input.h:787
	MotionEventButtonStylusPrimary = 1 << 5
	// MotionEventButtonStylusSecondary as declared in input.h:788
	MotionEventButtonStylusSecondary = 1 << 6
)

const (
	// MotionEventToolTypeUnknown as declared in input.h:797
	MotionEventToolTypeUnknown = iota
	// MotionEventToolTypeFinger as declared in input.h:799
	MotionEventToolTypeFinger = 1
	// MotionEventToolTypeStylus as declared in input.h:801
	MotionEventToolTypeStylus = 2
	// MotionEventToolTypeMouse as declared in input.h:803
	MotionEventToolTypeMouse = 3
	// MotionEventToolTypeEraser as declared in input.h:805
	MotionEventToolTypeEraser = 4
	// MotionEventToolTypePalm as declared in input.h:807
	MotionEventToolTypePalm = 5
)

const (
	// MotionEventClassificationNone as declared in input.h:819
	MotionEventClassificationNone = iota
	// MotionEventClassificationAmbiguousGesture as declared in input.h:829
	MotionEventClassificationAmbiguousGesture = 1
	// MotionEventClassificationDeepPress as declared in input.h:836
	MotionEventClassificationDeepPress = 2
)

const (
	// InputSourceClassMask as declared in input.h:847
	InputSourceClassMask = 0x000000ff
	// InputSourceClassNone as declared in input.h:850
	InputSourceClassNone = 0x00000000
	// InputSourceClassButton as declared in input.h:852
	InputSourceClassButton = 0x00000001
	// InputSourceClassPointer as declared in input.h:854
	InputSourceClassPointer = 0x00000002
	// InputSourceClassNavigation as declared in input.h:856
	InputSourceClassNavigation = 0x00000004
	// InputSourceClassPosition as declared in input.h:858
	InputSourceClassPosition = 0x00000008
	// InputSourceClassJoystick as declared in input.h:860
	InputSourceClassJoystick = 0x00000010
)

const (
	// InputSourceUnknown as declared in input.h:868
	InputSourceUnknown = 0x00000000
	// InputSourceKeyboard as declared in input.h:871
	InputSourceKeyboard = 0x00000100 | InputSourceClassButton
	// InputSourceDpad as declared in input.h:873
	InputSourceDpad = 0x00000200 | InputSourceClassButton
	// InputSourceGamepad as declared in input.h:875
	InputSourceGamepad = 0x00000400 | InputSourceClassButton
	// InputSourceTouchscreen as declared in input.h:877
	InputSourceTouchscreen = 0x00001000 | InputSourceClassPointer
	// InputSourceMouse as declared in input.h:879
	InputSourceMouse = 0x00002000 | InputSourceClassPointer
	// InputSourceStylus as declared in input.h:881
	InputSourceStylus = 0x00004000 | InputSourceClassPointer
	// InputSourceBluetoothStylus as declared in input.h:883
	InputSourceBluetoothStylus = 0x00008000 | InputSourceStylus
	// InputSourceTrackball as declared in input.h:885
	InputSourceTrackball = 0x00010000 | InputSourceClassNavigation
	// InputSourceMouseRelative as declared in input.h:887
	InputSourceMouseRelative = 0x00020000 | InputSourceClassNavigation
	// InputSourceTouchpad as declared in input.h:889
	InputSourceTouchpad = 0x00100000 | InputSourceClassPosition
	// InputSourceTouchNavigation as declared in input.h:891
	InputSourceTouchNavigation = 0x00200000 | InputSourceClassNone
	// InputSourceJoystick as declared in input.h:893
	InputSourceJoystick = 0x01000000 | InputSourceClassJoystick
	// InputSourceHdmi as declared in input.h:895
	InputSourceHdmi = 0x02000000 | InputSourceClassButton
	// InputSourceSensor as declared in input.h:897
	InputSourceSensor = 0x04000000 | InputSourceClassNone
	// InputSourceRotaryEncoder as declared in input.h:899
	InputSourceRotaryEncoder = 0x00400000 | InputSourceClassNone
	// InputSourceAny as declared in input.h:902
	InputSourceAny = 0xffffff00
)

const (
	// InputKeyboardTypeNone as declared in input.h:913
	InputKeyboardTypeNone = iota
	// InputKeyboardTypeNonAlphabetic as declared in input.h:915
	InputKeyboardTypeNonAlphabetic = 1
	// InputKeyboardTypeAlphabetic as declared in input.h:917
	InputKeyboardTypeAlphabetic = 2
)

const (
	// InputMotionRangeX as declared in input.h:932
	InputMotionRangeX = MotionEventAxisX
	// InputMotionRangeY as declared in input.h:934
	InputMotionRangeY = MotionEventAxisY
	// InputMotionRangePressure as declared in input.h:936
	InputMotionRangePressure = MotionEventAxisPressure
	// InputMotionRangeSize as declared in input.h:938
	InputMotionRangeSize = MotionEventAxisSize
	// InputMotionRangeTouchMajor as declared in input.h:940
	InputMotionRangeTouchMajor = MotionEventAxisTouchMajor
	// InputMotionRangeTouchMinor as declared in input.h:942
	InputMotionRangeTouchMinor = MotionEventAxisTouchMinor
	// InputMotionRangeToolMajor as declared in input.h:944
	InputMotionRangeToolMajor = MotionEventAxisToolMajor
	// InputMotionRangeToolMinor as declared in input.h:946
	InputMotionRangeToolMinor = MotionEventAxisToolMinor
	// InputMotionRangeOrientation as declared in input.h:948
	InputMotionRangeOrientation = MotionEventAxisOrientation
)

const (
	// KeycodeUnknown as declared in keycodes.h:56
	KeycodeUnknown = iota
	// KeycodeSoftLeft as declared in keycodes.h:61
	KeycodeSoftLeft = 1
	// KeycodeSoftRight as declared in keycodes.h:66
	KeycodeSoftRight = 2
	// KeycodeHome as declared in keycodes.h:69
	KeycodeHome = 3
	// KeycodeBack as declared in keycodes.h:71
	KeycodeBack = 4
	// KeycodeCall as declared in keycodes.h:73
	KeycodeCall = 5
	// KeycodeEndcall as declared in keycodes.h:75
	KeycodeEndcall = 6
	// Keycode0 as declared in keycodes.h:77
	Keycode0 = 7
	// Keycode1 as declared in keycodes.h:79
	Keycode1 = 8
	// Keycode2 as declared in keycodes.h:81
	Keycode2 = 9
	// Keycode3 as declared in keycodes.h:83
	Keycode3 = 10
	// Keycode4 as declared in keycodes.h:85
	Keycode4 = 11
	// Keycode5 as declared in keycodes.h:87
	Keycode5 = 12
	// Keycode6 as declared in keycodes.h:89
	Keycode6 = 13
	// Keycode7 as declared in keycodes.h:91
	Keycode7 = 14
	// Keycode8 as declared in keycodes.h:93
	Keycode8 = 15
	// Keycode9 as declared in keycodes.h:95
	Keycode9 = 16
	// KeycodeStar as declared in keycodes.h:97
	KeycodeStar = 17
	// KeycodePound as declared in keycodes.h:99
	KeycodePound = 18
	// KeycodeDpadUp as declared in keycodes.h:102
	KeycodeDpadUp = 19
	// KeycodeDpadDown as declared in keycodes.h:105
	KeycodeDpadDown = 20
	// KeycodeDpadLeft as declared in keycodes.h:108
	KeycodeDpadLeft = 21
	// KeycodeDpadRight as declared in keycodes.h:111
	KeycodeDpadRight = 22
	// KeycodeDpadCenter as declared in keycodes.h:114
	KeycodeDpadCenter = 23
	// KeycodeVolumeUp as declared in keycodes.h:117
	KeycodeVolumeUp = 24
	// KeycodeVolumeDown as declared in keycodes.h:120
	KeycodeVolumeDown = 25
	// KeycodePower as declared in keycodes.h:122
	KeycodePower = 26
	// KeycodeCamera as declared in keycodes.h:125
	KeycodeCamera = 27
	// KeycodeClear as declared in keycodes.h:127
	KeycodeClear = 28
	// KeycodeA as declared in keycodes.h:129
	KeycodeA = 29
	// KeycodeB as declared in keycodes.h:131
	KeycodeB = 30
	// KeycodeC as declared in keycodes.h:133
	KeycodeC = 31
	// KeycodeD as declared in keycodes.h:135
	KeycodeD = 32
	// KeycodeE as declared in keycodes.h:137
	KeycodeE = 33
	// KeycodeF as declared in keycodes.h:139
	KeycodeF = 34
	// KeycodeG as declared in keycodes.h:141
	KeycodeG = 35
	// KeycodeH as declared in keycodes.h:143
	KeycodeH = 36
	// KeycodeI as declared in keycodes.h:145
	KeycodeI = 37
	// KeycodeJ as declared in keycodes.h:147
	KeycodeJ = 38
	// KeycodeK as declared in keycodes.h:149
	KeycodeK = 39
	// KeycodeL as declared in keycodes.h:151
	KeycodeL = 40
	// KeycodeM as declared in keycodes.h:153
	KeycodeM = 41
	// KeycodeN as declared in keycodes.h:155
	KeycodeN = 42
	// KeycodeO as declared in keycodes.h:157
	KeycodeO = 43
	// KeycodeP as declared in keycodes.h:159
	KeycodeP = 44
	// KeycodeQ as declared in keycodes.h:161
	KeycodeQ = 45
	// KeycodeR as declared in keycodes.h:163
	KeycodeR = 46
	// KeycodeS as declared in keycodes.h:165
	KeycodeS = 47
	// KeycodeT as declared in keycodes.h:167
	KeycodeT = 48
	// KeycodeU as declared in keycodes.h:169
	KeycodeU = 49
	// KeycodeV as declared in keycodes.h:171
	KeycodeV = 50
	// KeycodeW as declared in keycodes.h:173
	KeycodeW = 51
	// KeycodeX as declared in keycodes.h:175
	KeycodeX = 52
	// KeycodeY as declared in keycodes.h:177
	KeycodeY = 53
	// KeycodeZ as declared in keycodes.h:179
	KeycodeZ = 54
	// KeycodeComma as declared in keycodes.h:181
	KeycodeComma = 55
	// KeycodePeriod as declared in keycodes.h:183
	KeycodePeriod = 56
	// KeycodeAltLeft as declared in keycodes.h:185
	KeycodeAltLeft = 57
	// KeycodeAltRight as declared in keycodes.h:187
	KeycodeAltRight = 58
	// KeycodeShiftLeft as declared in keycodes.h:189
	KeycodeShiftLeft = 59
	// KeycodeShiftRight as declared in keycodes.h:191
	KeycodeShiftRight = 60
	// KeycodeTab as declared in keycodes.h:193
	KeycodeTab = 61
	// KeycodeSpace as declared in keycodes.h:195
	KeycodeSpace = 62
	// KeycodeSym as declared in keycodes.h:198
	KeycodeSym = 63
	// KeycodeExplorer as declared in keycodes.h:201
	KeycodeExplorer = 64
	// KeycodeEnvelope as declared in keycodes.h:204
	KeycodeEnvelope = 65
	// KeycodeEnter as declared in keycodes.h:206
	KeycodeEnter = 66
	// KeycodeDel as declared in keycodes.h:209
	KeycodeDel = 67
	// KeycodeGrave as declared in keycodes.h:211
	KeycodeGrave = 68
	// KeycodeMinus as declared in keycodes.h:213
	KeycodeMinus = 69
	// KeycodeEquals as declared in keycodes.h:215
	KeycodeEquals = 70
	// KeycodeLeftBracket as declared in keycodes.h:217
	KeycodeLeftBracket = 71
	// KeycodeRightBracket as declared in keycodes.h:219
	KeycodeRightBracket = 72
	// KeycodeBackslash as declared in keycodes.h:221
	KeycodeBackslash = 73
	// KeycodeSemicolon as declared in keycodes.h:223
	KeycodeSemicolon = 74
	// KeycodeApostrophe as declared in keycodes.h:225
	KeycodeApostrophe = 75
	// KeycodeSlash as declared in keycodes.h:227
	KeycodeSlash = 76
	// KeycodeAt as declared in keycodes.h:229
	KeycodeAt = 77
	// KeycodeNum as declared in keycodes.h:233
	KeycodeNum = 78
	// KeycodeHeadsethook as declared in keycodes.h:236
	KeycodeHeadsethook = 79
	// KeycodeFocus as declared in keycodes.h:239
	KeycodeFocus = 80
	// KeycodePlus as declared in keycodes.h:241
	KeycodePlus = 81
	// KeycodeMenu as declared in keycodes.h:243
	KeycodeMenu = 82
	// KeycodeNotification as declared in keycodes.h:245
	KeycodeNotification = 83
	// KeycodeSearch as declared in keycodes.h:247
	KeycodeSearch = 84
	// KeycodeMediaPlayPause as declared in keycodes.h:249
	KeycodeMediaPlayPause = 85
	// KeycodeMediaStop as declared in keycodes.h:251
	KeycodeMediaStop = 86
	// KeycodeMediaNext as declared in keycodes.h:253
	KeycodeMediaNext = 87
	// KeycodeMediaPrevious as declared in keycodes.h:255
	KeycodeMediaPrevious = 88
	// KeycodeMediaRewind as declared in keycodes.h:257
	KeycodeMediaRewind = 89
	// KeycodeMediaFastForward as declared in keycodes.h:259
	KeycodeMediaFastForward = 90
	// KeycodeMute as declared in keycodes.h:262
	KeycodeMute = 91
	// KeycodePageUp as declared in keycodes.h:264
	KeycodePageUp = 92
	// KeycodePageDown as declared in keycodes.h:266
	KeycodePageDown = 93
	// KeycodePictsymbols as declared in keycodes.h:269
	KeycodePictsymbols = 94
	// KeycodeSwitchCharset as declared in keycodes.h:272
	KeycodeSwitchCharset = 95
	// KeycodeButtonA as declared in keycodes.h:276
	KeycodeButtonA = 96
	// KeycodeButtonB as declared in keycodes.h:280
	KeycodeButtonB = 97
	// KeycodeButtonC as declared in keycodes.h:284
	KeycodeButtonC = 98
	// KeycodeButtonX as declared in keycodes.h:288
	KeycodeButtonX = 99
	// KeycodeButtonY as declared in keycodes.h:292
	KeycodeButtonY = 100
	// KeycodeButtonZ as declared in keycodes.h:296
	KeycodeButtonZ = 101
	// KeycodeButtonL1 as declared in keycodes.h:300
	KeycodeButtonL1 = 102
	// KeycodeButtonR1 as declared in keycodes.h:304
	KeycodeButtonR1 = 103
	// KeycodeButtonL2 as declared in keycodes.h:308
	KeycodeButtonL2 = 104
	// KeycodeButtonR2 as declared in keycodes.h:312
	KeycodeButtonR2 = 105
	// KeycodeButtonThumbl as declared in keycodes.h:316
	KeycodeButtonThumbl = 106
	// KeycodeButtonThumbr as declared in keycodes.h:320
	KeycodeButtonThumbr = 107
	// KeycodeButtonStart as declared in keycodes.h:323
	KeycodeButtonStart = 108
	// KeycodeButtonSelect as declared in keycodes.h:326
	KeycodeButtonSelect = 109
	// KeycodeButtonMode as declared in keycodes.h:329
	KeycodeButtonMode = 110
	// KeycodeEscape as declared in keycodes.h:331
	KeycodeEscape = 111
	// KeycodeForwardDel as declared in keycodes.h:334
	KeycodeForwardDel = 112
	// KeycodeCtrlLeft as declared in keycodes.h:336
	KeycodeCtrlLeft = 113
	// KeycodeCtrlRight as declared in keycodes.h:338
	KeycodeCtrlRight = 114
	// KeycodeCapsLock as declared in keycodes.h:340
	KeycodeCapsLock = 115
	// KeycodeScrollLock as declared in keycodes.h:342
	KeycodeScrollLock = 116
	// KeycodeMetaLeft as declared in keycodes.h:344
	KeycodeMetaLeft = 117
	// KeycodeMetaRight as declared in keycodes.h:346
	KeycodeMetaRight = 118
	// KeycodeFunction as declared in keycodes.h:348
	KeycodeFunction = 119
	// KeycodeSysrq as declared in keycodes.h:350
	KeycodeSysrq = 120
	// KeycodeBreak as declared in keycodes.h:352
	KeycodeBreak = 121
	// KeycodeMoveHome as declared in keycodes.h:356
	KeycodeMoveHome = 122
	// KeycodeMoveEnd as declared in keycodes.h:360
	KeycodeMoveEnd = 123
	// KeycodeInsert as declared in keycodes.h:363
	KeycodeInsert = 124
	// KeycodeForward as declared in keycodes.h:366
	KeycodeForward = 125
	// KeycodeMediaPlay as declared in keycodes.h:368
	KeycodeMediaPlay = 126
	// KeycodeMediaPause as declared in keycodes.h:370
	KeycodeMediaPause = 127
	// KeycodeMediaClose as declared in keycodes.h:373
	KeycodeMediaClose = 128
	// KeycodeMediaEject as declared in keycodes.h:376
	KeycodeMediaEject = 129
	// KeycodeMediaRecord as declared in keycodes.h:378
	KeycodeMediaRecord = 130
	// KeycodeF1 as declared in keycodes.h:380
	KeycodeF1 = 131
	// KeycodeF2 as declared in keycodes.h:382
	KeycodeF2 = 132
	// KeycodeF3 as declared in keycodes.h:384
	KeycodeF3 = 133
	// KeycodeF4 as declared in keycodes.h:386
	KeycodeF4 = 134
	// KeycodeF5 as declared in keycodes.h:388
	KeycodeF5 = 135
	// KeycodeF6 as declared in keycodes.h:390
	KeycodeF6 = 136
	// KeycodeF7 as declared in keycodes.h:392
	KeycodeF7 = 137
	// KeycodeF8 as declared in keycodes.h:394
	KeycodeF8 = 138
	// KeycodeF9 as declared in keycodes.h:396
	KeycodeF9 = 139
	// KeycodeF10 as declared in keycodes.h:398
	KeycodeF10 = 140
	// KeycodeF11 as declared in keycodes.h:400
	KeycodeF11 = 141
	// KeycodeF12 as declared in keycodes.h:402
	KeycodeF12 = 142
	// KeycodeNumLock as declared in keycodes.h:406
	KeycodeNumLock = 143
	// KeycodeNumpad0 as declared in keycodes.h:408
	KeycodeNumpad0 = 144
	// KeycodeNumpad1 as declared in keycodes.h:410
	KeycodeNumpad1 = 145
	// KeycodeNumpad2 as declared in keycodes.h:412
	KeycodeNumpad2 = 146
	// KeycodeNumpad3 as declared in keycodes.h:414
	KeycodeNumpad3 = 147
	// KeycodeNumpad4 as declared in keycodes.h:416
	KeycodeNumpad4 = 148
	// KeycodeNumpad5 as declared in keycodes.h:418
	KeycodeNumpad5 = 149
	// KeycodeNumpad6 as declared in keycodes.h:420
	KeycodeNumpad6 = 150
	// KeycodeNumpad7 as declared in keycodes.h:422
	KeycodeNumpad7 = 151
	// KeycodeNumpad8 as declared in keycodes.h:424
	KeycodeNumpad8 = 152
	// KeycodeNumpad9 as declared in keycodes.h:426
	KeycodeNumpad9 = 153
	// KeycodeNumpadDivide as declared in keycodes.h:428
	KeycodeNumpadDivide = 154
	// KeycodeNumpadMultiply as declared in keycodes.h:430
	KeycodeNumpadMultiply = 155
	// KeycodeNumpadSubtract as declared in keycodes.h:432
	KeycodeNumpadSubtract = 156
	// KeycodeNumpadAdd as declared in keycodes.h:434
	KeycodeNumpadAdd = 157
	// KeycodeNumpadDot as declared in keycodes.h:436
	KeycodeNumpadDot = 158
	// KeycodeNumpadComma as declared in keycodes.h:438
	KeycodeNumpadComma = 159
	// KeycodeNumpadEnter as declared in keycodes.h:440
	KeycodeNumpadEnter = 160
	// KeycodeNumpadEquals as declared in keycodes.h:442
	KeycodeNumpadEquals = 161
	// KeycodeNumpadLeftParen as declared in keycodes.h:444
	KeycodeNumpadLeftParen = 162
	// KeycodeNumpadRightParen as declared in keycodes.h:446
	KeycodeNumpadRightParen = 163
	// KeycodeVolumeMute as declared in keycodes.h:451
	KeycodeVolumeMute = 164
	// KeycodeInfo as declared in keycodes.h:455
	KeycodeInfo = 165
	// KeycodeChannelUp as declared in keycodes.h:458
	KeycodeChannelUp = 166
	// KeycodeChannelDown as declared in keycodes.h:461
	KeycodeChannelDown = 167
	// KeycodeZoomIn as declared in keycodes.h:463
	KeycodeZoomIn = 168
	// KeycodeZoomOut as declared in keycodes.h:465
	KeycodeZoomOut = 169
	// KeycodeTv as declared in keycodes.h:468
	KeycodeTv = 170
	// KeycodeWindow as declared in keycodes.h:471
	KeycodeWindow = 171
	// KeycodeGuide as declared in keycodes.h:474
	KeycodeGuide = 172
	// KeycodeDvr as declared in keycodes.h:477
	KeycodeDvr = 173
	// KeycodeBookmark as declared in keycodes.h:480
	KeycodeBookmark = 174
	// KeycodeCaptions as declared in keycodes.h:483
	KeycodeCaptions = 175
	// KeycodeSettings as declared in keycodes.h:486
	KeycodeSettings = 176
	// KeycodeTvPower as declared in keycodes.h:489
	KeycodeTvPower = 177
	// KeycodeTvInput as declared in keycodes.h:492
	KeycodeTvInput = 178
	// KeycodeStbPower as declared in keycodes.h:495
	KeycodeStbPower = 179
	// KeycodeStbInput as declared in keycodes.h:498
	KeycodeStbInput = 180
	// KeycodeAvrPower as declared in keycodes.h:501
	KeycodeAvrPower = 181
	// KeycodeAvrInput as declared in keycodes.h:504
	KeycodeAvrInput = 182
	// KeycodeProgRed as declared in keycodes.h:507
	KeycodeProgRed = 183
	// KeycodeProgGreen as declared in keycodes.h:510
	KeycodeProgGreen = 184
	// KeycodeProgYellow as declared in keycodes.h:513
	KeycodeProgYellow = 185
	// KeycodeProgBlue as declared in keycodes.h:516
	KeycodeProgBlue = 186
	// KeycodeAppSwitch as declared in keycodes.h:519
	KeycodeAppSwitch = 187
	// KeycodeButton1 as declared in keycodes.h:521
	KeycodeButton1 = 188
	// KeycodeButton2 as declared in keycodes.h:523
	KeycodeButton2 = 189
	// KeycodeButton3 as declared in keycodes.h:525
	KeycodeButton3 = 190
	// KeycodeButton4 as declared in keycodes.h:527
	KeycodeButton4 = 191
	// KeycodeButton5 as declared in keycodes.h:529
	KeycodeButton5 = 192
	// KeycodeButton6 as declared in keycodes.h:531
	KeycodeButton6 = 193
	// KeycodeButton7 as declared in keycodes.h:533
	KeycodeButton7 = 194
	// KeycodeButton8 as declared in keycodes.h:535
	KeycodeButton8 = 195
	// KeycodeButton9 as declared in keycodes.h:537
	KeycodeButton9 = 196
	// KeycodeButton10 as declared in keycodes.h:539
	KeycodeButton10 = 197
	// KeycodeButton11 as declared in keycodes.h:541
	KeycodeButton11 = 198
	// KeycodeButton12 as declared in keycodes.h:543
	KeycodeButton12 = 199
	// KeycodeButton13 as declared in keycodes.h:545
	KeycodeButton13 = 200
	// KeycodeButton14 as declared in keycodes.h:547
	KeycodeButton14 = 201
	// KeycodeButton15 as declared in keycodes.h:549
	KeycodeButton15 = 202
	// KeycodeButton16 as declared in keycodes.h:551
	KeycodeButton16 = 203
	// KeycodeLanguageSwitch as declared in keycodes.h:556
	KeycodeLanguageSwitch = 204
	// KeycodeMannerMode as declared in keycodes.h:561
	KeycodeMannerMode = 205
	// Keycode3dMode as declared in keycodes.h:564
	Keycode3dMode = 206
	// KeycodeContacts as declared in keycodes.h:567
	KeycodeContacts = 207
	// KeycodeCalendar as declared in keycodes.h:570
	KeycodeCalendar = 208
	// KeycodeMusic as declared in keycodes.h:573
	KeycodeMusic = 209
	// KeycodeCalculator as declared in keycodes.h:576
	KeycodeCalculator = 210
	// KeycodeZenkakuHankaku as declared in keycodes.h:578
	KeycodeZenkakuHankaku = 211
	// KeycodeEisu as declared in keycodes.h:580
	KeycodeEisu = 212
	// KeycodeMuhenkan as declared in keycodes.h:582
	KeycodeMuhenkan = 213
	// KeycodeHenkan as declared in keycodes.h:584
	KeycodeHenkan = 214
	// KeycodeKatakanaHiragana as declared in keycodes.h:586
	KeycodeKatakanaHiragana = 215
	// KeycodeYen as declared in keycodes.h:588
	KeycodeYen = 216
	// KeycodeRo as declared in keycodes.h:590
	KeycodeRo = 217
	// KeycodeKana as declared in keycodes.h:592
	KeycodeKana = 218
	// KeycodeAssist as declared in keycodes.h:595
	KeycodeAssist = 219
	// KeycodeBrightnessDown as declared in keycodes.h:598
	KeycodeBrightnessDown = 220
	// KeycodeBrightnessUp as declared in keycodes.h:601
	KeycodeBrightnessUp = 221
	// KeycodeMediaAudioTrack as declared in keycodes.h:604
	KeycodeMediaAudioTrack = 222
	// KeycodeSleep as declared in keycodes.h:608
	KeycodeSleep = 223
	// KeycodeWakeup as declared in keycodes.h:612
	KeycodeWakeup = 224
	// KeycodePairing as declared in keycodes.h:617
	KeycodePairing = 225
	// KeycodeMediaTopMenu as declared in keycodes.h:620
	KeycodeMediaTopMenu = 226
	// Keycode11 as declared in keycodes.h:622
	Keycode11 = 227
	// Keycode12 as declared in keycodes.h:624
	Keycode12 = 228
	// KeycodeLastChannel as declared in keycodes.h:627
	KeycodeLastChannel = 229
	// KeycodeTvDataService as declared in keycodes.h:630
	KeycodeTvDataService = 230
	// KeycodeVoiceAssist as declared in keycodes.h:633
	KeycodeVoiceAssist = 231
	// KeycodeTvRadioService as declared in keycodes.h:636
	KeycodeTvRadioService = 232
	// KeycodeTvTeletext as declared in keycodes.h:639
	KeycodeTvTeletext = 233
	// KeycodeTvNumberEntry as declared in keycodes.h:644
	KeycodeTvNumberEntry = 234
	// KeycodeTvTerrestrialAnalog as declared in keycodes.h:647
	KeycodeTvTerrestrialAnalog = 235
	// KeycodeTvTerrestrialDigital as declared in keycodes.h:650
	KeycodeTvTerrestrialDigital = 236
	// KeycodeTvSatellite as declared in keycodes.h:653
	KeycodeTvSatellite = 237
	// KeycodeTvSatelliteBs as declared in keycodes.h:656
	KeycodeTvSatelliteBs = 238
	// KeycodeTvSatelliteCs as declared in keycodes.h:659
	KeycodeTvSatelliteCs = 239
	// KeycodeTvSatelliteService as declared in keycodes.h:662
	KeycodeTvSatelliteService = 240
	// KeycodeTvNetwork as declared in keycodes.h:665
	KeycodeTvNetwork = 241
	// KeycodeTvAntennaCable as declared in keycodes.h:668
	KeycodeTvAntennaCable = 242
	// KeycodeTvInputHdmi1 as declared in keycodes.h:671
	KeycodeTvInputHdmi1 = 243
	// KeycodeTvInputHdmi2 as declared in keycodes.h:674
	KeycodeTvInputHdmi2 = 244
	// KeycodeTvInputHdmi3 as declared in keycodes.h:677
	KeycodeTvInputHdmi3 = 245
	// KeycodeTvInputHdmi4 as declared in keycodes.h:680
	KeycodeTvInputHdmi4 = 246
	// KeycodeTvInputComposite1 as declared in keycodes.h:683
	KeycodeTvInputComposite1 = 247
	// KeycodeTvInputComposite2 as declared in keycodes.h:686
	KeycodeTvInputComposite2 = 248
	// KeycodeTvInputComponent1 as declared in keycodes.h:689
	KeycodeTvInputComponent1 = 249
	// KeycodeTvInputComponent2 as declared in keycodes.h:692
	KeycodeTvInputComponent2 = 250
	// KeycodeTvInputVga1 as declared in keycodes.h:695
	KeycodeTvInputVga1 = 251
	// KeycodeTvAudioDescription as declared in keycodes.h:698
	KeycodeTvAudioDescription = 252
	// KeycodeTvAudioDescriptionMixUp as declared in keycodes.h:701
	KeycodeTvAudioDescriptionMixUp = 253
	// KeycodeTvAudioDescriptionMixDown as declared in keycodes.h:704
	KeycodeTvAudioDescriptionMixDown = 254
	// KeycodeTvZoomMode as declared in keycodes.h:707
	KeycodeTvZoomMode = 255
	// KeycodeTvContentsMenu as declared in keycodes.h:711
	KeycodeTvContentsMenu = 256
	// KeycodeTvMediaContextMenu as declared in keycodes.h:715
	KeycodeTvMediaContextMenu = 257
	// KeycodeTvTimerProgramming as declared in keycodes.h:719
	KeycodeTvTimerProgramming = 258
	// KeycodeHelp as declared in keycodes.h:721
	KeycodeHelp = 259
	// KeycodeNavigatePrevious as declared in keycodes.h:722
	KeycodeNavigatePrevious = 260
	// KeycodeNavigateNext as declared in keycodes.h:723
	KeycodeNavigateNext = 261
	// KeycodeNavigateIn as declared in keycodes.h:724
	KeycodeNavigateIn = 262
	// KeycodeNavigateOut as declared in keycodes.h:725
	KeycodeNavigateOut = 263
	// KeycodeStemPrimary as declared in keycodes.h:728
	KeycodeStemPrimary = 264
	// KeycodeStem1 as declared in keycodes.h:730
	KeycodeStem1 = 265
	// KeycodeStem2 as declared in keycodes.h:732
	KeycodeStem2 = 266
	// KeycodeStem3 as declared in keycodes.h:734
	KeycodeStem3 = 267
	// KeycodeDpadUpLeft as declared in keycodes.h:736
	KeycodeDpadUpLeft = 268
	// KeycodeDpadDownLeft as declared in keycodes.h:738
	KeycodeDpadDownLeft = 269
	// KeycodeDpadUpRight as declared in keycodes.h:740
	KeycodeDpadUpRight = 270
	// KeycodeDpadDownRight as declared in keycodes.h:742
	KeycodeDpadDownRight = 271
	// KeycodeMediaSkipForward as declared in keycodes.h:744
	KeycodeMediaSkipForward = 272
	// KeycodeMediaSkipBackward as declared in keycodes.h:746
	KeycodeMediaSkipBackward = 273
	// KeycodeMediaStepForward as declared in keycodes.h:749
	KeycodeMediaStepForward = 274
	// KeycodeMediaStepBackward as declared in keycodes.h:752
	KeycodeMediaStepBackward = 275
	// KeycodeSoftSleep as declared in keycodes.h:754
	KeycodeSoftSleep = 276
	// KeycodeCut as declared in keycodes.h:756
	KeycodeCut = 277
	// KeycodeCopy as declared in keycodes.h:758
	KeycodeCopy = 278
	// KeycodePaste as declared in keycodes.h:760
	KeycodePaste = 279
	// KeycodeSystemNavigationUp as declared in keycodes.h:762
	KeycodeSystemNavigationUp = 280
	// KeycodeSystemNavigationDown as declared in keycodes.h:764
	KeycodeSystemNavigationDown = 281
	// KeycodeSystemNavigationLeft as declared in keycodes.h:766
	KeycodeSystemNavigationLeft = 282
	// KeycodeSystemNavigationRight as declared in keycodes.h:768
	KeycodeSystemNavigationRight = 283
	// KeycodeAllApps as declared in keycodes.h:770
	KeycodeAllApps = 284
	// KeycodeRefresh as declared in keycodes.h:772
	KeycodeRefresh = 285
	// KeycodeThumbsUp as declared in keycodes.h:774
	KeycodeThumbsUp = 286
	// KeycodeThumbsDown as declared in keycodes.h:776
	KeycodeThumbsDown = 287
	// KeycodeProfileSwitch as declared in keycodes.h:779
	KeycodeProfileSwitch = 288
	// KeycodeVideoApp1 as declared in keycodes.h:781
	KeycodeVideoApp1 = 289
	// KeycodeVideoApp2 as declared in keycodes.h:783
	KeycodeVideoApp2 = 290
	// KeycodeVideoApp3 as declared in keycodes.h:785
	KeycodeVideoApp3 = 291
	// KeycodeVideoApp4 as declared in keycodes.h:787
	KeycodeVideoApp4 = 292
	// KeycodeVideoApp5 as declared in keycodes.h:789
	KeycodeVideoApp5 = 293
	// KeycodeVideoApp6 as declared in keycodes.h:791
	KeycodeVideoApp6 = 294
	// KeycodeVideoApp7 as declared in keycodes.h:793
	KeycodeVideoApp7 = 295
	// KeycodeVideoApp8 as declared in keycodes.h:795
	KeycodeVideoApp8 = 296
	// KeycodeFeaturedApp1 as declared in keycodes.h:797
	KeycodeFeaturedApp1 = 297
	// KeycodeFeaturedApp2 as declared in keycodes.h:799
	KeycodeFeaturedApp2 = 298
	// KeycodeFeaturedApp3 as declared in keycodes.h:801
	KeycodeFeaturedApp3 = 299
	// KeycodeFeaturedApp4 as declared in keycodes.h:803
	KeycodeFeaturedApp4 = 300
	// KeycodeDemoApp1 as declared in keycodes.h:805
	KeycodeDemoApp1 = 301
	// KeycodeDemoApp2 as declared in keycodes.h:807
	KeycodeDemoApp2 = 302
	// KeycodeDemoApp3 as declared in keycodes.h:809
	KeycodeDemoApp3 = 303
	// KeycodeDemoApp4 as declared in keycodes.h:811
	KeycodeDemoApp4 = 304
)

const (
	// LooperPrepareAllowNonCallbacks as declared in looper.h:64
	LooperPrepareAllowNonCallbacks = 1 << 0
)

const (
	// LooperPollWake as declared in looper.h:82
	LooperPollWake = -1
	// LooperPollCallback as declared in looper.h:88
	LooperPollCallback = -2
	// LooperPollTimeout as declared in looper.h:94
	LooperPollTimeout = -3
	// LooperPollError as declared in looper.h:100
	LooperPollError = -4
)

const (
	// LooperEventInput as declared in looper.h:124
	LooperEventInput = 1 << 0
	// LooperEventOutput as declared in looper.h:129
	LooperEventOutput = 1 << 1
	// LooperEventError as declared in looper.h:137
	LooperEventError = 1 << 2
	// LooperEventHangup as declared in looper.h:146
	LooperEventHangup = 1 << 3
	// LooperEventInvalid as declared in looper.h:155
	LooperEventInvalid = 1 << 4
)

const (
	// NativeactivityShowSoftInputImplicit as declared in native_activity.h:291
	NativeactivityShowSoftInputImplicit = 0x0001
	// NativeactivityShowSoftInputForced as declared in native_activity.h:298
	NativeactivityShowSoftInputForced = 0x0002
)

const (
	// NativeactivityHideSoftInputImplicitOnly as declared in native_activity.h:318
	NativeactivityHideSoftInputImplicitOnly = 0x0001
	// NativeactivityHideSoftInputNotAlways as declared in native_activity.h:323
	NativeactivityHideSoftInputNotAlways = 0x0002
)

const (
	// NativewindowTransformIdentity as declared in native_window.h:71
	NativewindowTransformIdentity = 0x00
	// NativewindowTransformMirrorHorizontal as declared in native_window.h:72
	NativewindowTransformMirrorHorizontal = 0x01
	// NativewindowTransformMirrorVertical as declared in native_window.h:73
	NativewindowTransformMirrorVertical = 0x02
	// NativewindowTransformRotate90 as declared in native_window.h:74
	NativewindowTransformRotate90 = 0x04
	// NativewindowTransformRotate180 as declared in native_window.h:76
	NativewindowTransformRotate180 = NativewindowTransformMirrorHorizontal | NativewindowTransformMirrorVertical
	// NativewindowTransformRotate270 as declared in native_window.h:78
	NativewindowTransformRotate270 = NativewindowTransformRotate180 | NativewindowTransformRotate90
)

const (
	// NativewindowFrameRateCompatibilityDefault as declared in native_window.h:239
	NativewindowFrameRateCompatibilityDefault = iota
	// NativewindowFrameRateCompatibilityFixedSource as declared in native_window.h:249
	NativewindowFrameRateCompatibilityFixedSource = 1
)

const (
	// NativewindowChangeFrameRateOnlyIfSeamless as declared in native_window.h:279
	NativewindowChangeFrameRateOnlyIfSeamless = iota
	// NativewindowChangeFrameRateAlways as declared in native_window.h:284
	NativewindowChangeFrameRateAlways = 1
)

const (
	// ObbinfoOverlay as declared in obb.h:42
	ObbinfoOverlay = 0x0001
)

const (
	// SensorTypeInvalid as declared in sensor.h:86
	SensorTypeInvalid = -1
	// SensorTypeAccelerometer as declared in sensor.h:94
	SensorTypeAccelerometer = 1
	// SensorTypeMagneticField as declared in sensor.h:102
	SensorTypeMagneticField = 2
	// SensorTypeGyroscope as declared in sensor.h:110
	SensorTypeGyroscope = 4
	// SensorTypeLight as declared in sensor.h:117
	SensorTypeLight = 5
	// SensorTypePressure as declared in sensor.h:123
	SensorTypePressure = 6
	// SensorTypeProximity as declared in sensor.h:134
	SensorTypeProximity = 8
	// SensorTypeGravity as declared in sensor.h:142
	SensorTypeGravity = 9
	// SensorTypeLinearAcceleration as declared in sensor.h:150
	SensorTypeLinearAcceleration = 10
	// SensorTypeRotationVector as declared in sensor.h:154
	SensorTypeRotationVector = 11
	// SensorTypeRelativeHumidity as declared in sensor.h:160
	SensorTypeRelativeHumidity = 12
	// SensorTypeAmbientTemperature as declared in sensor.h:166
	SensorTypeAmbientTemperature = 13
	// SensorTypeMagneticFieldUncalibrated as declared in sensor.h:170
	SensorTypeMagneticFieldUncalibrated = 14
	// SensorTypeGameRotationVector as declared in sensor.h:174
	SensorTypeGameRotationVector = 15
	// SensorTypeGyroscopeUncalibrated as declared in sensor.h:178
	SensorTypeGyroscopeUncalibrated = 16
	// SensorTypeSignificantMotion as declared in sensor.h:182
	SensorTypeSignificantMotion = 17
	// SensorTypeStepDetector as declared in sensor.h:186
	SensorTypeStepDetector = 18
	// SensorTypeStepCounter as declared in sensor.h:190
	SensorTypeStepCounter = 19
	// SensorTypeGeomagneticRotationVector as declared in sensor.h:194
	SensorTypeGeomagneticRotationVector = 20
	// SensorTypeHeartRate as declared in sensor.h:198
	SensorTypeHeartRate = 21
	// SensorTypePose6dof as declared in sensor.h:202
	SensorTypePose6dof = 28
	// SensorTypeStationaryDetect as declared in sensor.h:206
	SensorTypeStationaryDetect = 29
	// SensorTypeMotionDetect as declared in sensor.h:210
	SensorTypeMotionDetect = 30
	// SensorTypeHeartBeat as declared in sensor.h:214
	SensorTypeHeartBeat = 31
	// SensorTypeDynamicSensorMeta as declared in sensor.h:221
	SensorTypeDynamicSensorMeta = 32
	// SensorTypeAdditionalInfo as declared in sensor.h:250
	SensorTypeAdditionalInfo = 33
	// SensorTypeLowLatencyOffbodyDetect as declared in sensor.h:254
	SensorTypeLowLatencyOffbodyDetect = 34
	// SensorTypeAccelerometerUncalibrated as declared in sensor.h:258
	SensorTypeAccelerometerUncalibrated = 35
	// SensorTypeHingeAngle as declared in sensor.h:265
	SensorTypeHingeAngle = 36
	// SensorTypeHeadTracker as declared in sensor.h:273
	SensorTypeHeadTracker = 37
	// SensorTypeAccelerometerLimitedAxes as declared in sensor.h:282
	SensorTypeAccelerometerLimitedAxes = 38
	// SensorTypeGyroscopeLimitedAxes as declared in sensor.h:291
	SensorTypeGyroscopeLimitedAxes = 39
	// SensorTypeAccelerometerLimitedAxesUncalibrated as declared in sensor.h:301
	SensorTypeAccelerometerLimitedAxesUncalibrated = 40
	// SensorTypeGyroscopeLimitedAxesUncalibrated as declared in sensor.h:311
	SensorTypeGyroscopeLimitedAxesUncalibrated = 41
	// SensorTypeHeading as declared in sensor.h:319
	SensorTypeHeading = 42
)

const (
	// SensorStatusNoContact as declared in sensor.h:327
	SensorStatusNoContact = -1
	// SensorStatusUnreliable as declared in sensor.h:329
	SensorStatusUnreliable = 0
	// SensorStatusAccuracyLow as declared in sensor.h:331
	SensorStatusAccuracyLow = 1
	// SensorStatusAccuracyMedium as declared in sensor.h:333
	SensorStatusAccuracyMedium = 2
	// SensorStatusAccuracyHigh as declared in sensor.h:335
	SensorStatusAccuracyHigh = 3
)

const (
	// ReportingModeInvalid as declared in sensor.h:343
	ReportingModeInvalid = -1
	// ReportingModeContinuous as declared in sensor.h:345
	ReportingModeContinuous = 0
	// ReportingModeOnChange as declared in sensor.h:347
	ReportingModeOnChange = 1
	// ReportingModeOneShot as declared in sensor.h:349
	ReportingModeOneShot = 2
	// ReportingModeSpecialTrigger as declared in sensor.h:351
	ReportingModeSpecialTrigger = 3
)

const (
	// SensorDirectRateStop as declared in sensor.h:359
	SensorDirectRateStop = iota
	// SensorDirectRateNormal as declared in sensor.h:361
	SensorDirectRateNormal = 1
	// SensorDirectRateFast as declared in sensor.h:363
	SensorDirectRateFast = 2
	// SensorDirectRateVeryFast as declared in sensor.h:365
	SensorDirectRateVeryFast = 3
)

const (
	// SensorDirectChannelTypeSharedMemory as declared in sensor.h:373
	SensorDirectChannelTypeSharedMemory = 1
	// SensorDirectChannelTypeHardwareBuffer as declared in sensor.h:375
	SensorDirectChannelTypeHardwareBuffer = 2
)

const (
	// SensorAdditionalInfoBegin as declared in sensor.h:385
	SensorAdditionalInfoBegin = iota
	// SensorAdditionalInfoEnd as declared in sensor.h:388
	SensorAdditionalInfoEnd = 1
	// SensorAdditionalInfoUntrackedDelay as declared in sensor.h:396
	SensorAdditionalInfoUntrackedDelay = 0x10000
	// SensorAdditionalInfoInternalTemperature as declared in sensor.h:399
	SensorAdditionalInfoInternalTemperature = 65537
	// SensorAdditionalInfoVec3Calibration as declared in sensor.h:406
	SensorAdditionalInfoVec3Calibration = 65538
	// SensorAdditionalInfoSensorPlacement as declared in sensor.h:414
	SensorAdditionalInfoSensorPlacement = 65539
	// SensorAdditionalInfoSampling as declared in sensor.h:420
	SensorAdditionalInfoSampling = 65540
)

const (
	// ObbStateMounted as declared in storage_manager.h:50
	ObbStateMounted = 1
	// ObbStateUnmounted as declared in storage_manager.h:56
	ObbStateUnmounted = 2
	// ObbStateErrorInternal as declared in storage_manager.h:63
	ObbStateErrorInternal = 20
	// ObbStateErrorCouldNotMount as declared in storage_manager.h:69
	ObbStateErrorCouldNotMount = 21
	// ObbStateErrorCouldNotUnmount as declared in storage_manager.h:76
	ObbStateErrorCouldNotUnmount = 22
	// ObbStateErrorNotMounted as declared in storage_manager.h:83
	ObbStateErrorNotMounted = 23
	// ObbStateErrorAlreadyMounted as declared in storage_manager.h:89
	ObbStateErrorAlreadyMounted = 24
	// ObbStateErrorPermissionDenied as declared in storage_manager.h:97
	ObbStateErrorPermissionDenied = 25
)

const (
	// WindowFlagAllowLockWhileScreenOn as declared in window.h:44
	WindowFlagAllowLockWhileScreenOn = 0x00000001
	// WindowFlagDimBehind as declared in window.h:46
	WindowFlagDimBehind = 0x00000002
	// WindowFlagBlurBehind as declared in window.h:51
	WindowFlagBlurBehind = 0x00000004
	// WindowFlagNotFocusable as declared in window.h:67
	WindowFlagNotFocusable = 0x00000008
	// WindowFlagNotTouchable as declared in window.h:69
	WindowFlagNotTouchable = 0x00000010
	// WindowFlagNotTouchModal as declared in window.h:77
	WindowFlagNotTouchModal = 0x00000020
	// WindowFlagTouchableWhenWaking as declared in window.h:86
	WindowFlagTouchableWhenWaking = 0x00000040
	// WindowFlagKeepScreenOn as declared in window.h:91
	WindowFlagKeepScreenOn = 0x00000080
	// WindowFlagLayoutInScreen as declared in window.h:98
	WindowFlagLayoutInScreen = 0x00000100
	// WindowFlagLayoutNoLimits as declared in window.h:100
	WindowFlagLayoutNoLimits = 0x00000200
	// WindowFlagFullscreen as declared in window.h:111
	WindowFlagFullscreen = 0x00000400
	// WindowFlagForceNotFullscreen as declared in window.h:116
	WindowFlagForceNotFullscreen = 0x00000800
	// WindowFlagDither as declared in window.h:122
	WindowFlagDither = 0x00001000
	// WindowFlagSecure as declared in window.h:128
	WindowFlagSecure = 0x00002000
	// WindowFlagScaled as declared in window.h:134
	WindowFlagScaled = 0x00004000
	// WindowFlagIgnoreCheekPresses as declared in window.h:145
	WindowFlagIgnoreCheekPresses = 0x00008000
	// WindowFlagLayoutInsetDecor as declared in window.h:154
	WindowFlagLayoutInsetDecor = 0x00010000
	// WindowFlagAltFocusableIm as declared in window.h:166
	WindowFlagAltFocusableIm = 0x00020000
	// WindowFlagWatchOutsideTouch as declared in window.h:176
	WindowFlagWatchOutsideTouch = 0x00040000
	// WindowFlagShowWhenLocked as declared in window.h:187
	WindowFlagShowWhenLocked = 0x00080000
	// WindowFlagShowWallpaper as declared in window.h:195
	WindowFlagShowWallpaper = 0x00100000
	// WindowFlagTurnScreenOn as declared in window.h:202
	WindowFlagTurnScreenOn = 0x00200000
	// WindowFlagDismissKeyguard as declared in window.h:216
	WindowFlagDismissKeyguard = 0x00400000
)
