// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package android provides Go bindings for the Android NDK API.
*/
package android
