// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package android

/*
#cgo LDFLAGS: -landroid -llog
#include <android/api-level.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/configuration.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log.h>
#include <android/looper.h>
#include <android/native_activity.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <android/obb.h>
#include <android/rect.h>
#include <android/sensor.h>
#include <android/storage_manager.h>
#include <android/window.h>
#include <jni.h>
#include "jni_call.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// AssetManager as declared in asset_manager.h:54
type AssetManager C.AAssetManager

// AssetDir as declared in asset_manager.h:64
type AssetDir C.AAssetDir

// Asset as declared in asset_manager.h:73
type Asset C.AAsset

// Configuration as declared in configuration.h:50
type Configuration C.AConfiguration

// HardwareBufferDesc as declared in hardware_buffer.h:367
type HardwareBufferDesc struct {
	Width          uint32
	Height         uint32
	Layers         uint32
	Format         uint32
	Usage          uint32
	Stride         uint32
	Rfu0           uint32
	Rfu1           uint32
	refa0098d4f    *C.AHardwareBuffer_Desc
	allocsa0098d4f interface{}
}

// HardwareBufferPlane as declared in hardware_buffer.h:377
type HardwareBufferPlane struct {
	Data           unsafe.Pointer
	PixelStride    uint32
	RowStride      uint32
	ref4b7d584d    *C.AHardwareBuffer_Plane
	allocs4b7d584d interface{}
}

// HardwareBufferPlanes as declared in hardware_buffer.h:385
type HardwareBufferPlanes struct {
	PlaneCount     uint32
	Planes         [4]HardwareBufferPlane
	ref13288f7e    *C.AHardwareBuffer_Planes
	allocs13288f7e interface{}
}

// HardwareBuffer as declared in hardware_buffer.h:390
type HardwareBuffer C.AHardwareBuffer

// InputEvent as declared in input.h:152
type InputEvent C.AInputEvent

// InputQueue as declared in input.h:1404
type InputQueue C.AInputQueue

// Looper as declared in looper.h:47
type Looper C.ALooper

// LooperCallbackFunc type as declared in looper.h:168
type LooperCallbackFunc func(fd int32, events int32, data unsafe.Pointer) int32

// NativeActivity as declared in native_activity.h:119
type NativeActivity struct {
	Callbacks        *NativeActivityCallbacks
	Vm               *JavaVM
	Env              *JNIEnv
	Clazz            Jobject
	InternalDataPath []byte
	ExternalDataPath []byte
	SdkVersion       int32
	Instance         unsafe.Pointer
	AssetManager     *AssetManager
	ObbPath          []byte
	ref2cc295bf      *C.ANativeActivity
	allocs2cc295bf   interface{}
}

// NativeActivityCallbacks as declared in native_activity.h:236
type NativeActivityCallbacks C.ANativeActivityCallbacks

// NativeActivityCreateFunc type as declared in native_activity.h:246
type NativeActivityCreateFunc func(activity *NativeActivity, savedState unsafe.Pointer, savedStateSize uint32)

// NativeWindow as declared in native_window.h:88
type NativeWindow C.ANativeWindow

// NativeWindowBuffer as declared in native_window.h:114
type NativeWindowBuffer struct {
	Width          int32
	Height         int32
	Stride         int32
	Format         int32
	Bits           unsafe.Pointer
	Reserved       [6]uint32
	ref3db2646c    *C.ANativeWindow_Buffer
	allocs3db2646c interface{}
}

// ObbInfo as declared in obb.h:37
type ObbInfo C.AObbInfo

// Rect as declared in rect.h:57
type Rect struct {
	Left           int32
	Top            int32
	Right          int32
	Bottom         int32
	ref9511c547    *C.ARect
	allocs9511c547 interface{}
}

// SensorVector as declared in sensor.h:455
type SensorVector struct {
	Status         int8
	Reserved       [3]byte
	refdc35e822    *C.ASensorVector
	allocsdc35e822 interface{}
}

// MetaDataEvent as declared in sensor.h:460
type MetaDataEvent struct {
	What           int32
	Sensor         int32
	ref4f7ec3e5    *C.AMetaDataEvent
	allocs4f7ec3e5 interface{}
}

// UncalibratedEvent as declared in sensor.h:479
type UncalibratedEvent struct {
	ref193d9a7d    *C.AUncalibratedEvent
	allocs193d9a7d interface{}
}

// HeartRateEvent as declared in sensor.h:484
type HeartRateEvent struct {
	Bpm            float32
	Status         int8
	ref1342bcf5    *C.AHeartRateEvent
	allocs1342bcf5 interface{}
}

// DynamicSensorEvent as declared in sensor.h:489
type DynamicSensorEvent struct {
	Connected      int32
	Handle         int32
	ref9cfbc6e0    *C.ADynamicSensorEvent
	allocs9cfbc6e0 interface{}
}

// AdditionalInfoEvent as declared in sensor.h:502
type AdditionalInfoEvent struct {
	Type           int32
	Serial         int32
	ref4b074385    *C.AAdditionalInfoEvent
	allocs4b074385 interface{}
}

// HeadTrackerEvent as declared in sensor.h:534
type HeadTrackerEvent struct {
	Rx                 float32
	Ry                 float32
	Rz                 float32
	Vx                 float32
	Vy                 float32
	Vz                 float32
	DiscontinuityCount int32
	refc13eaf5         *C.AHeadTrackerEvent
	allocsc13eaf5      interface{}
}

// LimitedAxesImuEvent as declared in sensor.h:553
type LimitedAxesImuEvent struct {
	ref88e0770b    *C.ALimitedAxesImuEvent
	allocs88e0770b interface{}
}

// LimitedAxesImuUncalibratedEvent as declared in sensor.h:580
type LimitedAxesImuUncalibratedEvent struct {
	ref75657dd0    *C.ALimitedAxesImuUncalibratedEvent
	allocs75657dd0 interface{}
}

// HeadingEvent as declared in sensor.h:597
type HeadingEvent struct {
	Heading        float32
	Accuracy       float32
	ref7ab82b4a    *C.AHeadingEvent
	allocs7ab82b4a interface{}
}

// SensorEvent as declared in sensor.h:651
type SensorEvent struct {
	Version        int32
	Sensor         int32
	Type           int32
	Reserved0      int32
	Timestamp      int32
	Flags          uint32
	Reserved1      [3]int32
	refb7a6c7dc    *C.ASensorEvent
	allocsb7a6c7dc interface{}
}

// SensorManager as declared in sensor.h:671
type SensorManager C.ASensorManager

// SensorEventQueue as declared in sensor.h:691
type SensorEventQueue C.ASensorEventQueue

// Sensor as declared in sensor.h:716
type Sensor C.ASensor

// SensorRef as declared in sensor.h:722
type SensorRef C.ASensorRef

// SensorList as declared in sensor.h:728
type SensorList C.ASensorList

// StorageManager as declared in storage_manager.h:40
type StorageManager C.AStorageManager

// StorageManagerObbCallbackFunc type as declared in storage_manager.h:123
type StorageManagerObbCallbackFunc func(filename string, state int32, data unsafe.Pointer)

// Jboolean type as declared in jni.h:30
type Jboolean byte

// Jbyte type as declared in jni.h:31
type Jbyte int8

// Jchar type as declared in jni.h:32
type Jchar uint16

// Jshort type as declared in jni.h:33
type Jshort int16

// Jint type as declared in jni.h:34
type Jint int32

// Jlong type as declared in jni.h:35
type Jlong int32

// Jfloat type as declared in jni.h:36
type Jfloat float32

// Jdouble type as declared in jni.h:37
type Jdouble float64

// Jsize type as declared in jni.h:40
type Jsize int32

// Jobject type as declared in jni.h:83
type Jobject unsafe.Pointer

// Jclass type as declared in jni.h:84
type Jclass unsafe.Pointer

// Jstring type as declared in jni.h:85
type Jstring unsafe.Pointer

// Jarray type as declared in jni.h:86
type Jarray unsafe.Pointer

// JobjectArray type as declared in jni.h:87
type JobjectArray unsafe.Pointer

// JbooleanArray type as declared in jni.h:88
type JbooleanArray unsafe.Pointer

// JbyteArray type as declared in jni.h:89
type JbyteArray unsafe.Pointer

// JcharArray type as declared in jni.h:90
type JcharArray unsafe.Pointer

// JshortArray type as declared in jni.h:91
type JshortArray unsafe.Pointer

// JintArray type as declared in jni.h:92
type JintArray unsafe.Pointer

// JlongArray type as declared in jni.h:93
type JlongArray unsafe.Pointer

// JfloatArray type as declared in jni.h:94
type JfloatArray unsafe.Pointer

// JdoubleArray type as declared in jni.h:95
type JdoubleArray unsafe.Pointer

// Jthrowable type as declared in jni.h:96
type Jthrowable unsafe.Pointer

// Jweak type as declared in jni.h:97
type Jweak unsafe.Pointer

// JfieldID as declared in jni.h:102
type JfieldID C.jfieldID

// JmethodID as declared in jni.h:105
type JmethodID C.jmethodID

// Jvalue as declared in jni.h:119
const sizeofJvalue = unsafe.Sizeof(C.jvalue{})

type Jvalue [sizeofJvalue]byte

// JNINativeMethod as declared in jni.h:132
type JNINativeMethod C.JNINativeMethod

// JNIEnv as declared in jni.h:142
type JNIEnv C.JNIEnv

// JavaVM as declared in jni.h:143
type JavaVM C.JavaVM

// JavaVMAttachArgs as declared in jni.h:1073
type JavaVMAttachArgs struct {
	Version        Jint
	Name           []byte
	Group          Jobject
	refab42f020    *C.JavaVMAttachArgs
	allocsab42f020 interface{}
}

// JavaVMOption as declared in jni.h:1082
type JavaVMOption C.JavaVMOption

// JavaVMInitArgs as declared in jni.h:1090
type JavaVMInitArgs C.JavaVMInitArgs

// _AndroidLogMessage as declared in log.h:187
type _AndroidLogMessage struct {
	StructSize    uint32
	BufferId      int32
	Priority      int32
	Tag           []byte
	File          []byte
	Line          uint32
	Message       []byte
	ref58c2db8    *C.struct___android_log_message
	allocs58c2db8 interface{}
}
