// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gles

/*
#cgo LDFLAGS: -lGLESv1_CM
#include <GLES/gl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// VERSION_ES_CM_1_0 as defined in gl.h:52
	VERSION_ES_CM_1_0 = 1
	// VERSION_ES_CL_1_0 as defined in gl.h:72
	VERSION_ES_CL_1_0 = 1
	// VERSION_ES_CM_1_1 as defined in gl.h:73
	VERSION_ES_CM_1_1 = 1
	// VERSION_ES_CL_1_1 as defined in gl.h:74
	VERSION_ES_CL_1_1 = 1
	// DEPTH_BUFFER_BIT as defined in gl.h:75
	DEPTH_BUFFER_BIT = 0x00000100
	// STENCIL_BUFFER_BIT as defined in gl.h:76
	STENCIL_BUFFER_BIT = 0x00000400
	// COLOR_BUFFER_BIT as defined in gl.h:77
	COLOR_BUFFER_BIT = 0x00004000
	// FALSE as defined in gl.h:78
	FALSE = 0
	// TRUE as defined in gl.h:79
	TRUE = 1
	// POINTS as defined in gl.h:80
	POINTS = 0x0000
	// LINES as defined in gl.h:81
	LINES = 0x0001
	// LINE_LOOP as defined in gl.h:82
	LINE_LOOP = 0x0002
	// LINE_STRIP as defined in gl.h:83
	LINE_STRIP = 0x0003
	// TRIANGLES as defined in gl.h:84
	TRIANGLES = 0x0004
	// TRIANGLE_STRIP as defined in gl.h:85
	TRIANGLE_STRIP = 0x0005
	// TRIANGLE_FAN as defined in gl.h:86
	TRIANGLE_FAN = 0x0006
	// NEVER as defined in gl.h:87
	NEVER = 0x0200
	// LESS as defined in gl.h:88
	LESS = 0x0201
	// EQUAL as defined in gl.h:89
	EQUAL = 0x0202
	// LEQUAL as defined in gl.h:90
	LEQUAL = 0x0203
	// GREATER as defined in gl.h:91
	GREATER = 0x0204
	// NOTEQUAL as defined in gl.h:92
	NOTEQUAL = 0x0205
	// GEQUAL as defined in gl.h:93
	GEQUAL = 0x0206
	// ALWAYS as defined in gl.h:94
	ALWAYS = 0x0207
	// ZERO as defined in gl.h:95
	ZERO = 0
	// ONE as defined in gl.h:96
	ONE = 1
	// SRC_COLOR as defined in gl.h:97
	SRC_COLOR = 0x0300
	// ONE_MINUS_SRC_COLOR as defined in gl.h:98
	ONE_MINUS_SRC_COLOR = 0x0301
	// SRC_ALPHA as defined in gl.h:99
	SRC_ALPHA = 0x0302
	// ONE_MINUS_SRC_ALPHA as defined in gl.h:100
	ONE_MINUS_SRC_ALPHA = 0x0303
	// DST_ALPHA as defined in gl.h:101
	DST_ALPHA = 0x0304
	// ONE_MINUS_DST_ALPHA as defined in gl.h:102
	ONE_MINUS_DST_ALPHA = 0x0305
	// DST_COLOR as defined in gl.h:103
	DST_COLOR = 0x0306
	// ONE_MINUS_DST_COLOR as defined in gl.h:104
	ONE_MINUS_DST_COLOR = 0x0307
	// SRC_ALPHA_SATURATE as defined in gl.h:105
	SRC_ALPHA_SATURATE = 0x0308
	// CLIP_PLANE0 as defined in gl.h:106
	CLIP_PLANE0 = 0x3000
	// CLIP_PLANE1 as defined in gl.h:107
	CLIP_PLANE1 = 0x3001
	// CLIP_PLANE2 as defined in gl.h:108
	CLIP_PLANE2 = 0x3002
	// CLIP_PLANE3 as defined in gl.h:109
	CLIP_PLANE3 = 0x3003
	// CLIP_PLANE4 as defined in gl.h:110
	CLIP_PLANE4 = 0x3004
	// CLIP_PLANE5 as defined in gl.h:111
	CLIP_PLANE5 = 0x3005
	// FRONT as defined in gl.h:112
	FRONT = 0x0404
	// BACK as defined in gl.h:113
	BACK = 0x0405
	// FRONT_AND_BACK as defined in gl.h:114
	FRONT_AND_BACK = 0x0408
	// FOG as defined in gl.h:115
	FOG = 0x0B60
	// LIGHTING as defined in gl.h:116
	LIGHTING = 0x0B50
	// TEXTURE_2D as defined in gl.h:117
	TEXTURE_2D = 0x0DE1
	// CULL_FACE as defined in gl.h:118
	CULL_FACE = 0x0B44
	// ALPHA_TEST as defined in gl.h:119
	ALPHA_TEST = 0x0BC0
	// BLEND as defined in gl.h:120
	BLEND = 0x0BE2
	// COLOR_LOGIC_OP as defined in gl.h:121
	COLOR_LOGIC_OP = 0x0BF2
	// DITHER as defined in gl.h:122
	DITHER = 0x0BD0
	// STENCIL_TEST as defined in gl.h:123
	STENCIL_TEST = 0x0B90
	// DEPTH_TEST as defined in gl.h:124
	DEPTH_TEST = 0x0B71
	// POINT_SMOOTH as defined in gl.h:125
	POINT_SMOOTH = 0x0B10
	// LINE_SMOOTH as defined in gl.h:126
	LINE_SMOOTH = 0x0B20
	// SCISSOR_TEST as defined in gl.h:127
	SCISSOR_TEST = 0x0C11
	// COLOR_MATERIAL as defined in gl.h:128
	COLOR_MATERIAL = 0x0B57
	// NORMALIZE as defined in gl.h:129
	NORMALIZE = 0x0BA1
	// RESCALE_NORMAL as defined in gl.h:130
	RESCALE_NORMAL = 0x803A
	// VERTEX_ARRAY as defined in gl.h:131
	VERTEX_ARRAY = 0x8074
	// NORMAL_ARRAY as defined in gl.h:132
	NORMAL_ARRAY = 0x8075
	// COLOR_ARRAY as defined in gl.h:133
	COLOR_ARRAY = 0x8076
	// TEXTURE_COORD_ARRAY as defined in gl.h:134
	TEXTURE_COORD_ARRAY = 0x8078
	// MULTISAMPLE as defined in gl.h:135
	MULTISAMPLE = 0x809D
	// SAMPLE_ALPHA_TO_COVERAGE as defined in gl.h:136
	SAMPLE_ALPHA_TO_COVERAGE = 0x809E
	// SAMPLE_ALPHA_TO_ONE as defined in gl.h:137
	SAMPLE_ALPHA_TO_ONE = 0x809F
	// SAMPLE_COVERAGE as defined in gl.h:138
	SAMPLE_COVERAGE = 0x80A0
	// NO_ERROR as defined in gl.h:139
	NO_ERROR = 0
	// INVALID_ENUM as defined in gl.h:140
	INVALID_ENUM = 0x0500
	// INVALID_VALUE as defined in gl.h:141
	INVALID_VALUE = 0x0501
	// INVALID_OPERATION as defined in gl.h:142
	INVALID_OPERATION = 0x0502
	// STACK_OVERFLOW as defined in gl.h:143
	STACK_OVERFLOW = 0x0503
	// STACK_UNDERFLOW as defined in gl.h:144
	STACK_UNDERFLOW = 0x0504
	// OUT_OF_MEMORY as defined in gl.h:145
	OUT_OF_MEMORY = 0x0505
	// EXP as defined in gl.h:146
	EXP = 0x0800
	// EXP2 as defined in gl.h:147
	EXP2 = 0x0801
	// FOG_DENSITY as defined in gl.h:148
	FOG_DENSITY = 0x0B62
	// FOG_START as defined in gl.h:149
	FOG_START = 0x0B63
	// FOG_END as defined in gl.h:150
	FOG_END = 0x0B64
	// FOG_MODE as defined in gl.h:151
	FOG_MODE = 0x0B65
	// FOG_COLOR as defined in gl.h:152
	FOG_COLOR = 0x0B66
	// CW as defined in gl.h:153
	CW = 0x0900
	// CCW as defined in gl.h:154
	CCW = 0x0901
	// CURRENT_COLOR as defined in gl.h:155
	CURRENT_COLOR = 0x0B00
	// CURRENT_NORMAL as defined in gl.h:156
	CURRENT_NORMAL = 0x0B02
	// CURRENT_TEXTURE_COORDS as defined in gl.h:157
	CURRENT_TEXTURE_COORDS = 0x0B03
	// POINT_SIZE as defined in gl.h:158
	POINT_SIZE = 0x0B11
	// POINT_SIZE_MIN as defined in gl.h:159
	POINT_SIZE_MIN = 0x8126
	// POINT_SIZE_MAX as defined in gl.h:160
	POINT_SIZE_MAX = 0x8127
	// POINT_FADE_THRESHOLD_SIZE as defined in gl.h:161
	POINT_FADE_THRESHOLD_SIZE = 0x8128
	// POINT_DISTANCE_ATTENUATION as defined in gl.h:162
	POINT_DISTANCE_ATTENUATION = 0x8129
	// SMOOTH_POINT_SIZE_RANGE as defined in gl.h:163
	SMOOTH_POINT_SIZE_RANGE = 0x0B12
	// LINE_WIDTH as defined in gl.h:164
	LINE_WIDTH = 0x0B21
	// SMOOTH_LINE_WIDTH_RANGE as defined in gl.h:165
	SMOOTH_LINE_WIDTH_RANGE = 0x0B22
	// ALIASED_POINT_SIZE_RANGE as defined in gl.h:166
	ALIASED_POINT_SIZE_RANGE = 0x846D
	// ALIASED_LINE_WIDTH_RANGE as defined in gl.h:167
	ALIASED_LINE_WIDTH_RANGE = 0x846E
	// CULL_FACE_MODE as defined in gl.h:168
	CULL_FACE_MODE = 0x0B45
	// FRONT_FACE as defined in gl.h:169
	FRONT_FACE = 0x0B46
	// SHADE_MODEL as defined in gl.h:170
	SHADE_MODEL = 0x0B54
	// DEPTH_RANGE as defined in gl.h:171
	DEPTH_RANGE = 0x0B70
	// DEPTH_WRITEMASK as defined in gl.h:172
	DEPTH_WRITEMASK = 0x0B72
	// DEPTH_CLEAR_VALUE as defined in gl.h:173
	DEPTH_CLEAR_VALUE = 0x0B73
	// DEPTH_FUNC as defined in gl.h:174
	DEPTH_FUNC = 0x0B74
	// STENCIL_CLEAR_VALUE as defined in gl.h:175
	STENCIL_CLEAR_VALUE = 0x0B91
	// STENCIL_FUNC as defined in gl.h:176
	STENCIL_FUNC = 0x0B92
	// STENCIL_VALUE_MASK as defined in gl.h:177
	STENCIL_VALUE_MASK = 0x0B93
	// STENCIL_FAIL as defined in gl.h:178
	STENCIL_FAIL = 0x0B94
	// STENCIL_PASS_DEPTH_FAIL as defined in gl.h:179
	STENCIL_PASS_DEPTH_FAIL = 0x0B95
	// STENCIL_PASS_DEPTH_PASS as defined in gl.h:180
	STENCIL_PASS_DEPTH_PASS = 0x0B96
	// STENCIL_REF as defined in gl.h:181
	STENCIL_REF = 0x0B97
	// STENCIL_WRITEMASK as defined in gl.h:182
	STENCIL_WRITEMASK = 0x0B98
	// MATRIX_MODE as defined in gl.h:183
	MATRIX_MODE = 0x0BA0
	// VIEWPORT as defined in gl.h:184
	VIEWPORT = 0x0BA2
	// MODELVIEW_STACK_DEPTH as defined in gl.h:185
	MODELVIEW_STACK_DEPTH = 0x0BA3
	// PROJECTION_STACK_DEPTH as defined in gl.h:186
	PROJECTION_STACK_DEPTH = 0x0BA4
	// TEXTURE_STACK_DEPTH as defined in gl.h:187
	TEXTURE_STACK_DEPTH = 0x0BA5
	// MODELVIEW_MATRIX as defined in gl.h:188
	MODELVIEW_MATRIX = 0x0BA6
	// PROJECTION_MATRIX as defined in gl.h:189
	PROJECTION_MATRIX = 0x0BA7
	// TEXTURE_MATRIX as defined in gl.h:190
	TEXTURE_MATRIX = 0x0BA8
	// ALPHA_TEST_FUNC as defined in gl.h:191
	ALPHA_TEST_FUNC = 0x0BC1
	// ALPHA_TEST_REF as defined in gl.h:192
	ALPHA_TEST_REF = 0x0BC2
	// BLEND_DST as defined in gl.h:193
	BLEND_DST = 0x0BE0
	// BLEND_SRC as defined in gl.h:194
	BLEND_SRC = 0x0BE1
	// LOGIC_OP_MODE as defined in gl.h:195
	LOGIC_OP_MODE = 0x0BF0
	// SCISSOR_BOX as defined in gl.h:196
	SCISSOR_BOX = 0x0C10
	// COLOR_CLEAR_VALUE as defined in gl.h:197
	COLOR_CLEAR_VALUE = 0x0C22
	// COLOR_WRITEMASK as defined in gl.h:198
	COLOR_WRITEMASK = 0x0C23
	// MAX_LIGHTS as defined in gl.h:199
	MAX_LIGHTS = 0x0D31
	// MAX_CLIP_PLANES as defined in gl.h:200
	MAX_CLIP_PLANES = 0x0D32
	// MAX_TEXTURE_SIZE as defined in gl.h:201
	MAX_TEXTURE_SIZE = 0x0D33
	// MAX_MODELVIEW_STACK_DEPTH as defined in gl.h:202
	MAX_MODELVIEW_STACK_DEPTH = 0x0D36
	// MAX_PROJECTION_STACK_DEPTH as defined in gl.h:203
	MAX_PROJECTION_STACK_DEPTH = 0x0D38
	// MAX_TEXTURE_STACK_DEPTH as defined in gl.h:204
	MAX_TEXTURE_STACK_DEPTH = 0x0D39
	// MAX_VIEWPORT_DIMS as defined in gl.h:205
	MAX_VIEWPORT_DIMS = 0x0D3A
	// MAX_TEXTURE_UNITS as defined in gl.h:206
	MAX_TEXTURE_UNITS = 0x84E2
	// SUBPIXEL_BITS as defined in gl.h:207
	SUBPIXEL_BITS = 0x0D50
	// RED_BITS as defined in gl.h:208
	RED_BITS = 0x0D52
	// GREEN_BITS as defined in gl.h:209
	GREEN_BITS = 0x0D53
	// BLUE_BITS as defined in gl.h:210
	BLUE_BITS = 0x0D54
	// ALPHA_BITS as defined in gl.h:211
	ALPHA_BITS = 0x0D55
	// DEPTH_BITS as defined in gl.h:212
	DEPTH_BITS = 0x0D56
	// STENCIL_BITS as defined in gl.h:213
	STENCIL_BITS = 0x0D57
	// POLYGON_OFFSET_UNITS as defined in gl.h:214
	POLYGON_OFFSET_UNITS = 0x2A00
	// POLYGON_OFFSET_FILL as defined in gl.h:215
	POLYGON_OFFSET_FILL = 0x8037
	// POLYGON_OFFSET_FACTOR as defined in gl.h:216
	POLYGON_OFFSET_FACTOR = 0x8038
	// TEXTURE_BINDING_2D as defined in gl.h:217
	TEXTURE_BINDING_2D = 0x8069
	// VERTEX_ARRAY_SIZE as defined in gl.h:218
	VERTEX_ARRAY_SIZE = 0x807A
	// VERTEX_ARRAY_TYPE as defined in gl.h:219
	VERTEX_ARRAY_TYPE = 0x807B
	// VERTEX_ARRAY_STRIDE as defined in gl.h:220
	VERTEX_ARRAY_STRIDE = 0x807C
	// NORMAL_ARRAY_TYPE as defined in gl.h:221
	NORMAL_ARRAY_TYPE = 0x807E
	// NORMAL_ARRAY_STRIDE as defined in gl.h:222
	NORMAL_ARRAY_STRIDE = 0x807F
	// COLOR_ARRAY_SIZE as defined in gl.h:223
	COLOR_ARRAY_SIZE = 0x8081
	// COLOR_ARRAY_TYPE as defined in gl.h:224
	COLOR_ARRAY_TYPE = 0x8082
	// COLOR_ARRAY_STRIDE as defined in gl.h:225
	COLOR_ARRAY_STRIDE = 0x8083
	// TEXTURE_COORD_ARRAY_SIZE as defined in gl.h:226
	TEXTURE_COORD_ARRAY_SIZE = 0x8088
	// TEXTURE_COORD_ARRAY_TYPE as defined in gl.h:227
	TEXTURE_COORD_ARRAY_TYPE = 0x8089
	// TEXTURE_COORD_ARRAY_STRIDE as defined in gl.h:228
	TEXTURE_COORD_ARRAY_STRIDE = 0x808A
	// VERTEX_ARRAY_POINTER as defined in gl.h:229
	VERTEX_ARRAY_POINTER = 0x808E
	// NORMAL_ARRAY_POINTER as defined in gl.h:230
	NORMAL_ARRAY_POINTER = 0x808F
	// COLOR_ARRAY_POINTER as defined in gl.h:231
	COLOR_ARRAY_POINTER = 0x8090
	// TEXTURE_COORD_ARRAY_POINTER as defined in gl.h:232
	TEXTURE_COORD_ARRAY_POINTER = 0x8092
	// SAMPLE_BUFFERS as defined in gl.h:233
	SAMPLE_BUFFERS = 0x80A8
	// SAMPLES as defined in gl.h:234
	SAMPLES = 0x80A9
	// SAMPLE_COVERAGE_VALUE as defined in gl.h:235
	SAMPLE_COVERAGE_VALUE = 0x80AA
	// SAMPLE_COVERAGE_INVERT as defined in gl.h:236
	SAMPLE_COVERAGE_INVERT = 0x80AB
	// NUM_COMPRESSED_TEXTURE_FORMATS as defined in gl.h:237
	NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2
	// COMPRESSED_TEXTURE_FORMATS as defined in gl.h:238
	COMPRESSED_TEXTURE_FORMATS = 0x86A3
	// DONT_CARE as defined in gl.h:239
	DONT_CARE = 0x1100
	// FASTEST as defined in gl.h:240
	FASTEST = 0x1101
	// NICEST as defined in gl.h:241
	NICEST = 0x1102
	// PERSPECTIVE_CORRECTION_HINT as defined in gl.h:242
	PERSPECTIVE_CORRECTION_HINT = 0x0C50
	// POINT_SMOOTH_HINT as defined in gl.h:243
	POINT_SMOOTH_HINT = 0x0C51
	// LINE_SMOOTH_HINT as defined in gl.h:244
	LINE_SMOOTH_HINT = 0x0C52
	// FOG_HINT as defined in gl.h:245
	FOG_HINT = 0x0C54
	// GENERATE_MIPMAP_HINT as defined in gl.h:246
	GENERATE_MIPMAP_HINT = 0x8192
	// LIGHT_MODEL_AMBIENT as defined in gl.h:247
	LIGHT_MODEL_AMBIENT = 0x0B53
	// LIGHT_MODEL_TWO_SIDE as defined in gl.h:248
	LIGHT_MODEL_TWO_SIDE = 0x0B52
	// AMBIENT as defined in gl.h:249
	AMBIENT = 0x1200
	// DIFFUSE as defined in gl.h:250
	DIFFUSE = 0x1201
	// SPECULAR as defined in gl.h:251
	SPECULAR = 0x1202
	// POSITION as defined in gl.h:252
	POSITION = 0x1203
	// SPOT_DIRECTION as defined in gl.h:253
	SPOT_DIRECTION = 0x1204
	// SPOT_EXPONENT as defined in gl.h:254
	SPOT_EXPONENT = 0x1205
	// SPOT_CUTOFF as defined in gl.h:255
	SPOT_CUTOFF = 0x1206
	// CONSTANT_ATTENUATION as defined in gl.h:256
	CONSTANT_ATTENUATION = 0x1207
	// LINEAR_ATTENUATION as defined in gl.h:257
	LINEAR_ATTENUATION = 0x1208
	// QUADRATIC_ATTENUATION as defined in gl.h:258
	QUADRATIC_ATTENUATION = 0x1209
	// BYTE as defined in gl.h:259
	BYTE = 0x1400
	// UNSIGNED_BYTE as defined in gl.h:260
	UNSIGNED_BYTE = 0x1401
	// SHORT as defined in gl.h:261
	SHORT = 0x1402
	// UNSIGNED_SHORT as defined in gl.h:262
	UNSIGNED_SHORT = 0x1403
	// FLOAT as defined in gl.h:263
	FLOAT = 0x1406
	// FIXED as defined in gl.h:264
	FIXED = 0x140C
	// CLEAR as defined in gl.h:265
	CLEAR = 0x1500
	// AND as defined in gl.h:266
	AND = 0x1501
	// AND_REVERSE as defined in gl.h:267
	AND_REVERSE = 0x1502
	// COPY as defined in gl.h:268
	COPY = 0x1503
	// AND_INVERTED as defined in gl.h:269
	AND_INVERTED = 0x1504
	// NOOP as defined in gl.h:270
	NOOP = 0x1505
	// XOR as defined in gl.h:271
	XOR = 0x1506
	// OR as defined in gl.h:272
	OR = 0x1507
	// NOR as defined in gl.h:273
	NOR = 0x1508
	// EQUIV as defined in gl.h:274
	EQUIV = 0x1509
	// INVERT as defined in gl.h:275
	INVERT = 0x150A
	// OR_REVERSE as defined in gl.h:276
	OR_REVERSE = 0x150B
	// COPY_INVERTED as defined in gl.h:277
	COPY_INVERTED = 0x150C
	// OR_INVERTED as defined in gl.h:278
	OR_INVERTED = 0x150D
	// NAND as defined in gl.h:279
	NAND = 0x150E
	// SET as defined in gl.h:280
	SET = 0x150F
	// EMISSION as defined in gl.h:281
	EMISSION = 0x1600
	// SHININESS as defined in gl.h:282
	SHININESS = 0x1601
	// AMBIENT_AND_DIFFUSE as defined in gl.h:283
	AMBIENT_AND_DIFFUSE = 0x1602
	// MODELVIEW as defined in gl.h:284
	MODELVIEW = 0x1700
	// PROJECTION as defined in gl.h:285
	PROJECTION = 0x1701
	// TEXTURE as defined in gl.h:286
	TEXTURE = 0x1702
	// ALPHA as defined in gl.h:287
	ALPHA = 0x1906
	// RGB as defined in gl.h:288
	RGB = 0x1907
	// RGBA as defined in gl.h:289
	RGBA = 0x1908
	// LUMINANCE as defined in gl.h:290
	LUMINANCE = 0x1909
	// LUMINANCE_ALPHA as defined in gl.h:291
	LUMINANCE_ALPHA = 0x190A
	// UNPACK_ALIGNMENT as defined in gl.h:292
	UNPACK_ALIGNMENT = 0x0CF5
	// PACK_ALIGNMENT as defined in gl.h:293
	PACK_ALIGNMENT = 0x0D05
	// UNSIGNED_SHORT_4_4_4_4 as defined in gl.h:294
	UNSIGNED_SHORT_4_4_4_4 = 0x8033
	// UNSIGNED_SHORT_5_5_5_1 as defined in gl.h:295
	UNSIGNED_SHORT_5_5_5_1 = 0x8034
	// UNSIGNED_SHORT_5_6_5 as defined in gl.h:296
	UNSIGNED_SHORT_5_6_5 = 0x8363
	// FLAT as defined in gl.h:297
	FLAT = 0x1D00
	// SMOOTH as defined in gl.h:298
	SMOOTH = 0x1D01
	// KEEP as defined in gl.h:299
	KEEP = 0x1E00
	// REPLACE as defined in gl.h:300
	REPLACE = 0x1E01
	// INCR as defined in gl.h:301
	INCR = 0x1E02
	// DECR as defined in gl.h:302
	DECR = 0x1E03
	// VENDOR as defined in gl.h:303
	VENDOR = 0x1F00
	// RENDERER as defined in gl.h:304
	RENDERER = 0x1F01
	// VERSION as defined in gl.h:305
	VERSION = 0x1F02
	// EXTENSIONS as defined in gl.h:306
	EXTENSIONS = 0x1F03
	// MODULATE as defined in gl.h:307
	MODULATE = 0x2100
	// DECAL as defined in gl.h:308
	DECAL = 0x2101
	// ADD as defined in gl.h:309
	ADD = 0x0104
	// TEXTURE_ENV_MODE as defined in gl.h:310
	TEXTURE_ENV_MODE = 0x2200
	// TEXTURE_ENV_COLOR as defined in gl.h:311
	TEXTURE_ENV_COLOR = 0x2201
	// TEXTURE_ENV as defined in gl.h:312
	TEXTURE_ENV = 0x2300
	// NEAREST as defined in gl.h:313
	NEAREST = 0x2600
	// LINEAR as defined in gl.h:314
	LINEAR = 0x2601
	// NEAREST_MIPMAP_NEAREST as defined in gl.h:315
	NEAREST_MIPMAP_NEAREST = 0x2700
	// LINEAR_MIPMAP_NEAREST as defined in gl.h:316
	LINEAR_MIPMAP_NEAREST = 0x2701
	// NEAREST_MIPMAP_LINEAR as defined in gl.h:317
	NEAREST_MIPMAP_LINEAR = 0x2702
	// LINEAR_MIPMAP_LINEAR as defined in gl.h:318
	LINEAR_MIPMAP_LINEAR = 0x2703
	// TEXTURE_MAG_FILTER as defined in gl.h:319
	TEXTURE_MAG_FILTER = 0x2800
	// TEXTURE_MIN_FILTER as defined in gl.h:320
	TEXTURE_MIN_FILTER = 0x2801
	// TEXTURE_WRAP_S as defined in gl.h:321
	TEXTURE_WRAP_S = 0x2802
	// TEXTURE_WRAP_T as defined in gl.h:322
	TEXTURE_WRAP_T = 0x2803
	// GENERATE_MIPMAP as defined in gl.h:323
	GENERATE_MIPMAP = 0x8191
	// TEXTURE0 as defined in gl.h:324
	TEXTURE0 = 0x84C0
	// TEXTURE1 as defined in gl.h:325
	TEXTURE1 = 0x84C1
	// TEXTURE2 as defined in gl.h:326
	TEXTURE2 = 0x84C2
	// TEXTURE3 as defined in gl.h:327
	TEXTURE3 = 0x84C3
	// TEXTURE4 as defined in gl.h:328
	TEXTURE4 = 0x84C4
	// TEXTURE5 as defined in gl.h:329
	TEXTURE5 = 0x84C5
	// TEXTURE6 as defined in gl.h:330
	TEXTURE6 = 0x84C6
	// TEXTURE7 as defined in gl.h:331
	TEXTURE7 = 0x84C7
	// TEXTURE8 as defined in gl.h:332
	TEXTURE8 = 0x84C8
	// TEXTURE9 as defined in gl.h:333
	TEXTURE9 = 0x84C9
	// TEXTURE10 as defined in gl.h:334
	TEXTURE10 = 0x84CA
	// TEXTURE11 as defined in gl.h:335
	TEXTURE11 = 0x84CB
	// TEXTURE12 as defined in gl.h:336
	TEXTURE12 = 0x84CC
	// TEXTURE13 as defined in gl.h:337
	TEXTURE13 = 0x84CD
	// TEXTURE14 as defined in gl.h:338
	TEXTURE14 = 0x84CE
	// TEXTURE15 as defined in gl.h:339
	TEXTURE15 = 0x84CF
	// TEXTURE16 as defined in gl.h:340
	TEXTURE16 = 0x84D0
	// TEXTURE17 as defined in gl.h:341
	TEXTURE17 = 0x84D1
	// TEXTURE18 as defined in gl.h:342
	TEXTURE18 = 0x84D2
	// TEXTURE19 as defined in gl.h:343
	TEXTURE19 = 0x84D3
	// TEXTURE20 as defined in gl.h:344
	TEXTURE20 = 0x84D4
	// TEXTURE21 as defined in gl.h:345
	TEXTURE21 = 0x84D5
	// TEXTURE22 as defined in gl.h:346
	TEXTURE22 = 0x84D6
	// TEXTURE23 as defined in gl.h:347
	TEXTURE23 = 0x84D7
	// TEXTURE24 as defined in gl.h:348
	TEXTURE24 = 0x84D8
	// TEXTURE25 as defined in gl.h:349
	TEXTURE25 = 0x84D9
	// TEXTURE26 as defined in gl.h:350
	TEXTURE26 = 0x84DA
	// TEXTURE27 as defined in gl.h:351
	TEXTURE27 = 0x84DB
	// TEXTURE28 as defined in gl.h:352
	TEXTURE28 = 0x84DC
	// TEXTURE29 as defined in gl.h:353
	TEXTURE29 = 0x84DD
	// TEXTURE30 as defined in gl.h:354
	TEXTURE30 = 0x84DE
	// TEXTURE31 as defined in gl.h:355
	TEXTURE31 = 0x84DF
	// ACTIVE_TEXTURE as defined in gl.h:356
	ACTIVE_TEXTURE = 0x84E0
	// CLIENT_ACTIVE_TEXTURE as defined in gl.h:357
	CLIENT_ACTIVE_TEXTURE = 0x84E1
	// REPEAT as defined in gl.h:358
	REPEAT = 0x2901
	// CLAMP_TO_EDGE as defined in gl.h:359
	CLAMP_TO_EDGE = 0x812F
	// LIGHT0 as defined in gl.h:360
	LIGHT0 = 0x4000
	// LIGHT1 as defined in gl.h:361
	LIGHT1 = 0x4001
	// LIGHT2 as defined in gl.h:362
	LIGHT2 = 0x4002
	// LIGHT3 as defined in gl.h:363
	LIGHT3 = 0x4003
	// LIGHT4 as defined in gl.h:364
	LIGHT4 = 0x4004
	// LIGHT5 as defined in gl.h:365
	LIGHT5 = 0x4005
	// LIGHT6 as defined in gl.h:366
	LIGHT6 = 0x4006
	// LIGHT7 as defined in gl.h:367
	LIGHT7 = 0x4007
	// ARRAY_BUFFER as defined in gl.h:368
	ARRAY_BUFFER = 0x8892
	// ELEMENT_ARRAY_BUFFER as defined in gl.h:369
	ELEMENT_ARRAY_BUFFER = 0x8893
	// ARRAY_BUFFER_BINDING as defined in gl.h:370
	ARRAY_BUFFER_BINDING = 0x8894
	// ELEMENT_ARRAY_BUFFER_BINDING as defined in gl.h:371
	ELEMENT_ARRAY_BUFFER_BINDING = 0x8895
	// VERTEX_ARRAY_BUFFER_BINDING as defined in gl.h:372
	VERTEX_ARRAY_BUFFER_BINDING = 0x8896
	// NORMAL_ARRAY_BUFFER_BINDING as defined in gl.h:373
	NORMAL_ARRAY_BUFFER_BINDING = 0x8897
	// COLOR_ARRAY_BUFFER_BINDING as defined in gl.h:374
	COLOR_ARRAY_BUFFER_BINDING = 0x8898
	// TEXTURE_COORD_ARRAY_BUFFER_BINDING as defined in gl.h:375
	TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A
	// STATIC_DRAW as defined in gl.h:376
	STATIC_DRAW = 0x88E4
	// DYNAMIC_DRAW as defined in gl.h:377
	DYNAMIC_DRAW = 0x88E8
	// BUFFER_SIZE as defined in gl.h:378
	BUFFER_SIZE = 0x8764
	// BUFFER_USAGE as defined in gl.h:379
	BUFFER_USAGE = 0x8765
	// SUBTRACT as defined in gl.h:380
	SUBTRACT = 0x84E7
	// COMBINE as defined in gl.h:381
	COMBINE = 0x8570
	// COMBINE_RGB as defined in gl.h:382
	COMBINE_RGB = 0x8571
	// COMBINE_ALPHA as defined in gl.h:383
	COMBINE_ALPHA = 0x8572
	// RGB_SCALE as defined in gl.h:384
	RGB_SCALE = 0x8573
	// ADD_SIGNED as defined in gl.h:385
	ADD_SIGNED = 0x8574
	// INTERPOLATE as defined in gl.h:386
	INTERPOLATE = 0x8575
	// CONSTANT as defined in gl.h:387
	CONSTANT = 0x8576
	// PRIMARY_COLOR as defined in gl.h:388
	PRIMARY_COLOR = 0x8577
	// PREVIOUS as defined in gl.h:389
	PREVIOUS = 0x8578
	// OPERAND0_RGB as defined in gl.h:390
	OPERAND0_RGB = 0x8590
	// OPERAND1_RGB as defined in gl.h:391
	OPERAND1_RGB = 0x8591
	// OPERAND2_RGB as defined in gl.h:392
	OPERAND2_RGB = 0x8592
	// OPERAND0_ALPHA as defined in gl.h:393
	OPERAND0_ALPHA = 0x8598
	// OPERAND1_ALPHA as defined in gl.h:394
	OPERAND1_ALPHA = 0x8599
	// OPERAND2_ALPHA as defined in gl.h:395
	OPERAND2_ALPHA = 0x859A
	// ALPHA_SCALE as defined in gl.h:396
	ALPHA_SCALE = 0x0D1C
	// SRC0_RGB as defined in gl.h:397
	SRC0_RGB = 0x8580
	// SRC1_RGB as defined in gl.h:398
	SRC1_RGB = 0x8581
	// SRC2_RGB as defined in gl.h:399
	SRC2_RGB = 0x8582
	// SRC0_ALPHA as defined in gl.h:400
	SRC0_ALPHA = 0x8588
	// SRC1_ALPHA as defined in gl.h:401
	SRC1_ALPHA = 0x8589
	// SRC2_ALPHA as defined in gl.h:402
	SRC2_ALPHA = 0x858A
	// DOT3_RGB as defined in gl.h:403
	DOT3_RGB = 0x86AE
	// DOT3_RGBA as defined in gl.h:404
	DOT3_RGBA = 0x86AF
	// OES_compressed_paletted_texture as defined in gl.h:552
	OES_compressed_paletted_texture = 1
	// PALETTE4_RGB8_OES as defined in gl.h:553
	PALETTE4_RGB8_OES = 0x8B90
	// PALETTE4_RGBA8_OES as defined in gl.h:554
	PALETTE4_RGBA8_OES = 0x8B91
	// PALETTE4_R5_G6_B5_OES as defined in gl.h:555
	PALETTE4_R5_G6_B5_OES = 0x8B92
	// PALETTE4_RGBA4_OES as defined in gl.h:556
	PALETTE4_RGBA4_OES = 0x8B93
	// PALETTE4_RGB5_A1_OES as defined in gl.h:557
	PALETTE4_RGB5_A1_OES = 0x8B94
	// PALETTE8_RGB8_OES as defined in gl.h:558
	PALETTE8_RGB8_OES = 0x8B95
	// PALETTE8_RGBA8_OES as defined in gl.h:559
	PALETTE8_RGBA8_OES = 0x8B96
	// PALETTE8_R5_G6_B5_OES as defined in gl.h:560
	PALETTE8_R5_G6_B5_OES = 0x8B97
	// PALETTE8_RGBA4_OES as defined in gl.h:561
	PALETTE8_RGBA4_OES = 0x8B98
	// PALETTE8_RGB5_A1_OES as defined in gl.h:562
	PALETTE8_RGB5_A1_OES = 0x8B99
	// OES_point_size_array as defined in gl.h:566
	OES_point_size_array = 1
	// POINT_SIZE_ARRAY_OES as defined in gl.h:567
	POINT_SIZE_ARRAY_OES = 0x8B9C
	// POINT_SIZE_ARRAY_TYPE_OES as defined in gl.h:568
	POINT_SIZE_ARRAY_TYPE_OES = 0x898A
	// POINT_SIZE_ARRAY_STRIDE_OES as defined in gl.h:569
	POINT_SIZE_ARRAY_STRIDE_OES = 0x898B
	// POINT_SIZE_ARRAY_POINTER_OES as defined in gl.h:570
	POINT_SIZE_ARRAY_POINTER_OES = 0x898C
	// POINT_SIZE_ARRAY_BUFFER_BINDING_OES as defined in gl.h:571
	POINT_SIZE_ARRAY_BUFFER_BINDING_OES = 0x8B9F
	// OES_point_sprite as defined in gl.h:576
	OES_point_sprite = 1
	// POINT_SPRITE_OES as defined in gl.h:577
	POINT_SPRITE_OES = 0x8861
	// COORD_REPLACE_OES as defined in gl.h:578
	COORD_REPLACE_OES = 0x8862
	// OES_read_format as defined in gl.h:582
	OES_read_format = 1
	// IMPLEMENTATION_COLOR_READ_TYPE_OES as defined in gl.h:583
	IMPLEMENTATION_COLOR_READ_TYPE_OES = 0x8B9A
	// IMPLEMENTATION_COLOR_READ_FORMAT_OES as defined in gl.h:584
	IMPLEMENTATION_COLOR_READ_FORMAT_OES = 0x8B9B
)
