// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gles

/*
#cgo LDFLAGS: -lGLESv1_CM
#include <GLES/gl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// AlphaFunc function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glAlphaFunc.xml
func AlphaFunc(_func uint32, ref float32) {
	c_func, c_funcAllocMap := (C.GLenum)(_func), cgoAllocsUnknown
	cref, crefAllocMap := (C.GLfloat)(ref), cgoAllocsUnknown
	C.glAlphaFunc(c_func, cref)
	runtime.KeepAlive(crefAllocMap)
	runtime.KeepAlive(c_funcAllocMap)
}

// ClearColor function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClearColor.xml
func ClearColor(red float32, green float32, blue float32, alpha float32) {
	cred, credAllocMap := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glClearColor(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// ClearDepthf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClearDepthf.xml
func ClearDepthf(d float32) {
	cd, cdAllocMap := (C.GLfloat)(d), cgoAllocsUnknown
	C.glClearDepthf(cd)
	runtime.KeepAlive(cdAllocMap)
}

// ClipPlanef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClipPlanef.xml
func ClipPlanef(p uint32, eqn []float32) {
	cp, cpAllocMap := (C.GLenum)(p), cgoAllocsUnknown
	ceqn, ceqnAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&eqn)).Data)), cgoAllocsUnknown
	C.glClipPlanef(cp, ceqn)
	runtime.KeepAlive(ceqnAllocMap)
	runtime.KeepAlive(cpAllocMap)
}

// Color4f function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glColor4f.xml
func Color4f(red float32, green float32, blue float32, alpha float32) {
	cred, credAllocMap := (C.GLfloat)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLfloat)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLfloat)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLfloat)(alpha), cgoAllocsUnknown
	C.glColor4f(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// DepthRangef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDepthRangef.xml
func DepthRangef(n float32, f float32) {
	cn, cnAllocMap := (C.GLfloat)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfloat)(f), cgoAllocsUnknown
	C.glDepthRangef(cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// Fogf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFogf.xml
func Fogf(pname uint32, param float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glFogf(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// Fogfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFogfv.xml
func Fogfv(pname uint32, params []float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glFogfv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// Frustumf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFrustumf.xml
func Frustumf(l float32, r float32, b float32, t float32, n float32, f float32) {
	cl, clAllocMap := (C.GLfloat)(l), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfloat)(r), cgoAllocsUnknown
	cb, cbAllocMap := (C.GLfloat)(b), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfloat)(t), cgoAllocsUnknown
	cn, cnAllocMap := (C.GLfloat)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfloat)(f), cgoAllocsUnknown
	C.glFrustumf(cl, cr, cb, ct, cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(cbAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(clAllocMap)
}

// GetClipPlanef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetClipPlanef.xml
func GetClipPlanef(plane uint32, equation []float32) {
	cplane, cplaneAllocMap := (C.GLenum)(plane), cgoAllocsUnknown
	cequation, cequationAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&equation)).Data)), cgoAllocsUnknown
	C.glGetClipPlanef(cplane, cequation)
	runtime.KeepAlive(cequationAllocMap)
	runtime.KeepAlive(cplaneAllocMap)
}

// GetFloatv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetFloatv.xml
func GetFloatv(pname uint32, data []float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, cdataAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetFloatv(cpname, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// GetLightfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetLightfv.xml
func GetLightfv(light uint32, pname uint32, params []float32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetLightfv(clight, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// GetMaterialfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetMaterialfv.xml
func GetMaterialfv(face uint32, pname uint32, params []float32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetMaterialfv(cface, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// GetTexEnvfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexEnvfv.xml
func GetTexEnvfv(target uint32, pname uint32, params []float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnvfv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// GetTexParameterfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexParameterfv.xml
func GetTexParameterfv(target uint32, pname uint32, params []float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameterfv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// LightModelf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightModelf.xml
func LightModelf(pname uint32, param float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glLightModelf(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// LightModelfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightModelfv.xml
func LightModelfv(pname uint32, params []float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightModelfv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// Lightf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightf.xml
func Lightf(light uint32, pname uint32, param float32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glLightf(clight, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// Lightfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightfv.xml
func Lightfv(light uint32, pname uint32, params []float32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightfv(clight, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// LineWidth function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLineWidth.xml
func LineWidth(width float32) {
	cwidth, cwidthAllocMap := (C.GLfloat)(width), cgoAllocsUnknown
	C.glLineWidth(cwidth)
	runtime.KeepAlive(cwidthAllocMap)
}

// LoadMatrixf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLoadMatrixf.xml
func LoadMatrixf(m []float32) {
	cm, cmAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glLoadMatrixf(cm)
	runtime.KeepAlive(cmAllocMap)
}

// Materialf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMaterialf.xml
func Materialf(face uint32, pname uint32, param float32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glMaterialf(cface, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// Materialfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMaterialfv.xml
func Materialfv(face uint32, pname uint32, params []float32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glMaterialfv(cface, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// MultMatrixf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMultMatrixf.xml
func MultMatrixf(m []float32) {
	cm, cmAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glMultMatrixf(cm)
	runtime.KeepAlive(cmAllocMap)
}

// MultiTexCoord4f function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMultiTexCoord4f.xml
func MultiTexCoord4f(target uint32, s float32, t float32, r float32, q float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cs, csAllocMap := (C.GLfloat)(s), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfloat)(t), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfloat)(r), cgoAllocsUnknown
	cq, cqAllocMap := (C.GLfloat)(q), cgoAllocsUnknown
	C.glMultiTexCoord4f(ctarget, cs, ct, cr, cq)
	runtime.KeepAlive(cqAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(csAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// Normal3f function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glNormal3f.xml
func Normal3f(nx float32, ny float32, nz float32) {
	cnx, cnxAllocMap := (C.GLfloat)(nx), cgoAllocsUnknown
	cny, cnyAllocMap := (C.GLfloat)(ny), cgoAllocsUnknown
	cnz, cnzAllocMap := (C.GLfloat)(nz), cgoAllocsUnknown
	C.glNormal3f(cnx, cny, cnz)
	runtime.KeepAlive(cnzAllocMap)
	runtime.KeepAlive(cnyAllocMap)
	runtime.KeepAlive(cnxAllocMap)
}

// Orthof function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glOrthof.xml
func Orthof(l float32, r float32, b float32, t float32, n float32, f float32) {
	cl, clAllocMap := (C.GLfloat)(l), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfloat)(r), cgoAllocsUnknown
	cb, cbAllocMap := (C.GLfloat)(b), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfloat)(t), cgoAllocsUnknown
	cn, cnAllocMap := (C.GLfloat)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfloat)(f), cgoAllocsUnknown
	C.glOrthof(cl, cr, cb, ct, cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(cbAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(clAllocMap)
}

// PointParameterf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointParameterf.xml
func PointParameterf(pname uint32, param float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glPointParameterf(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// PointParameterfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointParameterfv.xml
func PointParameterfv(pname uint32, params []float32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glPointParameterfv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// PointSize function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointSize.xml
func PointSize(size float32) {
	csize, csizeAllocMap := (C.GLfloat)(size), cgoAllocsUnknown
	C.glPointSize(csize)
	runtime.KeepAlive(csizeAllocMap)
}

// PolygonOffset function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPolygonOffset.xml
func PolygonOffset(factor float32, units float32) {
	cfactor, cfactorAllocMap := (C.GLfloat)(factor), cgoAllocsUnknown
	cunits, cunitsAllocMap := (C.GLfloat)(units), cgoAllocsUnknown
	C.glPolygonOffset(cfactor, cunits)
	runtime.KeepAlive(cunitsAllocMap)
	runtime.KeepAlive(cfactorAllocMap)
}

// Rotatef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glRotatef.xml
func Rotatef(angle float32, x float32, y float32, z float32) {
	cangle, cangleAllocMap := (C.GLfloat)(angle), cgoAllocsUnknown
	cx, cxAllocMap := (C.GLfloat)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfloat)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfloat)(z), cgoAllocsUnknown
	C.glRotatef(cangle, cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
	runtime.KeepAlive(cangleAllocMap)
}

// Scalef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glScalef.xml
func Scalef(x float32, y float32, z float32) {
	cx, cxAllocMap := (C.GLfloat)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfloat)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfloat)(z), cgoAllocsUnknown
	C.glScalef(cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// TexEnvf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnvf.xml
func TexEnvf(target uint32, pname uint32, param float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexEnvf(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexEnvfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnvfv.xml
func TexEnvfv(target uint32, pname uint32, params []float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnvfv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameterf function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameterf.xml
func TexParameterf(target uint32, pname uint32, param float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfloat)(param), cgoAllocsUnknown
	C.glTexParameterf(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameterfv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameterfv.xml
func TexParameterfv(target uint32, pname uint32, params []float32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfloat)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameterfv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// Translatef function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTranslatef.xml
func Translatef(x float32, y float32, z float32) {
	cx, cxAllocMap := (C.GLfloat)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfloat)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfloat)(z), cgoAllocsUnknown
	C.glTranslatef(cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// ActiveTexture function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glActiveTexture.xml
func ActiveTexture(texture uint32) {
	ctexture, ctextureAllocMap := (C.GLenum)(texture), cgoAllocsUnknown
	C.glActiveTexture(ctexture)
	runtime.KeepAlive(ctextureAllocMap)
}

// AlphaFuncx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glAlphaFuncx.xml
func AlphaFuncx(_func uint32, ref int32) {
	c_func, c_funcAllocMap := (C.GLenum)(_func), cgoAllocsUnknown
	cref, crefAllocMap := (C.GLfixed)(ref), cgoAllocsUnknown
	C.glAlphaFuncx(c_func, cref)
	runtime.KeepAlive(crefAllocMap)
	runtime.KeepAlive(c_funcAllocMap)
}

// BindBuffer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glBindBuffer.xml
func BindBuffer(target uint32, buffer uint32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (C.GLuint)(buffer), cgoAllocsUnknown
	C.glBindBuffer(ctarget, cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// BindTexture function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glBindTexture.xml
func BindTexture(target uint32, texture uint32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	ctexture, ctextureAllocMap := (C.GLuint)(texture), cgoAllocsUnknown
	C.glBindTexture(ctarget, ctexture)
	runtime.KeepAlive(ctextureAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// BlendFunc function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glBlendFunc.xml
func BlendFunc(sfactor uint32, dfactor uint32) {
	csfactor, csfactorAllocMap := (C.GLenum)(sfactor), cgoAllocsUnknown
	cdfactor, cdfactorAllocMap := (C.GLenum)(dfactor), cgoAllocsUnknown
	C.glBlendFunc(csfactor, cdfactor)
	runtime.KeepAlive(cdfactorAllocMap)
	runtime.KeepAlive(csfactorAllocMap)
}

// BufferData function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glBufferData.xml
func BufferData(target uint32, size int32, data unsafe.Pointer, usage uint32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	csize, csizeAllocMap := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, cdataAllocMap := data, cgoAllocsUnknown
	cusage, cusageAllocMap := (C.GLenum)(usage), cgoAllocsUnknown
	C.glBufferData(ctarget, csize, cdata, cusage)
	runtime.KeepAlive(cusageAllocMap)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// BufferSubData function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glBufferSubData.xml
func BufferSubData(target uint32, offset int32, size int32, data unsafe.Pointer) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	coffset, coffsetAllocMap := (C.GLintptr)(offset), cgoAllocsUnknown
	csize, csizeAllocMap := (C.GLsizeiptr)(size), cgoAllocsUnknown
	cdata, cdataAllocMap := data, cgoAllocsUnknown
	C.glBufferSubData(ctarget, coffset, csize, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(csizeAllocMap)
	runtime.KeepAlive(coffsetAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// Clear function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClear.xml
func Clear(mask uint32) {
	cmask, cmaskAllocMap := (C.GLbitfield)(mask), cgoAllocsUnknown
	C.glClear(cmask)
	runtime.KeepAlive(cmaskAllocMap)
}

// ClearColorx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClearColorx.xml
func ClearColorx(red int32, green int32, blue int32, alpha int32) {
	cred, credAllocMap := (C.GLfixed)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLfixed)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLfixed)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLfixed)(alpha), cgoAllocsUnknown
	C.glClearColorx(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// ClearDepthx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClearDepthx.xml
func ClearDepthx(depth int32) {
	cdepth, cdepthAllocMap := (C.GLfixed)(depth), cgoAllocsUnknown
	C.glClearDepthx(cdepth)
	runtime.KeepAlive(cdepthAllocMap)
}

// ClearStencil function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClearStencil.xml
func ClearStencil(s int32) {
	cs, csAllocMap := (C.GLint)(s), cgoAllocsUnknown
	C.glClearStencil(cs)
	runtime.KeepAlive(csAllocMap)
}

// ClientActiveTexture function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClientActiveTexture.xml
func ClientActiveTexture(texture uint32) {
	ctexture, ctextureAllocMap := (C.GLenum)(texture), cgoAllocsUnknown
	C.glClientActiveTexture(ctexture)
	runtime.KeepAlive(ctextureAllocMap)
}

// ClipPlanex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glClipPlanex.xml
func ClipPlanex(plane uint32, equation []int32) {
	cplane, cplaneAllocMap := (C.GLenum)(plane), cgoAllocsUnknown
	cequation, cequationAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&equation)).Data)), cgoAllocsUnknown
	C.glClipPlanex(cplane, cequation)
	runtime.KeepAlive(cequationAllocMap)
	runtime.KeepAlive(cplaneAllocMap)
}

// Color4ub function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glColor4ub.xml
func Color4ub(red byte, green byte, blue byte, alpha byte) {
	cred, credAllocMap := (C.GLubyte)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLubyte)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLubyte)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLubyte)(alpha), cgoAllocsUnknown
	C.glColor4ub(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// Color4x function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glColor4x.xml
func Color4x(red int32, green int32, blue int32, alpha int32) {
	cred, credAllocMap := (C.GLfixed)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLfixed)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLfixed)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLfixed)(alpha), cgoAllocsUnknown
	C.glColor4x(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// ColorMask function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glColorMask.xml
func ColorMask(red byte, green byte, blue byte, alpha byte) {
	cred, credAllocMap := (C.GLboolean)(red), cgoAllocsUnknown
	cgreen, cgreenAllocMap := (C.GLboolean)(green), cgoAllocsUnknown
	cblue, cblueAllocMap := (C.GLboolean)(blue), cgoAllocsUnknown
	calpha, calphaAllocMap := (C.GLboolean)(alpha), cgoAllocsUnknown
	C.glColorMask(cred, cgreen, cblue, calpha)
	runtime.KeepAlive(calphaAllocMap)
	runtime.KeepAlive(cblueAllocMap)
	runtime.KeepAlive(cgreenAllocMap)
	runtime.KeepAlive(credAllocMap)
}

// ColorPointer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glColorPointer.xml
func ColorPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, csizeAllocMap := (C.GLint)(size), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, cstrideAllocMap := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, cpointerAllocMap := pointer, cgoAllocsUnknown
	C.glColorPointer(csize, ckind, cstride, cpointer)
	runtime.KeepAlive(cpointerAllocMap)
	runtime.KeepAlive(cstrideAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(csizeAllocMap)
}

// CompressedTexImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glCompressedTexImage2D.xml
func CompressedTexImage2D(target uint32, level int32, internalformat uint32, width int32, height int32, border int32, imageSize int32, data unsafe.Pointer) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, cinternalformatAllocMap := (C.GLenum)(internalformat), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, cborderAllocMap := (C.GLint)(border), cgoAllocsUnknown
	cimageSize, cimageSizeAllocMap := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, cdataAllocMap := data, cgoAllocsUnknown
	C.glCompressedTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cimageSize, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cimageSizeAllocMap)
	runtime.KeepAlive(cborderAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cinternalformatAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// CompressedTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glCompressedTexSubImage2D.xml
func CompressedTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, imageSize int32, data unsafe.Pointer) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, cxoffsetAllocMap := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, cyoffsetAllocMap := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, cformatAllocMap := (C.GLenum)(format), cgoAllocsUnknown
	cimageSize, cimageSizeAllocMap := (C.GLsizei)(imageSize), cgoAllocsUnknown
	cdata, cdataAllocMap := data, cgoAllocsUnknown
	C.glCompressedTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, cimageSize, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cimageSizeAllocMap)
	runtime.KeepAlive(cformatAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyoffsetAllocMap)
	runtime.KeepAlive(cxoffsetAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// CopyTexImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glCopyTexImage2D.xml
func CopyTexImage2D(target uint32, level int32, internalformat uint32, x int32, y int32, width int32, height int32, border int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, cinternalformatAllocMap := (C.GLenum)(internalformat), cgoAllocsUnknown
	cx, cxAllocMap := (C.GLint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLint)(y), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, cborderAllocMap := (C.GLint)(border), cgoAllocsUnknown
	C.glCopyTexImage2D(ctarget, clevel, cinternalformat, cx, cy, cwidth, cheight, cborder)
	runtime.KeepAlive(cborderAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
	runtime.KeepAlive(cinternalformatAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// CopyTexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glCopyTexSubImage2D.xml
func CopyTexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, x int32, y int32, width int32, height int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, cxoffsetAllocMap := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, cyoffsetAllocMap := (C.GLint)(yoffset), cgoAllocsUnknown
	cx, cxAllocMap := (C.GLint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLint)(y), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	C.glCopyTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cx, cy, cwidth, cheight)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
	runtime.KeepAlive(cyoffsetAllocMap)
	runtime.KeepAlive(cxoffsetAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// CullFace function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glCullFace.xml
func CullFace(mode uint32) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	C.glCullFace(cmode)
	runtime.KeepAlive(cmodeAllocMap)
}

// DeleteBuffers function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDeleteBuffers.xml
func DeleteBuffers(n int32, buffers []uint32) {
	cn, cnAllocMap := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, cbuffersAllocMap := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glDeleteBuffers(cn, cbuffers)
	runtime.KeepAlive(cbuffersAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// DeleteTextures function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDeleteTextures.xml
func DeleteTextures(n int32, textures []uint32) {
	cn, cnAllocMap := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, ctexturesAllocMap := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glDeleteTextures(cn, ctextures)
	runtime.KeepAlive(ctexturesAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// DepthFunc function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDepthFunc.xml
func DepthFunc(_func uint32) {
	c_func, c_funcAllocMap := (C.GLenum)(_func), cgoAllocsUnknown
	C.glDepthFunc(c_func)
	runtime.KeepAlive(c_funcAllocMap)
}

// DepthMask function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDepthMask.xml
func DepthMask(flag byte) {
	cflag, cflagAllocMap := (C.GLboolean)(flag), cgoAllocsUnknown
	C.glDepthMask(cflag)
	runtime.KeepAlive(cflagAllocMap)
}

// DepthRangex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDepthRangex.xml
func DepthRangex(n int32, f int32) {
	cn, cnAllocMap := (C.GLfixed)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfixed)(f), cgoAllocsUnknown
	C.glDepthRangex(cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// Disable function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDisable.xml
func Disable(cap uint32) {
	ccap, ccapAllocMap := (C.GLenum)(cap), cgoAllocsUnknown
	C.glDisable(ccap)
	runtime.KeepAlive(ccapAllocMap)
}

// DisableClientState function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDisableClientState.xml
func DisableClientState(array uint32) {
	carray, carrayAllocMap := (C.GLenum)(array), cgoAllocsUnknown
	C.glDisableClientState(carray)
	runtime.KeepAlive(carrayAllocMap)
}

// DrawArrays function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDrawArrays.xml
func DrawArrays(mode uint32, first int32, count int32) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	cfirst, cfirstAllocMap := (C.GLint)(first), cgoAllocsUnknown
	ccount, ccountAllocMap := (C.GLsizei)(count), cgoAllocsUnknown
	C.glDrawArrays(cmode, cfirst, ccount)
	runtime.KeepAlive(ccountAllocMap)
	runtime.KeepAlive(cfirstAllocMap)
	runtime.KeepAlive(cmodeAllocMap)
}

// DrawElements function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glDrawElements.xml
func DrawElements(mode uint32, count int32, kind uint32, indices unsafe.Pointer) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	ccount, ccountAllocMap := (C.GLsizei)(count), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cindices, cindicesAllocMap := indices, cgoAllocsUnknown
	C.glDrawElements(cmode, ccount, ckind, cindices)
	runtime.KeepAlive(cindicesAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(ccountAllocMap)
	runtime.KeepAlive(cmodeAllocMap)
}

// Enable function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glEnable.xml
func Enable(cap uint32) {
	ccap, ccapAllocMap := (C.GLenum)(cap), cgoAllocsUnknown
	C.glEnable(ccap)
	runtime.KeepAlive(ccapAllocMap)
}

// EnableClientState function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glEnableClientState.xml
func EnableClientState(array uint32) {
	carray, carrayAllocMap := (C.GLenum)(array), cgoAllocsUnknown
	C.glEnableClientState(carray)
	runtime.KeepAlive(carrayAllocMap)
}

// Finish function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFinish.xml
func Finish() {
	C.glFinish()
}

// Flush function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFlush.xml
func Flush() {
	C.glFlush()
}

// Fogx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFogx.xml
func Fogx(pname uint32, param int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glFogx(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// Fogxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFogxv.xml
func Fogxv(pname uint32, param []int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&param)).Data)), cgoAllocsUnknown
	C.glFogxv(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// FrontFace function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFrontFace.xml
func FrontFace(mode uint32) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	C.glFrontFace(cmode)
	runtime.KeepAlive(cmodeAllocMap)
}

// Frustumx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glFrustumx.xml
func Frustumx(l int32, r int32, b int32, t int32, n int32, f int32) {
	cl, clAllocMap := (C.GLfixed)(l), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfixed)(r), cgoAllocsUnknown
	cb, cbAllocMap := (C.GLfixed)(b), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfixed)(t), cgoAllocsUnknown
	cn, cnAllocMap := (C.GLfixed)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfixed)(f), cgoAllocsUnknown
	C.glFrustumx(cl, cr, cb, ct, cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(cbAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(clAllocMap)
}

// GetBooleanv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetBooleanv.xml
func GetBooleanv(pname uint32, data []byte) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, cdataAllocMap := (*C.GLboolean)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetBooleanv(cpname, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// GetBufferParameteriv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetBufferParameteriv.xml
func GetBufferParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetBufferParameteriv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// GetClipPlanex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetClipPlanex.xml
func GetClipPlanex(plane uint32, equation []int32) {
	cplane, cplaneAllocMap := (C.GLenum)(plane), cgoAllocsUnknown
	cequation, cequationAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&equation)).Data)), cgoAllocsUnknown
	C.glGetClipPlanex(cplane, cequation)
	runtime.KeepAlive(cequationAllocMap)
	runtime.KeepAlive(cplaneAllocMap)
}

// GenBuffers function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGenBuffers.xml
func GenBuffers(n int32, buffers []uint32) {
	cn, cnAllocMap := (C.GLsizei)(n), cgoAllocsUnknown
	cbuffers, cbuffersAllocMap := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&buffers)).Data)), cgoAllocsUnknown
	C.glGenBuffers(cn, cbuffers)
	runtime.KeepAlive(cbuffersAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// GenTextures function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGenTextures.xml
func GenTextures(n int32, textures []uint32) {
	cn, cnAllocMap := (C.GLsizei)(n), cgoAllocsUnknown
	ctextures, ctexturesAllocMap := (*C.GLuint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&textures)).Data)), cgoAllocsUnknown
	C.glGenTextures(cn, ctextures)
	runtime.KeepAlive(ctexturesAllocMap)
	runtime.KeepAlive(cnAllocMap)
}

// GetError function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetError.xml
func GetError() uint32 {
	__ret := C.glGetError()
	__v := (uint32)(__ret)
	return __v
}

// GetFixedv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetFixedv.xml
func GetFixedv(pname uint32, params []int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetFixedv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// GetIntegerv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetIntegerv.xml
func GetIntegerv(pname uint32, data []int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cdata, cdataAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&data)).Data)), cgoAllocsUnknown
	C.glGetIntegerv(cpname, cdata)
	runtime.KeepAlive(cdataAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// GetLightxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetLightxv.xml
func GetLightxv(light uint32, pname uint32, params []int32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetLightxv(clight, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// GetMaterialxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetMaterialxv.xml
func GetMaterialxv(face uint32, pname uint32, params []int32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetMaterialxv(cface, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// GetPointerv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetPointerv.xml
func GetPointerv(pname uint32, params []unsafe.Pointer) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*unsafe.Pointer)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetPointerv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// GetString function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetString.xml
func GetString(name uint32) *byte {
	cname, cnameAllocMap := (C.GLenum)(name), cgoAllocsUnknown
	__ret := C.glGetString(cname)
	runtime.KeepAlive(cnameAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// GetTexEnviv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexEnviv.xml
func GetTexEnviv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnviv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// GetTexEnvxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexEnvxv.xml
func GetTexEnvxv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexEnvxv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// GetTexParameteriv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexParameteriv.xml
func GetTexParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameteriv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// GetTexParameterxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glGetTexParameterxv.xml
func GetTexParameterxv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glGetTexParameterxv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// Hint function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glHint.xml
func Hint(target uint32, mode uint32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	C.glHint(ctarget, cmode)
	runtime.KeepAlive(cmodeAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// IsBuffer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glIsBuffer.xml
func IsBuffer(buffer uint32) byte {
	cbuffer, cbufferAllocMap := (C.GLuint)(buffer), cgoAllocsUnknown
	__ret := C.glIsBuffer(cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
	__v := (byte)(__ret)
	return __v
}

// IsEnabled function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glIsEnabled.xml
func IsEnabled(cap uint32) byte {
	ccap, ccapAllocMap := (C.GLenum)(cap), cgoAllocsUnknown
	__ret := C.glIsEnabled(ccap)
	runtime.KeepAlive(ccapAllocMap)
	__v := (byte)(__ret)
	return __v
}

// IsTexture function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glIsTexture.xml
func IsTexture(texture uint32) byte {
	ctexture, ctextureAllocMap := (C.GLuint)(texture), cgoAllocsUnknown
	__ret := C.glIsTexture(ctexture)
	runtime.KeepAlive(ctextureAllocMap)
	__v := (byte)(__ret)
	return __v
}

// LightModelx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightModelx.xml
func LightModelx(pname uint32, param int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glLightModelx(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// LightModelxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightModelxv.xml
func LightModelxv(pname uint32, param []int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&param)).Data)), cgoAllocsUnknown
	C.glLightModelxv(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// Lightx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightx.xml
func Lightx(light uint32, pname uint32, param int32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glLightx(clight, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// Lightxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLightxv.xml
func Lightxv(light uint32, pname uint32, params []int32) {
	clight, clightAllocMap := (C.GLenum)(light), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glLightxv(clight, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(clightAllocMap)
}

// LineWidthx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLineWidthx.xml
func LineWidthx(width int32) {
	cwidth, cwidthAllocMap := (C.GLfixed)(width), cgoAllocsUnknown
	C.glLineWidthx(cwidth)
	runtime.KeepAlive(cwidthAllocMap)
}

// LoadIdentity function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLoadIdentity.xml
func LoadIdentity() {
	C.glLoadIdentity()
}

// LoadMatrixx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLoadMatrixx.xml
func LoadMatrixx(m []int32) {
	cm, cmAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glLoadMatrixx(cm)
	runtime.KeepAlive(cmAllocMap)
}

// LogicOp function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glLogicOp.xml
func LogicOp(opcode uint32) {
	copcode, copcodeAllocMap := (C.GLenum)(opcode), cgoAllocsUnknown
	C.glLogicOp(copcode)
	runtime.KeepAlive(copcodeAllocMap)
}

// Materialx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMaterialx.xml
func Materialx(face uint32, pname uint32, param int32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glMaterialx(cface, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// Materialxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMaterialxv.xml
func Materialxv(face uint32, pname uint32, param []int32) {
	cface, cfaceAllocMap := (C.GLenum)(face), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&param)).Data)), cgoAllocsUnknown
	C.glMaterialxv(cface, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(cfaceAllocMap)
}

// MatrixMode function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMatrixMode.xml
func MatrixMode(mode uint32) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	C.glMatrixMode(cmode)
	runtime.KeepAlive(cmodeAllocMap)
}

// MultMatrixx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMultMatrixx.xml
func MultMatrixx(m []int32) {
	cm, cmAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&m)).Data)), cgoAllocsUnknown
	C.glMultMatrixx(cm)
	runtime.KeepAlive(cmAllocMap)
}

// MultiTexCoord4x function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glMultiTexCoord4x.xml
func MultiTexCoord4x(texture uint32, s int32, t int32, r int32, q int32) {
	ctexture, ctextureAllocMap := (C.GLenum)(texture), cgoAllocsUnknown
	cs, csAllocMap := (C.GLfixed)(s), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfixed)(t), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfixed)(r), cgoAllocsUnknown
	cq, cqAllocMap := (C.GLfixed)(q), cgoAllocsUnknown
	C.glMultiTexCoord4x(ctexture, cs, ct, cr, cq)
	runtime.KeepAlive(cqAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(csAllocMap)
	runtime.KeepAlive(ctextureAllocMap)
}

// Normal3x function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glNormal3x.xml
func Normal3x(nx int32, ny int32, nz int32) {
	cnx, cnxAllocMap := (C.GLfixed)(nx), cgoAllocsUnknown
	cny, cnyAllocMap := (C.GLfixed)(ny), cgoAllocsUnknown
	cnz, cnzAllocMap := (C.GLfixed)(nz), cgoAllocsUnknown
	C.glNormal3x(cnx, cny, cnz)
	runtime.KeepAlive(cnzAllocMap)
	runtime.KeepAlive(cnyAllocMap)
	runtime.KeepAlive(cnxAllocMap)
}

// NormalPointer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glNormalPointer.xml
func NormalPointer(kind uint32, stride int32, pointer unsafe.Pointer) {
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, cstrideAllocMap := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, cpointerAllocMap := pointer, cgoAllocsUnknown
	C.glNormalPointer(ckind, cstride, cpointer)
	runtime.KeepAlive(cpointerAllocMap)
	runtime.KeepAlive(cstrideAllocMap)
	runtime.KeepAlive(ckindAllocMap)
}

// Orthox function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glOrthox.xml
func Orthox(l int32, r int32, b int32, t int32, n int32, f int32) {
	cl, clAllocMap := (C.GLfixed)(l), cgoAllocsUnknown
	cr, crAllocMap := (C.GLfixed)(r), cgoAllocsUnknown
	cb, cbAllocMap := (C.GLfixed)(b), cgoAllocsUnknown
	ct, ctAllocMap := (C.GLfixed)(t), cgoAllocsUnknown
	cn, cnAllocMap := (C.GLfixed)(n), cgoAllocsUnknown
	cf, cfAllocMap := (C.GLfixed)(f), cgoAllocsUnknown
	C.glOrthox(cl, cr, cb, ct, cn, cf)
	runtime.KeepAlive(cfAllocMap)
	runtime.KeepAlive(cnAllocMap)
	runtime.KeepAlive(ctAllocMap)
	runtime.KeepAlive(cbAllocMap)
	runtime.KeepAlive(crAllocMap)
	runtime.KeepAlive(clAllocMap)
}

// PixelStorei function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPixelStorei.xml
func PixelStorei(pname uint32, param int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLint)(param), cgoAllocsUnknown
	C.glPixelStorei(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// PointParameterx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointParameterx.xml
func PointParameterx(pname uint32, param int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glPointParameterx(cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// PointParameterxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointParameterxv.xml
func PointParameterxv(pname uint32, params []int32) {
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glPointParameterxv(cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
}

// PointSizex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointSizex.xml
func PointSizex(size int32) {
	csize, csizeAllocMap := (C.GLfixed)(size), cgoAllocsUnknown
	C.glPointSizex(csize)
	runtime.KeepAlive(csizeAllocMap)
}

// PolygonOffsetx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPolygonOffsetx.xml
func PolygonOffsetx(factor int32, units int32) {
	cfactor, cfactorAllocMap := (C.GLfixed)(factor), cgoAllocsUnknown
	cunits, cunitsAllocMap := (C.GLfixed)(units), cgoAllocsUnknown
	C.glPolygonOffsetx(cfactor, cunits)
	runtime.KeepAlive(cunitsAllocMap)
	runtime.KeepAlive(cfactorAllocMap)
}

// PopMatrix function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPopMatrix.xml
func PopMatrix() {
	C.glPopMatrix()
}

// PushMatrix function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPushMatrix.xml
func PushMatrix() {
	C.glPushMatrix()
}

// ReadPixels function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glReadPixels.xml
func ReadPixels(x int32, y int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	cx, cxAllocMap := (C.GLint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLint)(y), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, cformatAllocMap := (C.GLenum)(format), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, cpixelsAllocMap := pixels, cgoAllocsUnknown
	C.glReadPixels(cx, cy, cwidth, cheight, cformat, ckind, cpixels)
	runtime.KeepAlive(cpixelsAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(cformatAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// Rotatex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glRotatex.xml
func Rotatex(angle int32, x int32, y int32, z int32) {
	cangle, cangleAllocMap := (C.GLfixed)(angle), cgoAllocsUnknown
	cx, cxAllocMap := (C.GLfixed)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfixed)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfixed)(z), cgoAllocsUnknown
	C.glRotatex(cangle, cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
	runtime.KeepAlive(cangleAllocMap)
}

// SampleCoverage function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glSampleCoverage.xml
func SampleCoverage(value float32, invert byte) {
	cvalue, cvalueAllocMap := (C.GLfloat)(value), cgoAllocsUnknown
	cinvert, cinvertAllocMap := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoverage(cvalue, cinvert)
	runtime.KeepAlive(cinvertAllocMap)
	runtime.KeepAlive(cvalueAllocMap)
}

// SampleCoveragex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glSampleCoveragex.xml
func SampleCoveragex(value int32, invert byte) {
	cvalue, cvalueAllocMap := (C.GLclampx)(value), cgoAllocsUnknown
	cinvert, cinvertAllocMap := (C.GLboolean)(invert), cgoAllocsUnknown
	C.glSampleCoveragex(cvalue, cinvert)
	runtime.KeepAlive(cinvertAllocMap)
	runtime.KeepAlive(cvalueAllocMap)
}

// Scalex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glScalex.xml
func Scalex(x int32, y int32, z int32) {
	cx, cxAllocMap := (C.GLfixed)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfixed)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfixed)(z), cgoAllocsUnknown
	C.glScalex(cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// Scissor function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glScissor.xml
func Scissor(x int32, y int32, width int32, height int32) {
	cx, cxAllocMap := (C.GLint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLint)(y), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	C.glScissor(cx, cy, cwidth, cheight)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// ShadeModel function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glShadeModel.xml
func ShadeModel(mode uint32) {
	cmode, cmodeAllocMap := (C.GLenum)(mode), cgoAllocsUnknown
	C.glShadeModel(cmode)
	runtime.KeepAlive(cmodeAllocMap)
}

// StencilFunc function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glStencilFunc.xml
func StencilFunc(_func uint32, ref int32, mask uint32) {
	c_func, c_funcAllocMap := (C.GLenum)(_func), cgoAllocsUnknown
	cref, crefAllocMap := (C.GLint)(ref), cgoAllocsUnknown
	cmask, cmaskAllocMap := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilFunc(c_func, cref, cmask)
	runtime.KeepAlive(cmaskAllocMap)
	runtime.KeepAlive(crefAllocMap)
	runtime.KeepAlive(c_funcAllocMap)
}

// StencilMask function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glStencilMask.xml
func StencilMask(mask uint32) {
	cmask, cmaskAllocMap := (C.GLuint)(mask), cgoAllocsUnknown
	C.glStencilMask(cmask)
	runtime.KeepAlive(cmaskAllocMap)
}

// StencilOp function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glStencilOp.xml
func StencilOp(fail uint32, zfail uint32, zpass uint32) {
	cfail, cfailAllocMap := (C.GLenum)(fail), cgoAllocsUnknown
	czfail, czfailAllocMap := (C.GLenum)(zfail), cgoAllocsUnknown
	czpass, czpassAllocMap := (C.GLenum)(zpass), cgoAllocsUnknown
	C.glStencilOp(cfail, czfail, czpass)
	runtime.KeepAlive(czpassAllocMap)
	runtime.KeepAlive(czfailAllocMap)
	runtime.KeepAlive(cfailAllocMap)
}

// TexCoordPointer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexCoordPointer.xml
func TexCoordPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, csizeAllocMap := (C.GLint)(size), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, cstrideAllocMap := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, cpointerAllocMap := pointer, cgoAllocsUnknown
	C.glTexCoordPointer(csize, ckind, cstride, cpointer)
	runtime.KeepAlive(cpointerAllocMap)
	runtime.KeepAlive(cstrideAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(csizeAllocMap)
}

// TexEnvi function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnvi.xml
func TexEnvi(target uint32, pname uint32, param int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLint)(param), cgoAllocsUnknown
	C.glTexEnvi(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexEnvx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnvx.xml
func TexEnvx(target uint32, pname uint32, param int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glTexEnvx(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexEnviv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnviv.xml
func TexEnviv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnviv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexEnvxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexEnvxv.xml
func TexEnvxv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexEnvxv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexImage2D.xml
func TexImage2D(target uint32, level int32, internalformat int32, width int32, height int32, border int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cinternalformat, cinternalformatAllocMap := (C.GLint)(internalformat), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cborder, cborderAllocMap := (C.GLint)(border), cgoAllocsUnknown
	cformat, cformatAllocMap := (C.GLenum)(format), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, cpixelsAllocMap := pixels, cgoAllocsUnknown
	C.glTexImage2D(ctarget, clevel, cinternalformat, cwidth, cheight, cborder, cformat, ckind, cpixels)
	runtime.KeepAlive(cpixelsAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(cformatAllocMap)
	runtime.KeepAlive(cborderAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cinternalformatAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameteri function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameteri.xml
func TexParameteri(target uint32, pname uint32, param int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLint)(param), cgoAllocsUnknown
	C.glTexParameteri(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameterx function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameterx.xml
func TexParameterx(target uint32, pname uint32, param int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparam, cparamAllocMap := (C.GLfixed)(param), cgoAllocsUnknown
	C.glTexParameterx(ctarget, cpname, cparam)
	runtime.KeepAlive(cparamAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameteriv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameteriv.xml
func TexParameteriv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameteriv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexParameterxv function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexParameterxv.xml
func TexParameterxv(target uint32, pname uint32, params []int32) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	cpname, cpnameAllocMap := (C.GLenum)(pname), cgoAllocsUnknown
	cparams, cparamsAllocMap := (*C.GLfixed)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&params)).Data)), cgoAllocsUnknown
	C.glTexParameterxv(ctarget, cpname, cparams)
	runtime.KeepAlive(cparamsAllocMap)
	runtime.KeepAlive(cpnameAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// TexSubImage2D function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTexSubImage2D.xml
func TexSubImage2D(target uint32, level int32, xoffset int32, yoffset int32, width int32, height int32, format uint32, kind uint32, pixels unsafe.Pointer) {
	ctarget, ctargetAllocMap := (C.GLenum)(target), cgoAllocsUnknown
	clevel, clevelAllocMap := (C.GLint)(level), cgoAllocsUnknown
	cxoffset, cxoffsetAllocMap := (C.GLint)(xoffset), cgoAllocsUnknown
	cyoffset, cyoffsetAllocMap := (C.GLint)(yoffset), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	cformat, cformatAllocMap := (C.GLenum)(format), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cpixels, cpixelsAllocMap := pixels, cgoAllocsUnknown
	C.glTexSubImage2D(ctarget, clevel, cxoffset, cyoffset, cwidth, cheight, cformat, ckind, cpixels)
	runtime.KeepAlive(cpixelsAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(cformatAllocMap)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyoffsetAllocMap)
	runtime.KeepAlive(cxoffsetAllocMap)
	runtime.KeepAlive(clevelAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
}

// Translatex function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glTranslatex.xml
func Translatex(x int32, y int32, z int32) {
	cx, cxAllocMap := (C.GLfixed)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLfixed)(y), cgoAllocsUnknown
	cz, czAllocMap := (C.GLfixed)(z), cgoAllocsUnknown
	C.glTranslatex(cx, cy, cz)
	runtime.KeepAlive(czAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// VertexPointer function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glVertexPointer.xml
func VertexPointer(size int32, kind uint32, stride int32, pointer unsafe.Pointer) {
	csize, csizeAllocMap := (C.GLint)(size), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, cstrideAllocMap := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, cpointerAllocMap := pointer, cgoAllocsUnknown
	C.glVertexPointer(csize, ckind, cstride, cpointer)
	runtime.KeepAlive(cpointerAllocMap)
	runtime.KeepAlive(cstrideAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(csizeAllocMap)
}

// Viewport function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glViewport.xml
func Viewport(x int32, y int32, width int32, height int32) {
	cx, cxAllocMap := (C.GLint)(x), cgoAllocsUnknown
	cy, cyAllocMap := (C.GLint)(y), cgoAllocsUnknown
	cwidth, cwidthAllocMap := (C.GLsizei)(width), cgoAllocsUnknown
	cheight, cheightAllocMap := (C.GLsizei)(height), cgoAllocsUnknown
	C.glViewport(cx, cy, cwidth, cheight)
	runtime.KeepAlive(cheightAllocMap)
	runtime.KeepAlive(cwidthAllocMap)
	runtime.KeepAlive(cyAllocMap)
	runtime.KeepAlive(cxAllocMap)
}

// PointSizePointerOES function as declared in https://www.khronos.org/opengles/sdk/1.1/docs/man/glPointSizePointerOES.xml
func PointSizePointerOES(kind uint32, stride int32, pointer unsafe.Pointer) {
	ckind, ckindAllocMap := (C.GLenum)(kind), cgoAllocsUnknown
	cstride, cstrideAllocMap := (C.GLsizei)(stride), cgoAllocsUnknown
	cpointer, cpointerAllocMap := pointer, cgoAllocsUnknown
	C.glPointSizePointerOES(ckind, cstride, cpointer)
	runtime.KeepAlive(cpointerAllocMap)
	runtime.KeepAlive(cstrideAllocMap)
	runtime.KeepAlive(ckindAllocMap)
}
