// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gles

/*
#cgo LDFLAGS: -lGLESv1_CM
#include <GLES/gl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Void type as declared in gl.h:53
type Void [0]byte

// Char type as declared in gl.h:54
type Char byte

// Enum type as declared in gl.h:55
type Enum uint32

// Float type as declared in gl.h:57
type Float float32

// Fixed type as declared in gl.h:58
type Fixed int32

// Uint type as declared in gl.h:59
type Uint uint32

// Sizeiptr type as declared in gl.h:60
type Sizeiptr int32

// Intptr type as declared in gl.h:61
type Intptr int32

// Bitfield type as declared in gl.h:62
type Bitfield uint32

// Int type as declared in gl.h:63
type Int int32

// Ushort type as declared in gl.h:64
type Ushort uint16

// Short type as declared in gl.h:65
type Short int16

// Byte type as declared in gl.h:66
type Byte int8

// Ubyte type as declared in gl.h:67
type Ubyte byte

// Boolean type as declared in gl.h:68
type Boolean byte

// Sizei type as declared in gl.h:69
type Sizei int32

// Clampf type as declared in gl.h:70
type Clampf float32

// Clampx type as declared in gl.h:71
type Clampx int32
