// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package egl

/*
#cgo LDFLAGS: -lEGL
#include <EGL/egl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Version10 as defined in egl.h:53
	Version10 = 1
	// AlphaSize as defined in egl.h:62
	AlphaSize = 0x3021
	// BadAccess as defined in egl.h:63
	BadAccess = 0x3002
	// BadAlloc as defined in egl.h:64
	BadAlloc = 0x3003
	// BadAttribute as defined in egl.h:65
	BadAttribute = 0x3004
	// BadConfig as defined in egl.h:66
	BadConfig = 0x3005
	// BadContext as defined in egl.h:67
	BadContext = 0x3006
	// BadCurrentSurface as defined in egl.h:68
	BadCurrentSurface = 0x3007
	// BadDisplay as defined in egl.h:69
	BadDisplay = 0x3008
	// BadMatch as defined in egl.h:70
	BadMatch = 0x3009
	// BadNativePixmap as defined in egl.h:71
	BadNativePixmap = 0x300A
	// BadNativeWindow as defined in egl.h:72
	BadNativeWindow = 0x300B
	// BadParameter as defined in egl.h:73
	BadParameter = 0x300C
	// BadSurface as defined in egl.h:74
	BadSurface = 0x300D
	// BlueSize as defined in egl.h:75
	BlueSize = 0x3022
	// BufferSize as defined in egl.h:76
	BufferSize = 0x3020
	// ConfigCaveat as defined in egl.h:77
	ConfigCaveat = 0x3027
	// ConfigId as defined in egl.h:78
	ConfigId = 0x3028
	// CoreNativeEngine as defined in egl.h:79
	CoreNativeEngine = 0x305B
	// DepthSize as defined in egl.h:80
	DepthSize = 0x3025
	// DontCare as defined in egl.h:81
	DontCare = 18446744073709551615
	// Draw as defined in egl.h:82
	Draw = 0x3059
	// Extensions as defined in egl.h:83
	Extensions = 0x3055
	// False as defined in egl.h:84
	False = 0
	// GreenSize as defined in egl.h:85
	GreenSize = 0x3023
	// Height as defined in egl.h:86
	Height = 0x3056
	// LargestPbuffer as defined in egl.h:87
	LargestPbuffer = 0x3058
	// Level as defined in egl.h:88
	Level = 0x3029
	// MaxPbufferHeight as defined in egl.h:89
	MaxPbufferHeight = 0x302A
	// MaxPbufferPixels as defined in egl.h:90
	MaxPbufferPixels = 0x302B
	// MaxPbufferWidth as defined in egl.h:91
	MaxPbufferWidth = 0x302C
	// NativeRenderable as defined in egl.h:92
	NativeRenderable = 0x302D
	// NativeVisualId as defined in egl.h:93
	NativeVisualId = 0x302E
	// NativeVisualType as defined in egl.h:94
	NativeVisualType = 0x302F
	// None as defined in egl.h:95
	None = 0x3038
	// NonConformantConfig as defined in egl.h:96
	NonConformantConfig = 0x3051
	// NotInitialized as defined in egl.h:97
	NotInitialized = 0x3001
	// PbufferBit as defined in egl.h:101
	PbufferBit = 0x0001
	// PixmapBit as defined in egl.h:102
	PixmapBit = 0x0002
	// Read as defined in egl.h:103
	Read = 0x305A
	// RedSize as defined in egl.h:104
	RedSize = 0x3024
	// Samples as defined in egl.h:105
	Samples = 0x3031
	// SampleBuffers as defined in egl.h:106
	SampleBuffers = 0x3032
	// SlowConfig as defined in egl.h:107
	SlowConfig = 0x3050
	// StencilSize as defined in egl.h:108
	StencilSize = 0x3026
	// Success as defined in egl.h:109
	Success = 0x3000
	// SurfaceType as defined in egl.h:110
	SurfaceType = 0x3033
	// TransparentBlueValue as defined in egl.h:111
	TransparentBlueValue = 0x3035
	// TransparentGreenValue as defined in egl.h:112
	TransparentGreenValue = 0x3036
	// TransparentRedValue as defined in egl.h:113
	TransparentRedValue = 0x3037
	// TransparentRgb as defined in egl.h:114
	TransparentRgb = 0x3052
	// TransparentType as defined in egl.h:115
	TransparentType = 0x3034
	// True as defined in egl.h:116
	True = 1
	// Vendor as defined in egl.h:117
	Vendor = 0x3053
	// Version as defined in egl.h:118
	Version = 0x3054
	// Width as defined in egl.h:119
	Width = 0x3057
	// WindowBit as defined in egl.h:120
	WindowBit = 0x0004
	// Version11 as defined in egl.h:148
	Version11 = 1
	// BackBuffer as defined in egl.h:149
	BackBuffer = 0x3084
	// BindToTextureRgb as defined in egl.h:150
	BindToTextureRgb = 0x3039
	// BindToTextureRgba as defined in egl.h:151
	BindToTextureRgba = 0x303A
	// ContextLost as defined in egl.h:152
	ContextLost = 0x300E
	// MinSwapInterval as defined in egl.h:153
	MinSwapInterval = 0x303B
	// MaxSwapInterval as defined in egl.h:154
	MaxSwapInterval = 0x303C
	// MipmapTexture as defined in egl.h:155
	MipmapTexture = 0x3082
	// MipmapLevel as defined in egl.h:156
	MipmapLevel = 0x3083
	// NoTexture as defined in egl.h:157
	NoTexture = 0x305C
	// Texture2d as defined in egl.h:158
	Texture2d = 0x305F
	// TextureFormat as defined in egl.h:159
	TextureFormat = 0x3080
	// TextureRgb as defined in egl.h:160
	TextureRgb = 0x305D
	// TextureRgba as defined in egl.h:161
	TextureRgba = 0x305E
	// TextureTarget as defined in egl.h:162
	TextureTarget = 0x3081
	// Version12 as defined in egl.h:170
	Version12 = 1
	// AlphaFormat as defined in egl.h:173
	AlphaFormat = 0x3088
	// AlphaFormatNonpre as defined in egl.h:174
	AlphaFormatNonpre = 0x308B
	// AlphaFormatPre as defined in egl.h:175
	AlphaFormatPre = 0x308C
	// AlphaMaskSize as defined in egl.h:176
	AlphaMaskSize = 0x303E
	// BufferPreserved as defined in egl.h:177
	BufferPreserved = 0x3094
	// BufferDestroyed as defined in egl.h:178
	BufferDestroyed = 0x3095
	// ClientApis as defined in egl.h:179
	ClientApis = 0x308D
	// Colorspace as defined in egl.h:180
	Colorspace = 0x3087
	// ColorspaceSrgb as defined in egl.h:181
	ColorspaceSrgb = 0x3089
	// ColorspaceLinear as defined in egl.h:182
	ColorspaceLinear = 0x308A
	// ColorBufferType as defined in egl.h:183
	ColorBufferType = 0x303F
	// ContextClientType as defined in egl.h:184
	ContextClientType = 0x3097
	// DisplayScaling as defined in egl.h:185
	DisplayScaling = 10000
	// HorizontalResolution as defined in egl.h:186
	HorizontalResolution = 0x3090
	// LuminanceBuffer as defined in egl.h:187
	LuminanceBuffer = 0x308F
	// LuminanceSize as defined in egl.h:188
	LuminanceSize = 0x303D
	// OpenglEsBit as defined in egl.h:189
	OpenglEsBit = 0x0001
	// OpenvgBit as defined in egl.h:190
	OpenvgBit = 0x0002
	// OpenglEsApi as defined in egl.h:191
	OpenglEsApi = 0x30A0
	// OpenvgApi as defined in egl.h:192
	OpenvgApi = 0x30A1
	// OpenvgImage as defined in egl.h:193
	OpenvgImage = 0x3096
	// PixelAspectRatio as defined in egl.h:194
	PixelAspectRatio = 0x3092
	// RenderableType as defined in egl.h:195
	RenderableType = 0x3040
	// RenderBuffer as defined in egl.h:196
	RenderBuffer = 0x3086
	// RgbBuffer as defined in egl.h:197
	RgbBuffer = 0x308E
	// SingleBuffer as defined in egl.h:198
	SingleBuffer = 0x3085
	// SwapBehavior as defined in egl.h:199
	SwapBehavior = 0x3093
	// Unknown as defined in egl.h:200
	Unknown = 18446744073709551615
	// VerticalResolution as defined in egl.h:201
	VerticalResolution = 0x3091
	// Version13 as defined in egl.h:210
	Version13 = 1
	// Conformant as defined in egl.h:211
	Conformant = 0x3042
	// ContextClientVersion as defined in egl.h:212
	ContextClientVersion = 0x3098
	// MatchNativePixmap as defined in egl.h:213
	MatchNativePixmap = 0x3041
	// OpenglEs2Bit as defined in egl.h:214
	OpenglEs2Bit = 0x0004
	// VgAlphaFormat as defined in egl.h:215
	VgAlphaFormat = 0x3088
	// VgAlphaFormatNonpre as defined in egl.h:216
	VgAlphaFormatNonpre = 0x308B
	// VgAlphaFormatPre as defined in egl.h:217
	VgAlphaFormatPre = 0x308C
	// VgAlphaFormatPreBit as defined in egl.h:218
	VgAlphaFormatPreBit = 0x0040
	// VgColorspace as defined in egl.h:219
	VgColorspace = 0x3087
	// VgColorspaceSrgb as defined in egl.h:220
	VgColorspaceSrgb = 0x3089
	// VgColorspaceLinear as defined in egl.h:221
	VgColorspaceLinear = 0x308A
	// VgColorspaceLinearBit as defined in egl.h:222
	VgColorspaceLinearBit = 0x0020
	// Version14 as defined in egl.h:226
	Version14 = 1
	// MultisampleResolveBoxBit as defined in egl.h:228
	MultisampleResolveBoxBit = 0x0200
	// MultisampleResolve as defined in egl.h:229
	MultisampleResolve = 0x3099
	// MultisampleResolveDefault as defined in egl.h:230
	MultisampleResolveDefault = 0x309A
	// MultisampleResolveBox as defined in egl.h:231
	MultisampleResolveBox = 0x309B
	// OpenglApi as defined in egl.h:232
	OpenglApi = 0x30A2
	// OpenglBit as defined in egl.h:233
	OpenglBit = 0x0008
	// SwapBehaviorPreservedBit as defined in egl.h:234
	SwapBehaviorPreservedBit = 0x0400
	// Version15 as defined in egl.h:239
	Version15 = 1
	// ContextMajorVersion as defined in egl.h:244
	ContextMajorVersion = 0x3098
	// ContextMinorVersion as defined in egl.h:245
	ContextMinorVersion = 0x30FB
	// ContextOpenglProfileMask as defined in egl.h:246
	ContextOpenglProfileMask = 0x30FD
	// ContextOpenglResetNotificationStrategy as defined in egl.h:247
	ContextOpenglResetNotificationStrategy = 0x31BD
	// NoResetNotification as defined in egl.h:248
	NoResetNotification = 0x31BE
	// LoseContextOnReset as defined in egl.h:249
	LoseContextOnReset = 0x31BF
	// ContextOpenglCoreProfileBit as defined in egl.h:250
	ContextOpenglCoreProfileBit = 0x00000001
	// ContextOpenglCompatibilityProfileBit as defined in egl.h:251
	ContextOpenglCompatibilityProfileBit = 0x00000002
	// ContextOpenglDebug as defined in egl.h:252
	ContextOpenglDebug = 0x31B0
	// ContextOpenglForwardCompatible as defined in egl.h:253
	ContextOpenglForwardCompatible = 0x31B1
	// ContextOpenglRobustAccess as defined in egl.h:254
	ContextOpenglRobustAccess = 0x31B2
	// OpenglEs3Bit as defined in egl.h:255
	OpenglEs3Bit = 0x00000040
	// ClEventHandle as defined in egl.h:256
	ClEventHandle = 0x309C
	// SyncClEvent as defined in egl.h:257
	SyncClEvent = 0x30FE
	// SyncClEventComplete as defined in egl.h:258
	SyncClEventComplete = 0x30FF
	// SyncPriorCommandsComplete as defined in egl.h:259
	SyncPriorCommandsComplete = 0x30F0
	// SyncType as defined in egl.h:260
	SyncType = 0x30F7
	// SyncStatus as defined in egl.h:261
	SyncStatus = 0x30F1
	// SyncCondition as defined in egl.h:262
	SyncCondition = 0x30F8
	// Signaled as defined in egl.h:263
	Signaled = 0x30F2
	// Unsignaled as defined in egl.h:264
	Unsignaled = 0x30F3
	// SyncFlushCommandsBit as defined in egl.h:265
	SyncFlushCommandsBit = 0x0001
	// Forever as defined in egl.h:266
	Forever = uint64(0xFFFFFFFFFFFFFFFF)
	// TimeoutExpired as defined in egl.h:267
	TimeoutExpired = 0x30F5
	// ConditionSatisfied as defined in egl.h:268
	ConditionSatisfied = 0x30F6
	// NoSync as defined in egl.h:269
	NoSync = 0
	// SyncFence as defined in egl.h:270
	SyncFence = 0x30F9
	// GlColorspace as defined in egl.h:271
	GlColorspace = 0x309D
	// GlColorspaceSrgb as defined in egl.h:272
	GlColorspaceSrgb = 0x3089
	// GlColorspaceLinear as defined in egl.h:273
	GlColorspaceLinear = 0x308A
	// GlRenderbuffer as defined in egl.h:274
	GlRenderbuffer = 0x30B9
	// GlTexture2d as defined in egl.h:275
	GlTexture2d = 0x30B1
	// GlTextureLevel as defined in egl.h:276
	GlTextureLevel = 0x30BC
	// GlTexture3d as defined in egl.h:277
	GlTexture3d = 0x30B2
	// GlTextureZoffset as defined in egl.h:278
	GlTextureZoffset = 0x30BD
	// GlTextureCubeMapPositiveX as defined in egl.h:279
	GlTextureCubeMapPositiveX = 0x30B3
	// GlTextureCubeMapNegativeX as defined in egl.h:280
	GlTextureCubeMapNegativeX = 0x30B4
	// GlTextureCubeMapPositiveY as defined in egl.h:281
	GlTextureCubeMapPositiveY = 0x30B5
	// GlTextureCubeMapNegativeY as defined in egl.h:282
	GlTextureCubeMapNegativeY = 0x30B6
	// GlTextureCubeMapPositiveZ as defined in egl.h:283
	GlTextureCubeMapPositiveZ = 0x30B7
	// GlTextureCubeMapNegativeZ as defined in egl.h:284
	GlTextureCubeMapNegativeZ = 0x30B8
	// ImagePreserved as defined in egl.h:285
	ImagePreserved = 0x30D2
	// NoImage as defined in egl.h:286
	NoImage = 0
)
