// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package egl

/*
#cgo LDFLAGS: -lEGL
#include <EGL/egl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// ChooseConfig function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglChooseConfig.xhtml
func ChooseConfig(dpy Display, attribList []int32, configs []Config, configSize int32, numConfig *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	cconfigs, cconfigsAllocMap := (*C.EGLConfig)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&configs)).Data)), cgoAllocsUnknown
	cconfigSize, cconfigSizeAllocMap := (C.EGLint)(configSize), cgoAllocsUnknown
	cnumConfig, cnumConfigAllocMap := (*C.EGLint)(unsafe.Pointer(numConfig)), cgoAllocsUnknown
	__ret := C.eglChooseConfig(cdpy, cattribList, cconfigs, cconfigSize, cnumConfig)
	runtime.KeepAlive(cnumConfigAllocMap)
	runtime.KeepAlive(cconfigSizeAllocMap)
	runtime.KeepAlive(cconfigsAllocMap)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// CopyBuffers function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCopyBuffers.xhtml
func CopyBuffers(dpy Display, surface Surface, target NativePixmapType) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	ctarget, ctargetAllocMap := *(*C.EGLNativePixmapType)(unsafe.Pointer(&target)), cgoAllocsUnknown
	__ret := C.eglCopyBuffers(cdpy, csurface, ctarget)
	runtime.KeepAlive(ctargetAllocMap)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// CreateContext function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreateContext.xhtml
func CreateContext(dpy Display, config Config, shareContext Context, attribList []int32) Context {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cshareContext, cshareContextAllocMap := (C.EGLContext)(unsafe.Pointer(shareContext)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreateContext(cdpy, cconfig, cshareContext, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cshareContextAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Context)(unsafe.Pointer(&__ret))
	return __v
}

// CreatePbufferSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreatePbufferSurface.xhtml
func CreatePbufferSurface(dpy Display, config Config, attribList []int32) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreatePbufferSurface(cdpy, cconfig, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// CreatePixmapSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreatePixmapSurface.xhtml
func CreatePixmapSurface(dpy Display, config Config, pixmap NativePixmapType, attribList []int32) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cpixmap, cpixmapAllocMap := *(*C.EGLNativePixmapType)(unsafe.Pointer(&pixmap)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreatePixmapSurface(cdpy, cconfig, cpixmap, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cpixmapAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// CreateWindowSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreateWindowSurface.xhtml
func CreateWindowSurface(dpy Display, config Config, win NativeWindowType, attribList []int32) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cwin, cwinAllocMap := *(*C.EGLNativeWindowType)(unsafe.Pointer(&win)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreateWindowSurface(cdpy, cconfig, cwin, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cwinAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// DestroyContext function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglDestroyContext.xhtml
func DestroyContext(dpy Display, ctx Context) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cctx, cctxAllocMap := (C.EGLContext)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.eglDestroyContext(cdpy, cctx)
	runtime.KeepAlive(cctxAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// DestroySurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglDestroySurface.xhtml
func DestroySurface(dpy Display, surface Surface) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	__ret := C.eglDestroySurface(cdpy, csurface)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// GetConfigAttrib function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetConfigAttrib.xhtml
func GetConfigAttrib(dpy Display, config Config, attribute int32, value *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cattribute, cattributeAllocMap := (C.EGLint)(attribute), cgoAllocsUnknown
	cvalue, cvalueAllocMap := (*C.EGLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	__ret := C.eglGetConfigAttrib(cdpy, cconfig, cattribute, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cattributeAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// GetConfigs function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetConfigs.xhtml
func GetConfigs(dpy Display, configs []Config, configSize int32, numConfig *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfigs, cconfigsAllocMap := (*C.EGLConfig)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&configs)).Data)), cgoAllocsUnknown
	cconfigSize, cconfigSizeAllocMap := (C.EGLint)(configSize), cgoAllocsUnknown
	cnumConfig, cnumConfigAllocMap := (*C.EGLint)(unsafe.Pointer(numConfig)), cgoAllocsUnknown
	__ret := C.eglGetConfigs(cdpy, cconfigs, cconfigSize, cnumConfig)
	runtime.KeepAlive(cnumConfigAllocMap)
	runtime.KeepAlive(cconfigSizeAllocMap)
	runtime.KeepAlive(cconfigsAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// GetCurrentDisplay function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetCurrentDisplay.xhtml
func GetCurrentDisplay() Display {
	__ret := C.eglGetCurrentDisplay()
	__v := *(*Display)(unsafe.Pointer(&__ret))
	return __v
}

// GetCurrentSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetCurrentSurface.xhtml
func GetCurrentSurface(readdraw int32) Surface {
	creaddraw, creaddrawAllocMap := (C.EGLint)(readdraw), cgoAllocsUnknown
	__ret := C.eglGetCurrentSurface(creaddraw)
	runtime.KeepAlive(creaddrawAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// GetDisplay function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetDisplay.xhtml
func GetDisplay(displayId NativeDisplayType) Display {
	cdisplayId, cdisplayIdAllocMap := (C.EGLNativeDisplayType)(unsafe.Pointer(displayId)), cgoAllocsUnknown
	__ret := C.eglGetDisplay(cdisplayId)
	runtime.KeepAlive(cdisplayIdAllocMap)
	__v := *(*Display)(unsafe.Pointer(&__ret))
	return __v
}

// GetError function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetError.xhtml
func GetError() int32 {
	__ret := C.eglGetError()
	__v := (int32)(__ret)
	return __v
}

// Initialize function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglInitialize.xhtml
func Initialize(dpy Display, major *int32, minor *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cmajor, cmajorAllocMap := (*C.EGLint)(unsafe.Pointer(major)), cgoAllocsUnknown
	cminor, cminorAllocMap := (*C.EGLint)(unsafe.Pointer(minor)), cgoAllocsUnknown
	__ret := C.eglInitialize(cdpy, cmajor, cminor)
	runtime.KeepAlive(cminorAllocMap)
	runtime.KeepAlive(cmajorAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// MakeCurrent function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglMakeCurrent.xhtml
func MakeCurrent(dpy Display, draw Surface, read Surface, ctx Context) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cdraw, cdrawAllocMap := (C.EGLSurface)(unsafe.Pointer(draw)), cgoAllocsUnknown
	cread, creadAllocMap := (C.EGLSurface)(unsafe.Pointer(read)), cgoAllocsUnknown
	cctx, cctxAllocMap := (C.EGLContext)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	__ret := C.eglMakeCurrent(cdpy, cdraw, cread, cctx)
	runtime.KeepAlive(cctxAllocMap)
	runtime.KeepAlive(creadAllocMap)
	runtime.KeepAlive(cdrawAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// QueryContext function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglQueryContext.xhtml
func QueryContext(dpy Display, ctx Context, attribute int32, value *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cctx, cctxAllocMap := (C.EGLContext)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	cattribute, cattributeAllocMap := (C.EGLint)(attribute), cgoAllocsUnknown
	cvalue, cvalueAllocMap := (*C.EGLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	__ret := C.eglQueryContext(cdpy, cctx, cattribute, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cattributeAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// QueryString function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglQueryString.xhtml
func QueryString(dpy Display, name int32) string {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cname, cnameAllocMap := (C.EGLint)(name), cgoAllocsUnknown
	__ret := C.eglQueryString(cdpy, cname)
	runtime.KeepAlive(cnameAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := packPCharString(__ret)
	return __v
}

// QuerySurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglQuerySurface.xhtml
func QuerySurface(dpy Display, surface Surface, attribute int32, value *int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	cattribute, cattributeAllocMap := (C.EGLint)(attribute), cgoAllocsUnknown
	cvalue, cvalueAllocMap := (*C.EGLint)(unsafe.Pointer(value)), cgoAllocsUnknown
	__ret := C.eglQuerySurface(cdpy, csurface, cattribute, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cattributeAllocMap)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// SwapBuffers function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglSwapBuffers.xhtml
func SwapBuffers(dpy Display, surface Surface) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	__ret := C.eglSwapBuffers(cdpy, csurface)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// Terminate function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglTerminate.xhtml
func Terminate(dpy Display) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	__ret := C.eglTerminate(cdpy)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// WaitGL function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglWaitGL.xhtml
func WaitGL() Boolean {
	__ret := C.eglWaitGL()
	__v := (Boolean)(__ret)
	return __v
}

// WaitNative function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglWaitNative.xhtml
func WaitNative(engine int32) Boolean {
	cengine, cengineAllocMap := (C.EGLint)(engine), cgoAllocsUnknown
	__ret := C.eglWaitNative(cengine)
	runtime.KeepAlive(cengineAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// BindTexImage function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglBindTexImage.xhtml
func BindTexImage(dpy Display, surface Surface, buffer int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (C.EGLint)(buffer), cgoAllocsUnknown
	__ret := C.eglBindTexImage(cdpy, csurface, cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// ReleaseTexImage function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglReleaseTexImage.xhtml
func ReleaseTexImage(dpy Display, surface Surface, buffer int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (C.EGLint)(buffer), cgoAllocsUnknown
	__ret := C.eglReleaseTexImage(cdpy, csurface, cbuffer)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// SurfaceAttrib function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglSurfaceAttrib.xhtml
func SurfaceAttrib(dpy Display, surface Surface, attribute int32, value int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csurface, csurfaceAllocMap := (C.EGLSurface)(unsafe.Pointer(surface)), cgoAllocsUnknown
	cattribute, cattributeAllocMap := (C.EGLint)(attribute), cgoAllocsUnknown
	cvalue, cvalueAllocMap := (C.EGLint)(value), cgoAllocsUnknown
	__ret := C.eglSurfaceAttrib(cdpy, csurface, cattribute, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cattributeAllocMap)
	runtime.KeepAlive(csurfaceAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// SwapInterval function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglSwapInterval.xhtml
func SwapInterval(dpy Display, interval int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cinterval, cintervalAllocMap := (C.EGLint)(interval), cgoAllocsUnknown
	__ret := C.eglSwapInterval(cdpy, cinterval)
	runtime.KeepAlive(cintervalAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// BindAPI function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglBindAPI.xhtml
func BindAPI(api Enum) Boolean {
	capi, capiAllocMap := (C.EGLenum)(api), cgoAllocsUnknown
	__ret := C.eglBindAPI(capi)
	runtime.KeepAlive(capiAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// QueryAPI function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglQueryAPI.xhtml
func QueryAPI() Enum {
	__ret := C.eglQueryAPI()
	__v := (Enum)(__ret)
	return __v
}

// CreatePbufferFromClientBuffer function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreatePbufferFromClientBuffer.xhtml
func CreatePbufferFromClientBuffer(dpy Display, buftype Enum, buffer ClientBuffer, config Config, attribList []int32) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cbuftype, cbuftypeAllocMap := (C.EGLenum)(buftype), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (C.EGLClientBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLint)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreatePbufferFromClientBuffer(cdpy, cbuftype, cbuffer, cconfig, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(cbuftypeAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// ReleaseThread function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglReleaseThread.xhtml
func ReleaseThread() Boolean {
	__ret := C.eglReleaseThread()
	__v := (Boolean)(__ret)
	return __v
}

// WaitClient function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglWaitClient.xhtml
func WaitClient() Boolean {
	__ret := C.eglWaitClient()
	__v := (Boolean)(__ret)
	return __v
}

// GetCurrentContext function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetCurrentContext.xhtml
func GetCurrentContext() Context {
	__ret := C.eglGetCurrentContext()
	__v := *(*Context)(unsafe.Pointer(&__ret))
	return __v
}

// CreateSync function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreateSync.xhtml
func CreateSync(dpy Display, kind Enum, attribList *Attrib) Sync {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	ckind, ckindAllocMap := (C.EGLenum)(kind), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLAttrib)(unsafe.Pointer(attribList)), cgoAllocsUnknown
	__ret := C.eglCreateSync(cdpy, ckind, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(ckindAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Sync)(unsafe.Pointer(&__ret))
	return __v
}

// DestroySync function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglDestroySync.xhtml
func DestroySync(dpy Display, sync Sync) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csync, csyncAllocMap := (C.EGLSync)(unsafe.Pointer(sync)), cgoAllocsUnknown
	__ret := C.eglDestroySync(cdpy, csync)
	runtime.KeepAlive(csyncAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// ClientWaitSync function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglClientWaitSync.xhtml
func ClientWaitSync(dpy Display, sync Sync, flags int32, timeout Time) Int {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csync, csyncAllocMap := (C.EGLSync)(unsafe.Pointer(sync)), cgoAllocsUnknown
	cflags, cflagsAllocMap := (C.EGLint)(flags), cgoAllocsUnknown
	ctimeout, ctimeoutAllocMap := (C.EGLTime)(timeout), cgoAllocsUnknown
	__ret := C.eglClientWaitSync(cdpy, csync, cflags, ctimeout)
	runtime.KeepAlive(ctimeoutAllocMap)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(csyncAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Int)(__ret)
	return __v
}

// GetSyncAttrib function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetSyncAttrib.xhtml
func GetSyncAttrib(dpy Display, sync Sync, attribute int32, value *Attrib) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csync, csyncAllocMap := (C.EGLSync)(unsafe.Pointer(sync)), cgoAllocsUnknown
	cattribute, cattributeAllocMap := (C.EGLint)(attribute), cgoAllocsUnknown
	cvalue, cvalueAllocMap := (*C.EGLAttrib)(unsafe.Pointer(value)), cgoAllocsUnknown
	__ret := C.eglGetSyncAttrib(cdpy, csync, cattribute, cvalue)
	runtime.KeepAlive(cvalueAllocMap)
	runtime.KeepAlive(cattributeAllocMap)
	runtime.KeepAlive(csyncAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// CreateImage function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreateImage.xhtml
func CreateImage(dpy Display, ctx Context, target Enum, buffer ClientBuffer, attribList []Attrib) Image {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cctx, cctxAllocMap := (C.EGLContext)(unsafe.Pointer(ctx)), cgoAllocsUnknown
	ctarget, ctargetAllocMap := (C.EGLenum)(target), cgoAllocsUnknown
	cbuffer, cbufferAllocMap := (C.EGLClientBuffer)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLAttrib)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&attribList)).Data)), cgoAllocsUnknown
	__ret := C.eglCreateImage(cdpy, cctx, ctarget, cbuffer, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cbufferAllocMap)
	runtime.KeepAlive(ctargetAllocMap)
	runtime.KeepAlive(cctxAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Image)(unsafe.Pointer(&__ret))
	return __v
}

// DestroyImage function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglDestroyImage.xhtml
func DestroyImage(dpy Display, image Image) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cimage, cimageAllocMap := (C.EGLImage)(unsafe.Pointer(image)), cgoAllocsUnknown
	__ret := C.eglDestroyImage(cdpy, cimage)
	runtime.KeepAlive(cimageAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}

// GetPlatformDisplay function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglGetPlatformDisplay.xhtml
func GetPlatformDisplay(platform Enum, nativeDisplay unsafe.Pointer, attribList *Attrib) Display {
	cplatform, cplatformAllocMap := (C.EGLenum)(platform), cgoAllocsUnknown
	cnativeDisplay, cnativeDisplayAllocMap := nativeDisplay, cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLAttrib)(unsafe.Pointer(attribList)), cgoAllocsUnknown
	__ret := C.eglGetPlatformDisplay(cplatform, cnativeDisplay, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cnativeDisplayAllocMap)
	runtime.KeepAlive(cplatformAllocMap)
	__v := *(*Display)(unsafe.Pointer(&__ret))
	return __v
}

// CreatePlatformWindowSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreatePlatformWindowSurface.xhtml
func CreatePlatformWindowSurface(dpy Display, config Config, nativeWindow unsafe.Pointer, attribList *Attrib) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cnativeWindow, cnativeWindowAllocMap := nativeWindow, cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLAttrib)(unsafe.Pointer(attribList)), cgoAllocsUnknown
	__ret := C.eglCreatePlatformWindowSurface(cdpy, cconfig, cnativeWindow, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cnativeWindowAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// CreatePlatformPixmapSurface function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglCreatePlatformPixmapSurface.xhtml
func CreatePlatformPixmapSurface(dpy Display, config Config, nativePixmap unsafe.Pointer, attribList *Attrib) Surface {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	cconfig, cconfigAllocMap := (C.EGLConfig)(unsafe.Pointer(config)), cgoAllocsUnknown
	cnativePixmap, cnativePixmapAllocMap := nativePixmap, cgoAllocsUnknown
	cattribList, cattribListAllocMap := (*C.EGLAttrib)(unsafe.Pointer(attribList)), cgoAllocsUnknown
	__ret := C.eglCreatePlatformPixmapSurface(cdpy, cconfig, cnativePixmap, cattribList)
	runtime.KeepAlive(cattribListAllocMap)
	runtime.KeepAlive(cnativePixmapAllocMap)
	runtime.KeepAlive(cconfigAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := *(*Surface)(unsafe.Pointer(&__ret))
	return __v
}

// WaitSync function as declared in https://www.khronos.org/registry/egl/sdk/docs/man/html/eglWaitSync.xhtml
func WaitSync(dpy Display, sync Sync, flags int32) Boolean {
	cdpy, cdpyAllocMap := (C.EGLDisplay)(unsafe.Pointer(dpy)), cgoAllocsUnknown
	csync, csyncAllocMap := (C.EGLSync)(unsafe.Pointer(sync)), cgoAllocsUnknown
	cflags, cflagsAllocMap := (C.EGLint)(flags), cgoAllocsUnknown
	__ret := C.eglWaitSync(cdpy, csync, cflags)
	runtime.KeepAlive(cflagsAllocMap)
	runtime.KeepAlive(csyncAllocMap)
	runtime.KeepAlive(cdpyAllocMap)
	__v := (Boolean)(__ret)
	return __v
}
