// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on 18 Mar 2026.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package egl

/*
#cgo LDFLAGS: -lEGL
#include <EGL/egl.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Boolean type as declared in egl.h:54
type Boolean uint32

// Display type as declared in egl.h:55
type Display unsafe.Pointer

// Config type as declared in egl.h:58
type Config unsafe.Pointer

// Surface type as declared in egl.h:59
type Surface unsafe.Pointer

// Context type as declared in egl.h:60
type Context unsafe.Pointer

// Enum type as declared in egl.h:171
type Enum uint32

// ClientBuffer type as declared in egl.h:172
type ClientBuffer unsafe.Pointer

// Sync type as declared in egl.h:240
type Sync unsafe.Pointer

// Attrib type as declared in egl.h:241
type Attrib int32

// Time type as declared in egl.h:242
type Time uint32

// Image type as declared in egl.h:243
type Image unsafe.Pointer

// NativeWindowType as declared in eglplatform.h:103
type NativeWindowType C.EGLNativeWindowType

// NativePixmapType as declared in eglplatform.h:104
type NativePixmapType C.EGLNativePixmapType

// NativeDisplayType type as declared in eglplatform.h:105
type NativeDisplayType unsafe.Pointer

// Int type as declared in eglplatform.h:154
type Int int32
